/*
 * SPDX-FileCopyrightText: 2025 CERN
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

CREATE TYPE ARCHIVE_JOB_STATUS AS ENUM (
  'AJS_ToTransferForUser',
  'AJS_WaitReplicasBeforeReportingSuccessToDisk',
  'AJS_ToReportToUserForSuccess',
  'AJS_Complete',
  'AJS_ToReportToUserForFailure',
  'AJS_Failed',
  'AJS_Abandoned',
  'AJS_ToTransferForRepack',
  'AJS_ToReportToRepackForSuccess',
  'AJS_ToReportToRepackForFailure',
  'ReadyForDeletion',
  'Cancelled');
CREATE TYPE RETRIEVE_JOB_STATUS AS ENUM (
  'RJS_ToTransfer',
  'RJS_ToReportToUserForSuccess',
  'RJS_ToReportToUserForFailure',
  'RJS_Failed',
  'RJS_Complete',
  'RJS_ToReportToRepackForSuccess',
  'RJS_ToReportToRepackForFailure',
  'ReadyForDeletion',
  'Cancelled');
CREATE TYPE REPACK_REQ_STATUS AS ENUM (
  'RRS_Pending',
  'RRS_ToExpand',
  'RRS_Starting',
  'RRS_Running',
  'RRS_Complete',
  'RRS_Failed' );
CREATE TABLE ARCHIVE_ACTIVE_QUEUE(
/* Common part with RETRIEVE table - request related info */
  JOB_ID BIGSERIAL PRIMARY KEY,
/* Common part with RETRIEVE and REPACK table - request related info */
  ARCHIVE_REQUEST_ID BIGINT,
  REQUEST_JOB_COUNT SMALLINT,
  STATUS ARCHIVE_JOB_STATUS CONSTRAINT AJQ_S_NN NOT NULL,
  CREATION_TIME BIGINT,
/* TIMESTAMP NOT NULL, */
  MOUNT_POLICY VARCHAR(100) CONSTRAINT AJQ_MPN_NN NOT NULL,
  TAPE_POOL VARCHAR(100) CONSTRAINT AJQ_TPN_NN NOT NULL,
  VID VARCHAR(20),
/* Common part with RETRIEVE table - request related info */
  MOUNT_ID BIGINT,
  DRIVE VARCHAR(100),
  HOST VARCHAR(100),
  MOUNT_TYPE VARCHAR(100),
  LOGICAL_LIBRARY VARCHAR(100),
  START_TIME BIGINT,
  PRIORITY SMALLINT CONSTRAINT AJQ_MPAP_NN NOT NULL,
  STORAGE_CLASS VARCHAR(100),
  MIN_ARCHIVE_REQUEST_AGE INTEGER CONSTRAINT AJQ_MPAMR_NN NOT NULL,
  COPY_NB NUMERIC(3, 0),
  SIZE_IN_BYTES BIGINT,
  ARCHIVE_FILE_ID BIGINT,
  CHECKSUMBLOB BYTEA,
  REQUESTER_NAME VARCHAR(100),
  REQUESTER_GROUP VARCHAR(100),
  SRC_URL VARCHAR(2000),
  DISK_INSTANCE VARCHAR(100),
  DISK_FILE_PATH VARCHAR(2000),
  DISK_FILE_ID VARCHAR(100),
  DISK_FILE_GID INTEGER,
  DISK_FILE_OWNER_UID INTEGER,
  ARCHIVE_ERROR_REPORT_URL VARCHAR(2000),
  ARCHIVE_REPORT_URL VARCHAR(2000),
/* ARCHIVE specific columns */
/* REPACK_DEST_VID VARCHAR(20), */
  TOTAL_RETRIES SMALLINT,
  MAX_TOTAL_RETRIES SMALLINT,
  RETRIES_WITHIN_MOUNT SMALLINT,
  MAX_RETRIES_WITHIN_MOUNT SMALLINT,
  LAST_MOUNT_WITH_FAILURE BIGINT,
  IS_REPORTING BOOLEAN DEFAULT FALSE,
/* ARCHIVE specific columns */
  FAILURE_LOG TEXT DEFAULT '',
  LAST_UPDATE_TIME INTEGER DEFAULT (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::INTEGER),
  REPORT_FAILURE_LOG TEXT DEFAULT '',
  TOTAL_REPORT_RETRIES SMALLINT,
  MAX_REPORT_RETRIES SMALLINT
/* REPACK_FILEBUF_URL VARCHAR(2000), */
/* REPACK_FSEQ NUMERIC(20, 0) */
/* PARTITION BY RANGE (CREATION_TIME) */
/* CREATE TABLE ARCHIVE_ACTIVE_QUEUE_DEFAULT PARTITION OF ARCHIVE_ACTIVE_QUEUE DEFAULT */
/* ALTER TABLE ARCHIVE_ACTIVE_QUEUE ADD CONSTRAINT UNIQUE_ARCHIVE_COPY UNIQUE (ARCHIVE_FILE_ID) */
);
CREATE TABLE ARCHIVE_PENDING_QUEUE (LIKE ARCHIVE_ACTIVE_QUEUE INCLUDING ALL);
CREATE TABLE ARCHIVE_FAILED_QUEUE (LIKE ARCHIVE_ACTIVE_QUEUE INCLUDING ALL);

CREATE INDEX IDX_ARCHIVE_PENDING_QUEUE_FILTER_SORT ON ARCHIVE_PENDING_QUEUE (TAPE_POOL, STATUS, PRIORITY DESC, JOB_ID);
CREATE INDEX IDX_ARCHIVE_PENDING_QUEUE_MOUNT_ID_NN ON ARCHIVE_PENDING_QUEUE (MOUNT_ID) WHERE MOUNT_ID IS NOT NULL;
/* creating REPACK_ARCHIVE_PENDING_QUEUE only with the indices above */
CREATE TABLE REPACK_ARCHIVE_PENDING_QUEUE (LIKE ARCHIVE_PENDING_QUEUE INCLUDING ALL);
ALTER TABLE REPACK_ARCHIVE_PENDING_QUEUE ADD COLUMN REPACK_REQUEST_ID BIGINT;

CREATE INDEX IDX_ARCHIVE_ACTIVE_QUEUE_MOUNT_ID_CLEAN_UP ON ARCHIVE_ACTIVE_QUEUE (MOUNT_ID, JOB_ID) WHERE IS_REPORTING IS FALSE;
/* creating REPACK_ARCHIVE_ACTIVE_QUEUE only with the indices above */
CREATE TABLE REPACK_ARCHIVE_ACTIVE_QUEUE (LIKE ARCHIVE_ACTIVE_QUEUE INCLUDING ALL);
ALTER TABLE REPACK_ARCHIVE_ACTIVE_QUEUE ADD COLUMN REPACK_REQUEST_ID BIGINT;
/* unnecessary index CREATE INDEX IDX_REPACK_ARCHIVE_ACTIVE_QUEUE_SINGLE_COPY ON REPACK_ARCHIVE_ACTIVE_QUEUE (JOB_ID) WHERE REQUEST_JOB_COUNT = 1 */
/* unnecessary index CREATE INDEX IDX_REPACK_ARCHIVE_ACTIVE_QUEUE_MULTI_COPY ON REPACK_ARCHIVE_ACTIVE_QUEUE (JOB_ID) WHERE REQUEST_JOB_COUNT > 1 */
CREATE INDEX IDX_ARCHIVE_ACTIVE_QUEUE_REQUEST_ID_MULTI_COPY ON ARCHIVE_ACTIVE_QUEUE (ARCHIVE_REQUEST_ID, STATUS, JOB_ID);
CREATE INDEX IDX_ARCHIVE_ACTIVE_QUEUE_REPORTING_NEW ON ARCHIVE_ACTIVE_QUEUE (STATUS) WHERE IS_REPORTING IS FALSE;
CREATE INDEX IDX_ARCHIVE_ACTIVE_QUEUE_REPORTING_RECYCLE ON ARCHIVE_ACTIVE_QUEUE (STATUS, LAST_UPDATE_TIME) WHERE IS_REPORTING IS TRUE;
/* CREATE INDEX IDX_ARCHIVE_ACTIVE_QUEUE_REQUEST_ID_MULTI_COPY_THROUGHPUT ON ARCHIVE_ACTIVE_QUEUE (ARCHIVE_REQUEST_ID, STATUS) INCLUDE (JOB_ID, REQUEST_JOB_COUNT) */
CREATE TABLE REPACK_ARCHIVE_FAILED_QUEUE (LIKE REPACK_ARCHIVE_ACTIVE_QUEUE INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STATISTICS INCLUDING STORAGE INCLUDING COMMENTS);


CREATE TABLE RETRIEVE_ACTIVE_QUEUE(
  JOB_ID BIGSERIAL PRIMARY KEY,
  RETRIEVE_REQUEST_ID BIGINT,
  REQUEST_JOB_COUNT SMALLINT,
  STATUS RETRIEVE_JOB_STATUS CONSTRAINT RJQ_S_NN NOT NULL,
  ARCHIVE_FILE_ID BIGINT,
  CREATION_TIME BIGINT,
  STORAGE_CLASS VARCHAR(100),
  SIZE_IN_BYTES BIGINT,
  CHECKSUMBLOB BYTEA,
  FSEQ BIGINT,
  BLOCK_ID BIGINT,
  DISK_INSTANCE VARCHAR(100),
  DISK_FILE_PATH VARCHAR(2000),
  DISK_FILE_ID VARCHAR(100),
  DISK_FILE_GID INTEGER,
  DISK_FILE_OWNER_UID INTEGER,
  TAPE_POOL VARCHAR(100),
  MOUNT_POLICY VARCHAR(100) CONSTRAINT RJQ_MPN_NN NOT NULL,
  VID VARCHAR(20) CONSTRAINT RJQ_TPN_NN NOT NULL,
  ALTERNATE_COPY_NBS VARCHAR(20),
  ALTERNATE_FSEQS VARCHAR(256),
  ALTERNATE_BLOCK_IDS VARCHAR(256),
  ALTERNATE_VIDS VARCHAR(128),
  MOUNT_ID BIGINT,
  DRIVE VARCHAR(100),
  HOST VARCHAR(100),
  LOGICAL_LIBRARY VARCHAR(100),
  START_TIME BIGINT,
  PRIORITY SMALLINT CONSTRAINT RJQ_MPAP_NN NOT NULL,
  MIN_RETRIEVE_REQUEST_AGE INTEGER CONSTRAINT RJQ_MPAMR_NN NOT NULL,
  COPY_NB NUMERIC(3, 0),
  REQUESTER_NAME VARCHAR(100),
  REQUESTER_GROUP VARCHAR(100),
  DST_URL VARCHAR(2000),
  RETRIEVE_ERROR_REPORT_URL VARCHAR(2000),
  RETRIEVE_REPORT_URL VARCHAR(2000),
  TOTAL_RETRIES SMALLINT,
  MAX_TOTAL_RETRIES SMALLINT,
  RETRIES_WITHIN_MOUNT SMALLINT,
  MAX_RETRIES_WITHIN_MOUNT SMALLINT,
  LAST_MOUNT_WITH_FAILURE BIGINT,
  IS_REPORTING BOOLEAN DEFAULT FALSE,
  FAILURE_LOG TEXT DEFAULT '',
  LAST_UPDATE_TIME INTEGER DEFAULT (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::INTEGER),
  REPORT_FAILURE_LOG TEXT DEFAULT '',
  TOTAL_REPORT_RETRIES SMALLINT,
  MAX_REPORT_RETRIES SMALLINT,
  ACTIVITY VARCHAR(100),
  SRR_USERNAME VARCHAR(100),
  SRR_HOST VARCHAR(100),
  SRR_TIME BIGINT,
  SRR_MOUNT_POLICY VARCHAR(100),
  SRR_ACTIVITY VARCHAR(100),
/* User is_verify from schedulerretrieverequest */
  IS_VERIFY_ONLY BOOLEAN DEFAULT FALSE,
  LIFECYCLE_CREATION_TIME BIGINT,
  LIFECYCLE_FIRST_SELECTED_TIME BIGINT,
  LIFECYCLE_COMPLETED_TIME BIGINT,
  DISK_SYSTEM_NAME VARCHAR(256)
);

/* ALTER TABLE RETRIEVE_ACTIVE_QUEUE ADD CONSTRAINT UNIQUE_RETRIEVE_COPY UNIQUE (ARCHIVE_FILE_ID) */
CREATE TABLE RETRIEVE_PENDING_QUEUE (LIKE RETRIEVE_ACTIVE_QUEUE INCLUDING ALL);
CREATE TABLE RETRIEVE_FAILED_QUEUE (LIKE RETRIEVE_ACTIVE_QUEUE INCLUDING ALL);

CREATE INDEX IDX_RETRIEVE_PENDING_QUEUE_FILTER_SORT ON RETRIEVE_PENDING_QUEUE (VID, STATUS, PRIORITY DESC, JOB_ID);
CREATE INDEX IDX_RETRIEVE_PENDING_QUEUE_FILTER_SORT_MOUNT_ID_NN ON RETRIEVE_PENDING_QUEUE (MOUNT_ID) WHERE MOUNT_ID IS NOT NULL;
/* creating REPACK_RETRIEVE_PENDING_QUEUE only with the indices above */
CREATE TABLE REPACK_RETRIEVE_PENDING_QUEUE (LIKE RETRIEVE_PENDING_QUEUE INCLUDING ALL);
ALTER TABLE REPACK_RETRIEVE_PENDING_QUEUE ADD COLUMN REPACK_REQUEST_ID BIGINT;
/* COPY_NB is NUMERIC(3, 0) upto 1000, REPACK_REARCHIVE_COPY_NBS is a comma separated list of COPY_NBS and we do not have mor ethan 3 copies (1,2,3), VARCHAR(20) would allow up 10 copies which is far enough */
ALTER TABLE REPACK_RETRIEVE_PENDING_QUEUE ADD COLUMN REPACK_REARCHIVE_COPY_NBS VARCHAR(20);
ALTER TABLE REPACK_RETRIEVE_PENDING_QUEUE ADD COLUMN REPACK_REARCHIVE_TAPE_POOLS VARCHAR(2000);

CREATE INDEX IDX_RETRIEVE_ACTIVE_QUEUE_MOUNT_ID_CLEAN_UP ON RETRIEVE_ACTIVE_QUEUE (MOUNT_ID, JOB_ID) WHERE IS_REPORTING IS FALSE;
/* creating REPACK_RETRIEVE_ACTIVE_QUEUE only with the index above */
CREATE TABLE REPACK_RETRIEVE_ACTIVE_QUEUE (LIKE RETRIEVE_ACTIVE_QUEUE INCLUDING ALL);
ALTER TABLE REPACK_RETRIEVE_ACTIVE_QUEUE ADD COLUMN REPACK_REQUEST_ID BIGINT;
/* COPY_NB is NUMERIC(3, 0) upto 1000, REPACK_REARCHIVE_COPY_NBS is a comma separated list of COPY_NBS and we do not have mor ethan 3 copies (1,2,3), VARCHAR(20) would allow up 10 copies which is far enough */
ALTER TABLE REPACK_RETRIEVE_ACTIVE_QUEUE ADD COLUMN REPACK_REARCHIVE_COPY_NBS VARCHAR(20);
ALTER TABLE REPACK_RETRIEVE_ACTIVE_QUEUE ADD COLUMN REPACK_REARCHIVE_TAPE_POOLS VARCHAR(2000);

CREATE INDEX IDX_RETRIEVE_ACTIVE_QUEUE_REPORTING_NEW ON RETRIEVE_ACTIVE_QUEUE (STATUS) WHERE IS_REPORTING IS FALSE;
CREATE INDEX IDX_RETRIEVE_ACTIVE_QUEUE_REPORTING_RECYCLE ON RETRIEVE_ACTIVE_QUEUE (STATUS, LAST_UPDATE_TIME) WHERE IS_REPORTING IS TRUE;

CREATE INDEX IDX_REPACK_RETRIEVE_ACTIVE_QUEUE_POP ON REPACK_RETRIEVE_ACTIVE_QUEUE (STATUS, PRIORITY DESC, JOB_ID);

CREATE TABLE REPACK_RETRIEVE_FAILED_QUEUE (LIKE REPACK_RETRIEVE_ACTIVE_QUEUE INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING GENERATED INCLUDING IDENTITY INCLUDING STATISTICS INCLUDING STORAGE INCLUDING COMMENTS);

CREATE TABLE MOUNT_QUEUE_LAST_FETCH (
  MOUNT_ID        BIGINT NOT NULL,
  LAST_UPDATE_TIME INTEGER DEFAULT (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::INTEGER),
  QUEUE_TYPE       VARCHAR(50),
  PRIMARY KEY (MOUNT_ID, QUEUE_TYPE)
);

CREATE INDEX IDX_MOUNT_QUEUE_LAST_FETCH ON MOUNT_QUEUE_LAST_FETCH (LAST_UPDATE_TIME);

CREATE TABLE REPACK_REQUEST_TRACKING(
  REPACK_REQUEST_ID BIGSERIAL PRIMARY KEY,
  VID VARCHAR(20),
  BUFFER_URL VARCHAR(2000),
  STATUS REPACK_REQ_STATUS,
  IS_ADD_COPIES BOOLEAN,
  IS_MOVE BOOLEAN,
  MAX_FILES_TO_EXPAND BIGINT,
  TOTAL_FILES_ON_TAPE_AT_START BIGINT,
  TOTAL_BYTES_ON_TAPE_AT_START BIGINT,
  ALL_FILES_SELECTED_AT_START BOOLEAN,
  TOTAL_FILES_TO_RETRIEVE BIGINT,
  TOTAL_BYTES_TO_RETRIEVE BIGINT,
  TOTAL_FILES_TO_ARCHIVE BIGINT,
  TOTAL_BYTES_TO_ARCHIVE BIGINT,
  USER_PROVIDED_FILES BIGINT,
  USER_PROVIDED_BYTES BIGINT,
  RETRIEVED_FILES BIGINT,
  RETRIEVED_BYTES BIGINT,
  ARCHIVED_FILES BIGINT,
  ARCHIVED_BYTES BIGINT,
  REARCHIVE_COPYNBS BIGINT,
  REARCHIVE_BYTES BIGINT,
  FAILED_TO_RETRIEVE_FILES BIGINT,
  FAILED_TO_RETRIEVE_BYTES BIGINT,
  FAILED_TO_CREATE_ARCHIVE_REQ BIGINT,
  FAILED_TO_ARCHIVE_FILES BIGINT,
  FAILED_TO_ARCHIVE_BYTES BIGINT,
  LAST_EXPANDED_FSEQ BIGINT,
  RETRIEVE_SUBREQUESTS_EXPANDED BIGINT,
  IS_EXPAND_FINISHED BOOLEAN,
  IS_EXPAND_STARTED  BOOLEAN,
  MOUNT_POLICY VARCHAR(100),
  IS_COMPLETE BOOLEAN,
  IS_NO_RECALL BOOLEAN,
  SUBREQ_PB BYTEA,
  DESTINFO_PB BYTEA,
  CREATE_USERNAME VARCHAR(100),
  CREATE_HOST VARCHAR(100),
  CREATE_TIME BIGINT,
  REPACK_FINISHED_TIME BIGINT,
  LAST_UPDATE_TIME INTEGER DEFAULT (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::INTEGER)
);
ALTER TABLE REPACK_REQUEST_TRACKING ADD CONSTRAINT UNIQUE_REPACK_VID UNIQUE (VID);
CREATE INDEX IDX_REPACK_REQUEST_TRACKING ON REPACK_REQUEST_TRACKING (STATUS, CREATE_TIME ASC);


CREATE TABLE REPACK_REQUEST_DESTINATION_STATISTICS(
  ID BIGSERIAL PRIMARY KEY,
  REPACK_REQUEST_ID BIGINT NOT NULL,
  VID VARCHAR(20),
  ARCHIVED_FILES BIGINT,
  ARCHIVED_BYTES BIGINT
);

ALTER TABLE REPACK_REQUEST_DESTINATION_STATISTICS ADD CONSTRAINT FK_REPACK_REQ_STATS_TO_TRACKING FOREIGN KEY(REPACK_REQUEST_ID) REFERENCES REPACK_REQUEST_TRACKING(REPACK_REQUEST_ID) ON DELETE CASCADE;
ALTER TABLE REPACK_REQUEST_DESTINATION_STATISTICS ADD CONSTRAINT UNIQUE_REPACK_REQ_VID_DESTINATION UNIQUE (REPACK_REQUEST_ID, VID);

ALTER TABLE REPACK_RETRIEVE_PENDING_QUEUE ADD CONSTRAINT FK_REPACK_RETRIEVE_PENDING_REQ_TO_TRACKING FOREIGN KEY(REPACK_REQUEST_ID) REFERENCES REPACK_REQUEST_TRACKING(REPACK_REQUEST_ID) ON DELETE CASCADE;
ALTER TABLE REPACK_ARCHIVE_PENDING_QUEUE ADD CONSTRAINT FK_REPACK_ARCHIVE_PENDING_REQ_TO_TRACKING FOREIGN KEY(REPACK_REQUEST_ID) REFERENCES REPACK_REQUEST_TRACKING(REPACK_REQUEST_ID) ON DELETE CASCADE;

CREATE TABLE DISK_SYSTEM_SLEEP_TRACKING (
    DISK_SYSTEM_NAME VARCHAR(256) PRIMARY KEY,
    SLEEP_TIME BIGINT,
    LAST_UPDATE_TIME INTEGER DEFAULT (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::INTEGER)
);

CREATE TABLE TAPE_MOUNTS(
  MOUNT_ID BIGSERIAL,
  CREATION_TIME TIMESTAMPTZ DEFAULT NOW(),
  OWNER VARCHAR(100)
);

CREATE VIEW ARCHIVE_QUEUE_SUMMARY AS (SELECT STATUS,
    TAPE_POOL,
    MOUNT_POLICY,
    MOUNT_ID,
    COUNT(*) AS JOBS_COUNT,
    SUM(SIZE_IN_BYTES) AS JOBS_TOTAL_SIZE,
    MIN(START_TIME) AS OLDEST_JOB_START_TIME,
    MAX(PRIORITY) AS ARCHIVE_PRIORITY,
    MIN(MIN_ARCHIVE_REQUEST_AGE) AS ARCHIVE_MIN_REQUEST_AGE,
    MAX(LAST_UPDATE_TIME) AS LAST_JOB_UPDATE_TIME
        FROM ARCHIVE_PENDING_QUEUE WHERE MOUNT_ID IS NULL GROUP BY STATUS, TAPE_POOL, MOUNT_POLICY, MOUNT_ID
    );

CREATE VIEW REPACK_ARCHIVE_QUEUE_SUMMARY AS (SELECT STATUS,
    TAPE_POOL,
    MOUNT_POLICY,
    MOUNT_ID,
    COUNT(*) AS JOBS_COUNT,
    SUM(SIZE_IN_BYTES) AS JOBS_TOTAL_SIZE,
    MIN(START_TIME) AS OLDEST_JOB_START_TIME,
    MAX(PRIORITY) AS ARCHIVE_PRIORITY,
    MIN(MIN_ARCHIVE_REQUEST_AGE) AS ARCHIVE_MIN_REQUEST_AGE,
    MAX(LAST_UPDATE_TIME) AS LAST_JOB_UPDATE_TIME
        FROM REPACK_ARCHIVE_PENDING_QUEUE WHERE MOUNT_ID IS NULL GROUP BY STATUS, TAPE_POOL, MOUNT_POLICY, MOUNT_ID
    );

CREATE VIEW RETRIEVE_QUEUE_SUMMARY AS (SELECT
    VID,
    MOUNT_POLICY,
    ACTIVITY,
    DISK_SYSTEM_NAME,
    MAX(PRIORITY) AS PRIORITY,
    COUNT(*) AS JOBS_COUNT,
    SUM(SIZE_IN_BYTES) AS JOBS_TOTAL_SIZE,
    MIN(START_TIME) AS OLDEST_JOB_START_TIME,
    MAX(START_TIME) AS YOUNGEST_JOB_START_TIME,
    MIN(MIN_RETRIEVE_REQUEST_AGE) AS RETRIEVE_MIN_REQUEST_AGE,
    MAX(LAST_UPDATE_TIME) AS LAST_JOB_UPDATE_TIME
        FROM RETRIEVE_PENDING_QUEUE WHERE MOUNT_ID IS NULL GROUP BY VID, MOUNT_POLICY, ACTIVITY, DISK_SYSTEM_NAME
    );

CREATE VIEW REPACK_RETRIEVE_QUEUE_SUMMARY AS (SELECT
    VID,
    MOUNT_POLICY,
    ACTIVITY,
    DISK_SYSTEM_NAME,
    MAX(PRIORITY) AS PRIORITY,
    COUNT(*) AS JOBS_COUNT,
    SUM(SIZE_IN_BYTES) AS JOBS_TOTAL_SIZE,
    MIN(START_TIME) AS OLDEST_JOB_START_TIME,
    MAX(START_TIME) AS YOUNGEST_JOB_START_TIME,
    MIN(MIN_RETRIEVE_REQUEST_AGE) AS RETRIEVE_MIN_REQUEST_AGE,
    MAX(LAST_UPDATE_TIME) AS LAST_JOB_UPDATE_TIME
        FROM REPACK_RETRIEVE_PENDING_QUEUE WHERE MOUNT_ID IS NULL GROUP BY VID, MOUNT_POLICY, ACTIVITY, DISK_SYSTEM_NAME
    );

CREATE SEQUENCE MOUNT_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    NO MAXVALUE
    MINVALUE 1
    NO CYCLE
    CACHE 1;
CREATE SEQUENCE ARCHIVE_REQUEST_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    NO MAXVALUE
    MINVALUE 1
    NO CYCLE
    CACHE 1;
CREATE SEQUENCE RETRIEVE_REQUEST_ID_SEQ
    INCREMENT BY 1
    START WITH 1
    NO MAXVALUE
    MINVALUE 1
    NO CYCLE
    CACHE 1;
