.TH jobmanagerd 8 "$Date: 2009/08/18 09:42:52 $" CASTOR "CASTOR2 Job Manager Daemon"
.SH NAME
jobmanagerd \- CASTOR2 job manager deamon
.SH SYNOPSIS
.B jobmanagerd
[
.BI -f
]
[
.BI -c " <config-file>"
]
[
.BI -h
]
.LP
.SH DESCRIPTION
The
.B jobmanagerd
is the CASTOR2 job manager daemon used to submit new jobs into the LSF scheduler and
too monitor jobs waiting to be scheduled on diskservers. If no options are specified on
the command-line then the default configuration file (usually \fI/etc/castor/castor.conf\fR) will be used.

The
.B -f, --foreground
option forces the
.B jobmanagerd
to run in the foreground. The default is to run in the background as a "daemon".

The
.B -c, --config
option instructs the
.B jobmanagerd
to load its configuration settings from the file pointed to by \fI<config-file>

.SH FILES
The
.B jobmanagerd
daemon requires access to the CASTOR2 stager database. The
.B /etc/castor/ORASTAGERCONFIG
file is used
to define the username and password that should be used to connect to this database.
Refer to
.B /etc/castor/ORASTAGERCONFIG.example
for an example of how this file should be formatted.

All configuration settings for the
.B jobmanagerd
can found in
.B /etc/castor/castor.conf

By default all log messages from the
.B jobmanagerd
are written too
.B /var/log/castor/jobmanagerd.log
as well as the Distributed Logging Facility.

.SH SEE ALSO
lsfintro(1)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
