# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

resetMountDecision: false

resetImage:
  repository: gitlab-registry.cern.ch/cta/ctageneric
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets:
    - reg-ctageneric

# configuration:
#   backend: "postgres"
#   postgresConfig:
#     remote: false
#     username: ""
#     password: ""
#     database: ""
#     server: ""
#     path: ""

# This is only for the postgres pod
pod:
  extraSpec:
    # We want to know if something went wrong in CI
    restartPolicy: Never
