// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "DeleteLogParams.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace castor {
namespace messages {

namespace {

const ::google::protobuf::Descriptor* DeleteLogParams_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DeleteLogParams_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_DeleteLogParams_2eproto() {
  protobuf_AddDesc_DeleteLogParams_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "DeleteLogParams.proto");
  GOOGLE_CHECK(file != NULL);
  DeleteLogParams_descriptor_ = file->message_type(0);
  static const int DeleteLogParams_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteLogParams, unitname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteLogParams, param_names_),
  };
  DeleteLogParams_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DeleteLogParams_descriptor_,
      DeleteLogParams::default_instance_,
      DeleteLogParams_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteLogParams, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DeleteLogParams, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DeleteLogParams));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_DeleteLogParams_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DeleteLogParams_descriptor_, &DeleteLogParams::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_DeleteLogParams_2eproto() {
  delete DeleteLogParams::default_instance_;
  delete DeleteLogParams_reflection_;
}

void protobuf_AddDesc_DeleteLogParams_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025DeleteLogParams.proto\022\017castor.messages"
    "\"8\n\017DeleteLogParams\022\020\n\010unitname\030\001 \002(\t\022\023\n"
    "\013param_names\030\002 \003(\t", 98);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DeleteLogParams.proto", &protobuf_RegisterTypes);
  DeleteLogParams::default_instance_ = new DeleteLogParams();
  DeleteLogParams::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_DeleteLogParams_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_DeleteLogParams_2eproto {
  StaticDescriptorInitializer_DeleteLogParams_2eproto() {
    protobuf_AddDesc_DeleteLogParams_2eproto();
  }
} static_descriptor_initializer_DeleteLogParams_2eproto_;


// ===================================================================

const ::std::string DeleteLogParams::_default_unitname_;
#ifndef _MSC_VER
const int DeleteLogParams::kUnitnameFieldNumber;
const int DeleteLogParams::kParamNamesFieldNumber;
#endif  // !_MSC_VER

DeleteLogParams::DeleteLogParams()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void DeleteLogParams::InitAsDefaultInstance() {
}

DeleteLogParams::DeleteLogParams(const DeleteLogParams& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void DeleteLogParams::SharedCtor() {
  _cached_size_ = 0;
  unitname_ = const_cast< ::std::string*>(&_default_unitname_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DeleteLogParams::~DeleteLogParams() {
  SharedDtor();
}

void DeleteLogParams::SharedDtor() {
  if (unitname_ != &_default_unitname_) {
    delete unitname_;
  }
  if (this != default_instance_) {
  }
}

void DeleteLogParams::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DeleteLogParams::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DeleteLogParams_descriptor_;
}

const DeleteLogParams& DeleteLogParams::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_DeleteLogParams_2eproto();  return *default_instance_;
}

DeleteLogParams* DeleteLogParams::default_instance_ = NULL;

DeleteLogParams* DeleteLogParams::New() const {
  return new DeleteLogParams;
}

void DeleteLogParams::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (unitname_ != &_default_unitname_) {
        unitname_->clear();
      }
    }
  }
  param_names_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DeleteLogParams::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string unitname = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_unitname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->unitname().data(), this->unitname().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_param_names;
        break;
      }
      
      // repeated string param_names = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_param_names:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_param_names()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->param_names(0).data(), this->param_names(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_param_names;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void DeleteLogParams::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string unitname = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->unitname().data(), this->unitname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->unitname(), output);
  }
  
  // repeated string param_names = 2;
  for (int i = 0; i < this->param_names_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->param_names(i).data(), this->param_names(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->param_names(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* DeleteLogParams::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string unitname = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->unitname().data(), this->unitname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->unitname(), target);
  }
  
  // repeated string param_names = 2;
  for (int i = 0; i < this->param_names_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->param_names(i).data(), this->param_names(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->param_names(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int DeleteLogParams::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string unitname = 1;
    if (has_unitname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->unitname());
    }
    
  }
  // repeated string param_names = 2;
  total_size += 1 * this->param_names_size();
  for (int i = 0; i < this->param_names_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->param_names(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DeleteLogParams::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DeleteLogParams* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DeleteLogParams*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DeleteLogParams::MergeFrom(const DeleteLogParams& from) {
  GOOGLE_CHECK_NE(&from, this);
  param_names_.MergeFrom(from.param_names_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_unitname(from.unitname());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DeleteLogParams::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DeleteLogParams::CopyFrom(const DeleteLogParams& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeleteLogParams::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void DeleteLogParams::Swap(DeleteLogParams* other) {
  if (other != this) {
    std::swap(unitname_, other->unitname_);
    param_names_.Swap(&other->param_names_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DeleteLogParams::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DeleteLogParams_descriptor_;
  metadata.reflection = DeleteLogParams_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace messages
}  // namespace castor

// @@protoc_insertion_point(global_scope)
