{{- /*
SPDX-FileCopyrightText: 2026 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

{{- $schedulerConfig := include "scheduler.config" . | fromYaml }}
{{- if eq $schedulerConfig.backend "postgres" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cta-scheduler-init
data:
  01-init-scheduler.sql: |-
{{ tpl (.Files.Get "scripts/postgres-init-scheduler.sql.tpl") . | indent 4 }}
{{- end }}
