#!/usr/bin/python

import os, sys, random
from stressUtils import *

# print usage. Arguments should be <logFileName> <CastorPath> <instance> <svcClass>
def usage():
    print sys.argv[0] + " <logFileName> <CastorPath> <instance> <svcClass>"

# check number of input arguments
if len(sys.argv) != 5:
    print "Wrong number of arguments"
    usage()
    sys.exit(1)

# extract arguments and define default parameters
logFile = sys.argv[1]
baseCastorDir = sys.argv[2]
instance = sys.argv[3]
svcClass = sys.argv[4]
pathToCastorCommands = getCastorBinPath() + os.sep

# build common part of the command line
baseCmd = buildEnv(instance, svcClass, True)

# build a list of files to be read
print(baseCmd + pathToCastorCommands + "nsls " + baseCastorDir)
fileList = os.popen(baseCmd + pathToCastorCommands + "nsls " + baseCastorDir).read().split()

# Loop
counter = 0
while True:
    index = random.randint(0, len(fileList) - 1)
    fileName = getCastorDir(baseCastorDir, counter) + os.sep + fileList[index]
    command = baseCmd + pathToCastorCommands + "rfcp " + fileName + " /dev/null >> " + logFile + " 2>> " + logFile
    os.system(command)
    counter = counter + 1
