#!/usr/bin/python

import os, baseputloop, stressUtils
from putUtils import *

# all the preparation is done in baseputloop, we only have to execute the command
counter = 0
while True:
    createDirIfNeeded(baseputloop.baseCastorDir, counter)
    fileName = getCastorDir(baseCastorDir, counter) + os.sep + inputFileBaseName + "_" + host + "_" + stressUtils.buildUuid()
    command = baseCmd + pathToCastorCommands + "rfcp " + inputFile + " " + fileName + " >> " + logFile + " 2>> " + logFile
    os.system(command)
    counter = counter + 1
