{{- /*
SPDX-FileCopyrightText: 2025 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

{{- $schedulerConfig := include "scheduler.config" . | fromYaml -}}
{{ range .Values.drives }}
{{- $driveNameSlug := include "common.slugify" .name }}
# Generate unique config map for each tape drive
apiVersion: v1
kind: ConfigMap
metadata:
  name: cta-taped-{{ $driveNameSlug }}-conf
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
data:
  cta-taped.toml: |-

    [catalogue]
      config_file = "/etc/cta/cta-catalogue.conf"

    [scheduler]
      backend_name = {{ $schedulerConfig.backend | quote }}

      config_file = "/etc/cta/cta-scheduler.conf"
      {{- if eq $schedulerConfig.backend "postgres" }}
      number_of_connections = {{ $.Values.scheduler.numberOfConnections }}
      {{- end }}
      tape_cache_max_age_secs = {{ $.Values.scheduler.tapeCacheMaxAgeSecs }}
      retrieve_queue_cache_max_age_secs = {{ $.Values.scheduler.retrieveQueueCacheMaxAgeSecs }}

    [logging]
      level = {{ $.Values.logging.level | quote }}
      format = "json"
      [logging.attributes]
        instance = {{ $.Release.Namespace | quote }}
        sched_backend = {{ $schedulerConfig.backend | quote }}

    [telemetry]
      config_file = "/etc/cta/cta-otel.yaml"
      on_init_failure = "fatal"

    [health_server]
      enabled = true
      host = "0.0.0.0"
      port = 8080
      use_unix_domain_socket = false

    [xrootd]
      security_protocol = "sss"
      sss_keytab_path = "/etc/cta/cta-taped.sss.keytab.grp"

    [experimental]
      telemetry_enabled = {{ $.Values.telemetry.enabled }}

    [drive]
      name = {{ .name | quote }}
      device = {{ .device | quote }}
      control_path = {{ .controlPath | quote }}
      logical_library_name = {{ .logicalLibraryName | quote }}
      ready_timeout_secs = {{ $.Values.drive.readyTimeoutSecs }}

    [mounts]
      minimum_queued_bytes = {{ int64 $.Values.mounts.minimumQueuedBytes }}
      minimum_queued_files = {{ $.Values.mounts.minimumQueuedFiles }}
      scheduling_timeout_secs = {{ $.Values.mounts.schedulingTimeoutSecs }}
      get_next_mount_timeout_secs = {{ $.Values.mounts.getNextMountTimeoutSecs }}
      idle_scheduling_interval_secs = {{ $.Values.mounts.idleSchedulingIntervalSecs }}
      mount_timeout_secs = {{ $.Values.mounts.mountTimeoutSecs }}
      tape_load_timeout_secs = {{ $.Values.mounts.tapeLoadTimeoutSecs }}
      unmount_timeout_secs = {{ $.Values.mounts.unmountTimeoutSecs }}

    [rmcd]
      host = {{ $.Values.rmcd.host | quote }}
      port = {{ $.Values.rmcd.port }}
      request_timeout_secs = {{ $.Values.rmcd.requestTimeoutSecs }}
      request_attempts = {{ $.Values.rmcd.requestAttempts }}

    [transfers]
      buffer_count = {{ $.Values.transfers.bufferCount }}
      buffer_size_bytes = {{ $.Values.transfers.bufferSizeBytes }}
      disk_io_threads = {{ $.Values.transfers.diskIoThreads }}
      no_block_move_timeout_secs = {{ $.Values.transfers.noBlockMoveTimeoutSecs }}

    [transfers.archive]
      fetch_max_bytes = {{ int64 $.Values.transfers.archive.fetchMaxBytes }}
      fetch_max_files = {{ $.Values.transfers.archive.fetchMaxFiles }}
      flush_max_bytes = {{ int64 $.Values.transfers.archive.flushMaxBytes }}
      flush_max_files = {{ $.Values.transfers.archive.flushMaxFiles }}

    [transfers.archive.underfill]
      watch_period_secs = {{ $.Values.transfers.archive.underfill.watchPeriodSecs }}
      minimum_samples = {{ $.Values.transfers.archive.underfill.minimumSamples }}
      start_threshold_percent = {{ $.Values.transfers.archive.underfill.startThresholdPercent }}
      recovery_threshold_percent = {{ $.Values.transfers.archive.underfill.recoveryThresholdPercent }}

    [transfers.retrieve]
      fetch_max_bytes = {{ int64 $.Values.transfers.retrieve.fetchMaxBytes }}
      fetch_max_files = {{ $.Values.transfers.retrieve.fetchMaxFiles }}
      drain_to_disk_timeout_secs = {{ $.Values.transfers.retrieve.drainToDiskTimeoutSecs }}
      external_free_disk_space_script = {{ $.Values.transfers.retrieve.externalFreeDiskSpaceScript | quote }}

    [transfers.retrieve.rao]
      enabled = {{ $.Values.transfers.retrieve.rao.enabled }}
      lto_algorithm = {{ $.Values.transfers.retrieve.rao.ltoAlgorithm | quote }}

    [transfers.encryption]
      enabled = {{ $.Values.transfers.encryption.enabled }}
      external_key_script = {{ $.Values.transfers.encryption.externalKeyScript | quote }}

---
{{- end }}
