{{- /*
SPDX-FileCopyrightText: 2025 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

{{- $schedulerConfig := include "scheduler.config" . | fromYaml -}}
{{ range .Values.drives }}
{{- $driveNameSlug := include "common.slugify" .name }}
# Generate unique config map for each tape drive
apiVersion: v1
kind: ConfigMap
metadata:
  name: cta-taped-{{ $driveNameSlug }}-conf
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
data:
  cta-taped.toml: |-

    [catalogue]
      config_file = "/etc/cta/cta-catalogue.conf"

    [scheduler]
      backend_name = {{ $schedulerConfig.backend | quote }}
      {{- if eq $schedulerConfig.backend "postgres" }}
      config_file = "/etc/cta/cta-scheduler.conf"
      number_of_connections = {{ $.Values.scheduler.numberOfConnections }}
      {{- else }}
      objectstore_backend_path = {{ include "global.schedulerUrl" $ | quote }}
      {{- end }}
      tape_cache_max_age_secs = {{ $.Values.scheduler.tapeCacheMaxAgeSecs }}
      retrieve_queue_cache_max_age_secs = {{ $.Values.scheduler.retrieveQueueCacheMaxAgeSecs }}

    [logging]
      level = {{ $.Values.logging.level | quote }}
      format = "json"
      [logging.attributes]
        instance = {{ $.Release.Namespace | quote }}
        sched_backend = {{ $schedulerConfig.backend | quote }}

    [telemetry]
      config_file = "/etc/cta/cta-otel.yaml"
      on_init_failure = "fatal"

    [health_server]
      enabled = true
      host = "0.0.0.0"
      port = 8080
      use_unix_domain_socket = false

    [xrootd]
      security_protocol = "sss"
      sss_keytab_path = "/etc/cta/cta-taped.sss.keytab.grp"

    [experimental]
      telemetry_enabled = {{ $.Values.telemetry.enabled }}

    [drive]
      name = {{ .name | quote }}
      device = {{ .device | quote }}
      control_path = {{ .controlPath | quote }}
      logical_library_name = {{ .logicalLibraryName | quote }}

    [memory]
      buffer_count = {{ $.Values.memory.bufferCount }}
      buffer_size_bytes = {{ $.Values.memory.bufferSizeBytes }}

    [scheduling]
      mount_criteria_bytes = {{ int64 $.Values.scheduling.mountCriteriaBytes }}
      mount_criteria_files = {{ $.Values.scheduling.mountCriteriaFiles }}
      archive_fetch_bytes = {{ int64 $.Values.scheduling.archiveFetchBytes }}
      archive_fetch_files = {{ $.Values.scheduling.archiveFetchFiles }}
      archive_flush_bytes = {{ int64 $.Values.scheduling.archiveFlushBytes }}
      archive_flush_files = {{ $.Values.scheduling.archiveFlushFiles }}
      retrieve_fetch_bytes = {{ int64 $.Values.scheduling.retrieveFetchBytes }}
      retrieve_fetch_files = {{ $.Values.scheduling.retrieveFetchFiles }}

    [scheduling.archive_dismount_policy]
      underfill_watch_period_secs = {{ $.Values.scheduling.archiveDismountPolicy.underfillWatchPeriodSecs }}
      underfill_min_samples = {{ $.Values.scheduling.archiveDismountPolicy.underfillMinSamples }}
      underfill_start_threshold = {{ $.Values.scheduling.archiveDismountPolicy.underfillStartThreshold }}
      underfill_recovery_threshold = {{ $.Values.scheduling.archiveDismountPolicy.underfillRecoveryThreshold }}

    [encryption]
      enabled = {{ $.Values.encryption.enabled }}
      external_encryption_key_script = {{ $.Values.encryption.externalEncryptionKeyScript | quote }}

    [disk]
      io_threads = {{ $.Values.disk.ioThreads }}
      external_free_disk_space_script = {{ $.Values.disk.externalFreeDiskSpaceScript | quote }}

    [rao]
      enabled = {{ $.Values.rao.enabled }}
      lto_algorithm = {{ $.Values.rao.ltoAlgorithm | quote }}
      lto_algorithm_options = {{ $.Values.rao.ltoAlgorithmOptions | quote }}

    [timeout]
      tape_load_timeout_secs = {{ $.Values.timeout.tapeLoadTimeoutSecs }}
      drive_ready_timeout_secs = {{ $.Values.timeout.driveReadyTimeoutSecs }}
      schedule_timeout_secs = {{ $.Values.timeout.scheduleTimeoutSecs }}
      mount_timeout_secs = {{ $.Values.timeout.mountTimeoutSecs }}
      unmount_timeout_secs = {{ $.Values.timeout.unmountTimeoutSecs }}
      drain_to_disk_timeout_secs = {{ $.Values.timeout.drainToDiskTimeoutSecs }}
      shutdown_timeout_secs = {{ $.Values.timeout.shutdownTimeoutSecs }}
      no_block_move_timeout_secs = {{ $.Values.timeout.noBlockMoveTimeoutSecs }}
      idle_scheduling_interval_secs = {{ $.Values.timeout.idleSchedulingIntervalSecs }}
      get_next_mount_timeout_secs = {{ $.Values.timeout.getNextMountTimeoutSecs }}

    [rmc]
      host = {{ $.Values.rmc.host | quote }}
      port = {{ $.Values.rmc.port }}
      timeout_secs = {{ $.Values.rmc.timeoutSecs }}
      request_attempts = {{ $.Values.rmc.requestAttempts }}

---
{{- end }}
