# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

# Latest versions can be found in the respective repos if an update is desired
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        files: \.(c|h|cc|cpp|cxx|hpp|hh|json)$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.9
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.1.0
    hooks:
      - id: reuse-lint-file
  - repo: local
    hooks:
      - id: gitlab-ci
        name: GitLab CI check
        entry: >-
          bash -c 'python3 ci/checks/check_gitlab_ci_before_script_guard.py .gitlab-ci.yml .gitlab/ci/
          && python3 ci/checks/check_gitlab_ci_key_order.py .gitlab/
          && python3 ci/checks/check_gitlab_ci_single_stage.py .gitlab/ci/'
        language: python
        additional_dependencies: [PyYAML==6.0.2]
        files: '(^|/).*gitlab-ci\.yml$'
        pass_filenames: false
