#       @(#)$RCSfile: Makefile.ini,v $ $Revision: 1.4 $ $Date: 2008/11/26 14:39:13 $ CERN IT-PDP/DM Jean-Philippe Baud
#
#  Copyright (C) 1993-1999 by CERN/IT/PDP/DM
#  All rights reserved
#

# Makefile.ini	Startup Makefile

SHELL=/bin/sh

all: Makefiles
	$(MAKE) $@
install install.man clean clobber: Makefiles
	$(MAKE) $@
test: Makefiles
	(cd test; $(MAKE) all)

Makefiles:
	(cd imake; $(MAKE) $(MFLAGS) -f Makefile.ini BOOTSTRAPCFLAGS="$$BOOTSTRAPCFLAGS") ;\
	imake/imake -v -Iconfig -DCASTOR_NOSTK=$(CASTOR_NOSTK)
	$(MAKE) $@

deps:
	python config/showdeps.py
