#       @(#)$RCSfile: Makefile.ini,v $ $Revision: 1.1 $ $Date: 2004/06/17 08:10:52 $ CERN IT-PDP/DM Jean-Philippe Baud
#
#  Copyright (C) 1993-1999 by CERN/IT/PDP/DM
#  All rights reserved
#

# Makefile.ini	Startup Makefile

SHELL=/bin/sh

all: Makefiles
	$(MAKE) $@
install install.man clean clobber: Makefiles
	$(MAKE) $@
test: Makefiles
	(cd test; $(MAKE) all)

Makefiles:
	@. ./setosflags ;\
	(cd imake; $(MAKE) $(MFLAGS) -f Makefile.ini BOOTSTRAPCFLAGS="$$BOOTSTRAPCFLAGS") ;\
	imake/imake -v -Iconfig -DOSMajorVersion=$$OSMAJNO -DOSMinorVersion=$$OSMINNO
	$(MAKE) $@

define tmpfileHeader
#define YES 1
#define NO 0

#include "site.def"
#include "Project.tmpl"

#undef YES
#undef NO
endef

deps:
	python config/showdeps.py
