#       @(#)$RCSfile: Makefile.ini,v $ $Revision: 1.6 $ $Date: 2009/07/09 15:55:21 $ CERN IT-PDP/DM Jean-Philippe Baud
#
#  Copyright (C) 1993-1999 by CERN/IT/PDP/DM
#  All rights reserved
#
# Makefile.ini	Startup Makefile
#


CASTOR_ROOT=$(shell pwd)

.PHONY: Makefiles
Makefiles:
	@(cd imake; $(MAKE) $(MFLAGS) -f Makefile.ini BOOTSTRAPCFLAGS="$$BOOTSTRAPCFLAGS")
	@echo "Building Makefiles"
	@l=`echo $(CASTOR_ROOT) | awk '{ gsub(/\//,"_"); print}'`_;            \
	for i in `find $(CASTOR_ROOT) -name Imakefile -exec dirname {} \;`; do \
	    (echo " $$i";                                                       \
             cd $$i;                                                            \
             $(CASTOR_ROOT)/imake/imake -I$(CASTOR_ROOT)/config;                \
             j=`echo $$i | awk '{ gsub(/\//,"\\\/"); print}'`;                  \
             k=`echo $$i | awk '{ gsub(/\//,"_"); print}' | awk "{ gsub(/$$l/,\"\"); print}"`;                     \
             sed -e "s/__local_path__/$$j/g" -e "s/__root_prefix__/$$k/g" Makefile > Makefile.new;               \
             mv Makefile.new Makefile);                                         \
	done ;
