#!/bin/sh
#
#  Copyright (C) 1996-1999 by CERN/IT/PDP/DM
#  All rights reserved
#
#       @(#)$RCSfile: setosflags,v $ $Revision: 1.2 $ $Date: 1999/10/11 14:14:16 $ CERN IT-PDP/DM Jean-Philippe Baud

# set BOOTSTRAPCFLAGS, OSMAJNO and OSMINNO automatically
#
sysname=`uname -s`
sysrel=`uname -r`
case $sysname in
	AIX)	OSMAJNO=`uname -v`
		OSMINNO=$sysrel
		;;
	HP-UX)	OSMAJNO=`echo $sysrel | awk '{ print int(substr($1,3,2))}'`
		OSMINNO=`echo $sysrel | awk '{ print int(substr($1,6,2))}'`
		if [ $OSMAJNO -ge 10 ]
		then
			BOOTSTRAPCFLAGS="-DHPUX10"
		fi;;
	IRIX | IRIX64)	OSMAJNO=`echo $sysrel | awk '{ print substr($1,1,1)}'`
		OSMINNO=`echo $sysrel | awk '{ print substr($1,3)}'`
		if [ $OSMAJNO -ge 5 ]
		then
			BOOTSTRAPCFLAGS="-DIRIX5"
		fi;;
	SunOS)	OSMAJNO=`echo $sysrel | awk '{ print substr($1,1,1)}'`
		OSMINNO=`echo $sysrel | awk '{ print int(substr($1,3))}'`
		if [ $OSMAJNO -eq 5 ]
		then
			BOOTSTRAPCFLAGS="-DSOLARIS"
		fi;;
	OSF1)	OSMAJNO=`echo $sysrel | awk '{ print substr($1,2,1)}'`
		OSMINNO=`echo $sysrel | awk '{ print substr($1,4)}'`
		;;
	Linux)	OSMAJNO=`echo $sysrel | awk '{ print substr($1,1,1)}'`
		OSMINNO=`echo $sysrel | awk '{ print substr($1,3)}'`
		;;
	LynxOS)	OSMAJNO=`echo $sysrel | awk '{ print substr($1,1,1)}'`
		OSMINNO=`echo $sysrel | awk '{ print substr($1,3)}'`
		;;
esac
export BOOTSTRAPCFLAGS OSMAJNO OSMINNO
