.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GENCASTOR 1 "September 24, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gencastor \- produces castor source code from UML diagrams
.SH SYNOPSIS
.B gencastor
[ \-w  castor_workdir ]
[ \-h ]
.I xmiFile
.SH DESCRIPTION
gencastor is a tool to generate castor source code from UML diagrams.
These diagrams must be in .xmi format and edited by
.B umbrello
. gencastor will implement all classes of the UML diagram in C++. It will also
generate a C interface, a Streaming service and database conversion
services for the classes asking for it. Currently, only ORACLE is supported
as a DB and Odbc is produced but the code will not compile.
.PP
In order for a class to get a Streaming service, it shoudl inherit from the
interface castor::IStreamable. In order for a class to get a database conversion
service, it should inherit from the interface castor::IPersistent.
.SH OPTIONS
The following options are supported:
.TP
.B -h
Display the usage
.TP
.B -w castor_workdir
considers castor_workdir as the directory where the castor code resides
and where the code should be produced. If this option is not present,
the default value is the current directory
.SH SEE ALSO
.BR umbrello (1),
.br
.SH AUTHOR
This manual page was written by Sebastien Ponce <sebastien.ponce@cern.ch>,
for the Debian project (but may be used by others).
