# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

image:
  registry: gitlab-registry.cern.ch
  repository: cta/ctageneric/cta-taped
  tag: latest

logging:
  level: "INFO"

scheduler:
  tapeCacheMaxAgeSecs: 1
  retrieveQueueCacheMaxAgeSecs: 1
  numberOfConnections: 3

drive:
  readyTimeoutSecs: 120

mounts:
  minimumQueuedBytes: 2000000
  minimumQueuedFiles: 100
  schedulingTimeoutSecs: 300
  getNextMountTimeoutSecs: 900
  idleSchedulingIntervalSecs: 1 # Make tape servers more responsive, thus improving CI test speed
  mountTimeoutSecs: 600
  tapeLoadTimeoutSecs: 300
  unmountTimeoutSecs: 900
  rmcd:
    host: "cta-rmcd" # Override with localhost if using host networking
    port: 5014
    requestTimeoutSecs: 600
    requestAttempts: 10

transfers:
  bufferSizeBytes: 262144
  bufferCount: 200
  diskIoThreads: 4
  noBlockMoveTimeoutSecs: 1800
  archive:
    fetchMaxBytes: 100000000000
    fetchMaxFiles: 5000
    flushMaxBytes: 32000000000
    flushMaxFiles: 200
    underfill:
      watchPeriodSecs: 300
      minimumSamples: 3
      startThresholdPercent: 40
      recoveryThresholdPercent: 60
  retrieve:
    fetchMaxBytes: 100000000000
    fetchMaxFiles: 5000
    drainToDiskTimeoutSecs: 1800
    externalFreeDiskSpaceScript: "/usr/bin/cta-eosdf.sh"
    rao:
      enabled: true
      ltoAlgorithm: "sltf"
  encryption:
    enabled: false
    externalKeyScript: "/usr/local/bin/cta-get-encryption-key.sh"

telemetry:
  enabled: false

# OpenTelemetry is entirely configured through declarative configuration.
telemetryConfig: |
  file_format: "1.0-rc.1"
  disabled: true

# SSS keytab to communicate to the disk buffer
keytab:
  secretName: eos-keytab
  subPath: eos.keytab

# Script to execute in the main container before starting the taped services
preRun:
  enabled: false
  script: |
    #!/usr/bin/bash

# Script to execute in the main container after the taped process exited
postRun:
  enabled: true
  script: |
    #!/usr/bin/bash
    echo "Process crashed. Sleeping..."
    sleep infinity

# The following is an example format of drives
#
# drives:
#   - name: "VDSTK01"
#     device: "/dev/nst2"
#     logicalLibraryName: lib1
#     controlPath: smc0
#   - name: "VDSTK02"
#     device: "/dev/nst0"
#     logicalLibraryName: lib2
#     controlPath: smc1
drives: {}

securityContext:
  privileged: true # To get access to /dev/

pod:
  extraSpec:
    terminationGracePeriodSeconds: 1

extraEnv:

extraVolumes:
  volumes:
  volumeMounts:
