# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

image:
  registry: gitlab-registry.cern.ch
  repository: cta/ctageneric/cta-taped
  tag: latest

logging:
  level: "INFO"

scheduler:
  tapeCacheMaxAgeSecs: 1
  retrieveQueueCacheMaxAgeSecs: 1
  numberOfConnections: 3

memory:
  bufferSizeBytes: 262144
  bufferCount: 200

scheduling:
  mountCriteriaBytes: 2000000
  mountCriteriaFiles: 100
  archiveFetchBytes: 80000000000
  archiveFetchFiles: 4000
  archiveFlushBytes: 32000000000
  archiveFlushFiles: 200
  retrieveFetchBytes: 80000000000
  retrieveFetchFiles: 4000
  archiveDismountPolicy:
    underfillWatchPeriodSecs: 300
    underfillMinSamples: 3
    underfillStartThreshold: 40
    underfillRecoveryThreshold: 60

encryption:
  enabled: false
  externalEncryptionKeyScript: "/usr/local/bin/cta-get-encryption-key.sh"

disk:
  ioThreads: 4
  externalFreeDiskSpaceScript: "/usr/bin/cta-eosdf.sh"

rao:
  enabled: true
  ltoAlgorithm: "sltf"
  ltoAlgorithmOptions: "cost_heuristic_name:cta"

timeout:
  tapeLoadTimeoutSecs: 300
  driveReadyTimeoutSecs: 120
  scheduleTimeoutSecs: 300
  mountTimeoutSecs: 600
  unmountTimeoutSecs: 600
  drainToDiskTimeoutSecs: 1800
  shutdownTimeoutSecs: 900
  noBlockMoveTimeoutSecs: 1800
  idleSchedulingIntervalSecs: 1 # Make tape servers more responsive, thus improving CI test speed
  getNextMountTimeoutSecs: 900

rmc:
  host: "cta-rmcd" # Override with localhost if using host networking
  port: 5014
  timeoutSecs: 600
  requestAttempts: 10

telemetry:
  enabled: false

# OpenTelemetry is entirely configured through declarative configuration.
telemetryConfig: |
  file_format: "1.0-rc.1"
  disabled: true

# SSS keytab to communicate to the disk buffer
keytab:
  secretName: eos-keytab
  subPath: eos.keytab

# Script to execute in the main container before starting the taped services
preRun:
  enabled: false
  script: |
    #!/usr/bin/bash

# Script to execute in the main container after the taped process exited
postRun:
  enabled: true
  script: |
    #!/usr/bin/bash
    echo "Process crashed. Sleeping..."
    sleep infinity

# The following is an example format of drives
#
# drives:
#   - name: "VDSTK01"
#     device: "/dev/nst2"
#     logicalLibraryName: lib1
#     controlPath: smc0
#   - name: "VDSTK02"
#     device: "/dev/nst0"
#     logicalLibraryName: lib2
#     controlPath: smc1
drives: {}

securityContext:
  privileged: true # To get access to /dev/

pod:
  extraSpec:
    terminationGracePeriodSeconds: 1

extraEnv:

extraVolumes:
  volumes:
  volumeMounts:
