/**** This file has been autogenerated by gencastor from Umbrello UML model ***/

#ifndef CASTOR_STAGER_DISKCOPYSTATUSCODES_H
#define CASTOR_STAGER_DISKCOPYSTATUSCODES_H

//------------------------------------------------------------------------------
// This defines a C interface to the following enum
// enum DiskCopyStatusCodes
// Possible status codes for a DiskCopy
//------------------------------------------------------------------------------

#define Cstager_DiskCopyStatusCodes_t DiskCopyStatusCodes

#include "DiskCopyStatusCodes.hpp"

#endif // CASTOR_STAGER_DISKCOPYSTATUSCODES_H
