/**** This file has been autogenerated by gencastor from Umbrello UML model ***/

// Include Files
#include "castor/stager/DiskFile.hpp"

//------------------------------------------------------------------------------
// Constructor
//------------------------------------------------------------------------------
castor::stager::DiskFile::DiskFile() throw() {
};

//------------------------------------------------------------------------------
// Destructor
//------------------------------------------------------------------------------
castor::stager::DiskFile::~DiskFile() throw() {
};

