/**** This file has been autogenerated by gencastor from Umbrello UML model ***/

// Include Files
#include "castor/IClient.hpp"
#include "castor/IObject.hpp"
#include "castor/stager/FilesDeletionFailed.hpp"
#include "castor/stager/GCFile.hpp"
#include "castor/stager/GCFileList.hpp"
#include "castor/stager/Request.hpp"
#include "castor/stager/SvcClass.hpp"
#include "osdep.h"
#include <vector>

extern "C" {

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_create
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_create(castor::stager::FilesDeletionFailed** obj) {
    *obj = new castor::stager::FilesDeletionFailed();
    return 0;
  }
  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_delete
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_delete(castor::stager::FilesDeletionFailed* obj) {
    delete obj;
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_getGCFileList
  //----------------------------------------------------------------------------
  castor::stager::GCFileList* Cstager_FilesDeletionFailed_getGCFileList(castor::stager::FilesDeletionFailed* obj) {
    return obj;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_fromGCFileList
  //----------------------------------------------------------------------------
  castor::stager::FilesDeletionFailed* Cstager_FilesDeletionFailed_fromGCFileList(castor::stager::GCFileList* obj) {
    return dynamic_cast<castor::stager::FilesDeletionFailed*>(obj);
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_getRequest
  //----------------------------------------------------------------------------
  castor::stager::Request* Cstager_FilesDeletionFailed_getRequest(castor::stager::FilesDeletionFailed* obj) {
    return obj;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_fromRequest
  //----------------------------------------------------------------------------
  castor::stager::FilesDeletionFailed* Cstager_FilesDeletionFailed_fromRequest(castor::stager::Request* obj) {
    return dynamic_cast<castor::stager::FilesDeletionFailed*>(obj);
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_getIObject
  //----------------------------------------------------------------------------
  castor::IObject* Cstager_FilesDeletionFailed_getIObject(castor::stager::FilesDeletionFailed* obj) {
    return obj;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_fromIObject
  //----------------------------------------------------------------------------
  castor::stager::FilesDeletionFailed* Cstager_FilesDeletionFailed_fromIObject(castor::IObject* obj) {
    return dynamic_cast<castor::stager::FilesDeletionFailed*>(obj);
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_print
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_print(castor::stager::FilesDeletionFailed* instance) {
    instance->print();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_TYPE
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_TYPE(int* ret) {
    *ret = castor::stager::FilesDeletionFailed::TYPE();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_addFiles
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_addFiles(castor::stager::FilesDeletionFailed* instance, castor::stager::GCFile* obj) {
    instance->addFiles(obj);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_removeFiles
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_removeFiles(castor::stager::FilesDeletionFailed* instance, castor::stager::GCFile* obj) {
    instance->removeFiles(obj);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_files
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_files(castor::stager::FilesDeletionFailed* instance, castor::stager::GCFile*** var, int* len) {
    std::vector<castor::stager::GCFile*>& result = instance->files();
    *len = result.size();
    *var = (castor::stager::GCFile**) malloc((*len) * sizeof(castor::stager::GCFile*));
    for (int i = 0; i < *len; i++) {
      (*var)[i] = result[i];
    }
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_flags
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_flags(castor::stager::FilesDeletionFailed* instance, u_signed64* var) {
    *var = instance->flags();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setFlags
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setFlags(castor::stager::FilesDeletionFailed* instance, u_signed64 new_var) {
    instance->setFlags(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_userName
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_userName(castor::stager::FilesDeletionFailed* instance, const char** var) {
    *var = instance->userName().c_str();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setUserName
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setUserName(castor::stager::FilesDeletionFailed* instance, const char* new_var) {
    std::string snew_var(new_var, strlen(new_var));
    instance->setUserName(snew_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_euid
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_euid(castor::stager::FilesDeletionFailed* instance, unsigned long* var) {
    *var = instance->euid();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setEuid
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setEuid(castor::stager::FilesDeletionFailed* instance, unsigned long new_var) {
    instance->setEuid(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_egid
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_egid(castor::stager::FilesDeletionFailed* instance, unsigned long* var) {
    *var = instance->egid();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setEgid
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setEgid(castor::stager::FilesDeletionFailed* instance, unsigned long new_var) {
    instance->setEgid(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_mask
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_mask(castor::stager::FilesDeletionFailed* instance, unsigned long* var) {
    *var = instance->mask();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setMask
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setMask(castor::stager::FilesDeletionFailed* instance, unsigned long new_var) {
    instance->setMask(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_pid
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_pid(castor::stager::FilesDeletionFailed* instance, unsigned long* var) {
    *var = instance->pid();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setPid
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setPid(castor::stager::FilesDeletionFailed* instance, unsigned long new_var) {
    instance->setPid(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_machine
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_machine(castor::stager::FilesDeletionFailed* instance, const char** var) {
    *var = instance->machine().c_str();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setMachine
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setMachine(castor::stager::FilesDeletionFailed* instance, const char* new_var) {
    std::string snew_var(new_var, strlen(new_var));
    instance->setMachine(snew_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_svcClassName
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_svcClassName(castor::stager::FilesDeletionFailed* instance, const char** var) {
    *var = instance->svcClassName().c_str();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setSvcClassName
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setSvcClassName(castor::stager::FilesDeletionFailed* instance, const char* new_var) {
    std::string snew_var(new_var, strlen(new_var));
    instance->setSvcClassName(snew_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_userTag
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_userTag(castor::stager::FilesDeletionFailed* instance, const char** var) {
    *var = instance->userTag().c_str();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setUserTag
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setUserTag(castor::stager::FilesDeletionFailed* instance, const char* new_var) {
    std::string snew_var(new_var, strlen(new_var));
    instance->setUserTag(snew_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_reqId
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_reqId(castor::stager::FilesDeletionFailed* instance, const char** var) {
    *var = instance->reqId().c_str();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setReqId
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setReqId(castor::stager::FilesDeletionFailed* instance, const char* new_var) {
    std::string snew_var(new_var, strlen(new_var));
    instance->setReqId(snew_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_creationTime
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_creationTime(castor::stager::FilesDeletionFailed* instance, u_signed64* var) {
    *var = instance->creationTime();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setCreationTime
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setCreationTime(castor::stager::FilesDeletionFailed* instance, u_signed64 new_var) {
    instance->setCreationTime(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_lastModificationTime
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_lastModificationTime(castor::stager::FilesDeletionFailed* instance, u_signed64* var) {
    *var = instance->lastModificationTime();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setLastModificationTime
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setLastModificationTime(castor::stager::FilesDeletionFailed* instance, u_signed64 new_var) {
    instance->setLastModificationTime(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_svcClass
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_svcClass(castor::stager::FilesDeletionFailed* instance, castor::stager::SvcClass** var) {
    *var = instance->svcClass();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setSvcClass
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setSvcClass(castor::stager::FilesDeletionFailed* instance, castor::stager::SvcClass* new_var) {
    instance->setSvcClass(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_client
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_client(castor::stager::FilesDeletionFailed* instance, castor::IClient** var) {
    *var = instance->client();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setClient
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setClient(castor::stager::FilesDeletionFailed* instance, castor::IClient* new_var) {
    instance->setClient(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_type
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_type(castor::stager::FilesDeletionFailed* instance,
                                       int* ret) {
    *ret = instance->type();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_clone
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_clone(castor::stager::FilesDeletionFailed* instance,
                                        castor::IObject** ret) {
    *ret = instance->clone();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_id
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_id(castor::stager::FilesDeletionFailed* instance, u_signed64* var) {
    *var = instance->id();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cstager_FilesDeletionFailed_setId
  //----------------------------------------------------------------------------
  int Cstager_FilesDeletionFailed_setId(castor::stager::FilesDeletionFailed* instance, u_signed64 new_var) {
    instance->setId(new_var);
    return 0;
  }

} // End of extern "C"
