/**** This file has been autogenerated by gencastor from Umbrello UML model ***/

#ifndef CASTOR_STAGER_SUBREQUESTSTATUSCODES_HPP
#define CASTOR_STAGER_SUBREQUESTSTATUSCODES_HPP

#ifdef __cplusplus
namespace castor {

  namespace stager {

#endif
    /**
     * enum SubRequestStatusCodes
     * Possible status codes for a SubRequest
     */
    enum SubRequestStatusCodes {
      SUBREQUEST_START = 0,
      SUBREQUEST_RESTART = 1,
      SUBREQUEST_RETRY = 2,
      SUBREQUEST_WAITSCHED = 3,
      SUBREQUEST_WAITTAPERECALL = 4,
      SUBREQUEST_WAITSUBREQ = 5,
      SUBREQUEST_READY = 6,
      SUBREQUEST_FAILED = 7,
      SUBREQUEST_FINISHED = 8,
      SUBREQUEST_FAILED_FINISHED = 9,
      SUBREQUEST_FAILED_ANSWERING = 10,
      SUBREQUEST_ARCHIVED = 11,
      SUBREQUEST_REPACK = 12
    }; // end of enum SubRequestStatusCodes

    /**
     * Names of the differents representations, used to display
     * correctly the SubRequestStatusCodes enum
     */
    extern const char* SubRequestStatusCodesStrings[13];

#ifdef __cplusplus
  }; // end of namespace stager

}; // end of namespace castor

#endif
#endif // CASTOR_STAGER_SUBREQUESTSTATUSCODES_HPP
