#!/bin/sh

# Ensure Docker is running

HAS_DOCKER=$(ps ax|grep dockerd-current|grep -v grep|wc -l)
if [ $HAS_DOCKER -eq 0 ]
then
  echo -n Starting Docker...
  sudo systemctl start docker
  echo done.
fi

sudo docker build . -f ./Dockerfile -t buildxroot

id=$(sudo docker create buildxroot bash)

echo $id
