apiVersion: v1
kind: Service
metadata:
  name: auth-keycloak
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: auth-keycloak
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8080
