#!/bin/bash
#
#       /etc/rc.d/init.d/x2castormond
#
# Starts xrootd 
#
# chkconfig: 345 95 5
# description: Starts monitor script to monitor xrootd-castor2 
# processname: x2castormond

# Source function library.
XRDLOCATION="/opt/xrootd"
XRDCOREDIR="/var/spool/xroot"
XRDUSER=root
XRDLOGDIR="/var/log/xroot"

. /etc/init.d/functions


XRDPORT=$2



if test -n ${XRDPORT}; then
    cp -f ${XRDLOCATION}/bin/x2castormond ${XRDLOCATION}/bin/x2castormond${XRDPORT} 2> /dev/null
fi

if test ! -x ${XRDLOCATION}/bin/x2castormond ; then
  echo Error: ${XRDLOCATION}/bin/x2castormond does not exist
  exit 0
fi


if test ! -e /etc/sysconfig/x2castormond$XRDPORT ; then 
  echo Warning: /etc/sysconfig/x2castormond${XRDPORT} is not existing
else 
    . /etc/sysconfig/x2castormond${XRDPORT}
fi

XRDROLE="manager"

if test -z $2; then
    if test -e "/etc/sysconfig/xrd-service-ports"; then
	for name in `cat /etc/sysconfig/xrd-service-ports`; do 
	    /etc/init.d/x2castormond $1 $name
	done
	exit 0;
    fi
fi

mkdir -p $XRDCOREDIR/$XRDROLE$XRDPORT/
mkdir -p $XRDLOGDIR/$XRDROLE$XRDPORT/

RETVAL=0

#
#       See how we were called.
#

prog="x2castormond${XRDPORT}"

X2CASTORMONDSTARTUPFILE="/opt/xrootd/bin/x2castormonitoring.pl" 
start() {
        # Check if xrootd is already running
        if [ ! `pgrep -f -u ${XRDUSER} ${XRDLOCATION}/bin/x2castormond${XRDPORT}`  ]; then
            echo -n "Starting $prog: "
            daemon --user ${XRDUSER} "test -e /etc/sysconfig/x2castormond$XRDPORT && source /etc/sysconfig/x2castormond$XRDPORT; cd ${XRDCOREDIR}/${XRDROLE}${XRDPORT}; ulimit -c unlimited;${XRDLOCATION}/bin/x2castormond${XRDPORT} ${X2CASTORMONDSTARTUPFILE} ${XRDLOGDIR}/${XRDROLE}${XRDPORT}/proc/ ${XRDLOGDIR}/${XRDROLE}${XRDPORT}/x2castormondlog >& /dev/null"
            RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/x2castormond${XRDPORT}
            echo
	else 
            echo x2castormond${XRDPORT} already running.  
            echo Stop it first with 'service x2castormond stop ${XRDPORT}'
            echo and try again or use directly 'service x2castormond restart ${XRDPORT}'.
            RETVAL=1
        fi
        return $RETVAL
}

stop() {
        echo -n "Stopping $prog: "
        killproc ${XRDLOCATION}/bin/x2castormond${XRDPORT}
        RETVAL=$?
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/x2castormond${XRDPORT}
        echo
        return $RETVAL
}


restart() {
        stop
        start
}       

reload() {
        restart
}       

status_at() {
        status ${XRDLOCATION}/bin/x2castormond${XRDPORT}
}


case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
reload|restart)
        restart
        ;;
condrestart)
        if [ -f /var/lock/subsys/x2castormond${XRDPORT} ]; then
            restart
        fi
        ;;
status)
        status_at
        ;;
*)
        echo $"Usage: $0 {start|stop|restart|condrestart|status}"
        exit 1
esac

exit $?
exit $RETVAL
