.\" Copyright (C) 2003  CERN
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.TH TAPEBRIDGED 8 "$Date: 2009/08/18 09:42:55 $" CASTOR "CASTOR"
.SH NAME
tapebridged \- Tape bridge daemon
.SH SYNOPSIS
.BI "tapebridged [OPTIONS]"

.SH DESCRIPTION
\fBtapebridged\fP is the daemon responsible for acting as a protocol bridge
between the tape gateway-daemons and the legacy rtcpd daemon.
.P
When \fBtapebridged\fP is executed it immediately forks with the parent
terminating and the child running in the background.  If required the
\fB\-f, \-\-foreground\fP option can be used to stop \fBtapebridged\fP from
forking and keep the parent process in the foreground.

.SH OPTIONS
.TP
\fB\-f, \-\-foreground
Remain in the foreground.
.TP
\fB\-h, \-\-help
Prints the usage message


.SH CASTOR CONFIGURATION PARAMETERS
The tapebridge daemon reads and uses the following CASTOR configuration
parameters which are specified using environment variables or within the CASTOR
configuration file (the default location is /etc/castor/castor.conf).
.TP
\fBTAPEBRIDGE VDQMPORT
The port on which the tapebridge will listen for RTCOPY jobs from the VDQM.
The default is 5070.  This configuration parameter should \fBNOT\fP normally be
set and the default should be used.
.TP
\fBTAPEBRIDGE RTCPDLOWPORT
The inclusive low port of the tapebridge's RTCPD callback port number range.
.TP
\fBTAPEBRIDGE RTCPDHIGHPORT
The inclusive high port of the tapebridge's RTCPD callback port number range.
.TP
\fBTAPEBRIDGE BULKREQUESTMIGRATIONMAXBYTES
When the tapebridged daemon requests the tapegatewayd daemon for a set of
files to migrate to tape, this parameter defines the maximum number of bytes
the set of files should represent.
The value of this parameter is read and taken into account by the tapebridged
daemon when the daemon is started.  The tapebridged daemon must be restarted
in order for any change in the value of this parameter to be taken into
account.
.TP
\fBTAPEBRIDGE BULKREQUESTMIGRATIONMAXFILES
When the tapebridged daemon requests the tapegatewayd daemon for a set of
files to migrate to tape, this parameter defines the maximum number of files
the set may contain.
The value of this parameter is read and taken into account by the tapebridged
daemon when the daemon is started.  The tapebridged daemon must be restarted
in order for any change in the value of this parameter to be taken into
account.
.TP
\fBTAPEBRIDGE BULKREQUESTRECALLMAXBYTES
When the tapebridged daemon requests the tapegatewayd daemon for a set of
files to recall from tape, this parameter defines the maximum number of bytes
the set of files should represent.
The value of this parameter is read and taken into account by the tapebridged
daemon when the daemon is started.  The tapebridged daemon must be restarted
in order for any change in the value of this parameter to be taken into
account.
.TP
\fBTAPEBRIDGE BULKREQUESTRECALLMAXFILES
When the tapebridged daemon requests the tapegatewayd daemon for a set of
files to recall from tape, this parameter defines the maximum number of files
the set may contain.
The value of this parameter is read and taken into account by the tapebridged
daemon when the daemon is started.  The tapebridged daemon must be restarted
in order for any change in the value of this parameter to be taken into
account.
.TP
\fBTAPEBRIDGE TAPEFLUSHMODE
The value of this parameter defines the mode of tape-flush behaviour to be
used when tapegatewayd and writetp are clients of rtcpd (via tapebridged).
This option is explicitly ignored when rtcpclientd and tpwrite are the
clients of rtpcd.

The possible case-sensitive values for this option are:

\fBN_FLUSHES_PER_FILE\fP
.br
If the AUL tape format is used then data will be flushed to tape
three times per file, once after the header of the file, once again after the
end of the data of the file and finally once more after the trailer of the
file.  If the NL format is used then data will be flushed to tape after the
end of the data of each file.

\fBONE_FLUSH_PER_N_FILES\fP
.br
If the AUL tape format is used then data will be flushed to tape
after the AUL trailer of the Nth file, where the Nth file is the one that
reaches either the maximum number of bytes allowed before a flush or the
maximum number of files before a flush.  If the NL format is used then data
will be flushed to tape after the end of the data of the Nth file.

The appropriate st driver must be loaded in order to successfully use the
\fBONE_FLUSH_PER_N_FILES\fP tape-flush mode.

The value of this parameter is read and taken into account by the tapebridged
daemon when the daemon is started.  The tapebridged daemon must be restarted
in order for any change in the value of this parameter to be taken into
account.
.TP
\fBTAPEBRIDGE MAXBYTESBEFOREFLUSH
The value of this parameter defines the maximum number of bytes to be written
to tape before a flush to tape (synchronised tape-mark).  Please note that a
flush occurs on a file boundary therefore more bytes will normally be written
to tape before the actual flush occurs.

The value of this parameter is only used when \fBTAPEBRIDGE/TAPEFLUSHMODE\fP is
set to \fBONE_FLUSH_PER_N_FILES\fP.

The value of this parameter is read and taken into account by the tapebridged
daemon when the daemon is started.  The tapebridged daemon must be restarted
in order for any change in the value of this parameter to be taken into
account.
.TP
\fBTAPEBRIDGE MAXFILESBEFOREFLUSH
The value of this parameter defines the maximum number of files to be written
to tape before a flush to tape (synchronised or non-immediate tape-mark).

The value of this parameter is only used when \fBTAPEBRIDGE/TAPEFLUSHMODE\fP is
set to \fBONE_FLUSH_PER_N_FILES\fP.

The value of this parameter is read and taken into account by the tapebridged
daemon when the daemon is started.  The tapebridged daemon must be restarted
in order for any change in the value of this parameter to be taken into
account.
.TP
\fBtapebridged LOGSTANDARD XXXX
Sets the location of the \fBtapebridged\fP log file to be \fBXXXX\fP.

.SH FILES
.TP
.B /etc/castor/castor.conf
Default location of the CASTOR configuration file.
.TP
.B /var/log/castor/tapebridged.log
Default location of the tape tapebridge log file.

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
