# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

# Try CERN's proxy first when downloading external images. If the image is not
# available there, download it directly from its original registry.

# Docker treats official images such as docker.io/almalinux as if they were
# stored under docker.io/library. This rule removes "library" from the proxy URL.
[[registry]]
prefix = "docker.io/library"
location = "docker.io/library"

# A mirror block applies to the registry block immediately above it
[[registry.mirror]]
location = "registry.cern.ch/docker.io"

# Proxy images hosted on Quay
[[registry]]
prefix = "quay.io"
location = "quay.io"

[[registry.mirror]]
location = "registry.cern.ch/quay.io"

# Proxy images hosted on GitHub Container Registry
[[registry]]
prefix = "ghcr.io"
location = "ghcr.io"

[[registry.mirror]]
location = "registry.cern.ch/ghcr.io"

# Proxy all other Docker Hub images
[[registry]]
prefix = "docker.io"
location = "docker.io"

[[registry.mirror]]
location = "registry.cern.ch/docker.io"
