# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

image:
  registry: gitlab-registry.cern.ch
  repository: cta/ctageneric/cta-tools
  tag: latest

replicas: 1

conf:
  cta:
    endpoint: cta-frontend-admin:10955

users:
  - user1
  - eosadmin1
  - poweruser1
  - ctaadmin2

pod:
  extraSpec:
    terminationGracePeriodSeconds: 1

extraVolumes:
  volumeMounts:
  volumes:
