# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

# This file should contain a single line with the connection string for the CTA Scheduler backend.
# Blank lines and comments are ignored. A comment line starts with a hash '#' character. Comments at
# the end of a line are not supported. Leading whitespace is permitted.
#
# For a RADOS objectstore backend, the format is:
#
#    rados://user@pool:namespace
#
# The namespace is optional:
#
#    rados://user@pool
#
# For a PostgreSQL scheduler backend, the format is:
#
#    postgresql:postgresql://username:password@hostname/database
#
# For a VFS backend, the format is:
#
#    file:///path/to/objectstore

rados://user@pool:namespace
