# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

# This file should contain a single line with the connection string for the CTA Scheduler backend.
# Blank lines and comments are ignored. A comment line starts with a hash '#' character. Comments at
# the end of a line are not supported. Leading whitespace is permitted.
#
# The format of the PostgreSQL connection string is:
#
#    postgresql:postgresql://username:password@hostname/database

postgresql:postgresql://username:password@hostname/database
