/* This file was generated by ./DlfMessagesCodeGenerator on Wed Feb 24 10:30:09 CET 2010
 */

/******************************************************************************
 *           castor/tape/tapeserver/TapeServerDlfMessageStrings.cpp
 *
 * This file is part of the Castor project.
 * See http://castor.web.cern.ch/castor
 *
 * Copyright (C) 2003  CERN
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 *
 *
 * @author Steven Murray Steven.Murray@cern.ch
 *****************************************************************************/

#include "castor/tape/tapeserver/DlfMessageConstants.hpp"
#include "castor/tape/tapeserver/TapeServerDaemon.hpp"

castor::dlf::Message castor::tape::tapeserver::TapeServerDaemon::s_dlfMessages[] = {
{TAPESERVER_NULL, " - "},
{TAPESERVER_STARTED, "tapeserverd started"},
{TAPESERVER_FAILED_TO_START, "tapeserverd failed to start"},
{TAPESERVER_RECEIVED_VDQM_CONNECTION, "Received a connection from VDQM"},
{TAPESERVER_HANDLE_VDQM_REQUEST_EXCEPT, "Exception raised when handling a request from the VDQM"},
{TAPESERVER_FAILED_TO_READ_MESSAGE_HEADER, "Failed to read message header"},
{TAPESERVER_UNKNOWN_MAGIC, "Unknown magic number"},
{TAPESERVER_UNKNOWN_REQUEST_TYPE, "Unknown request type"},
{TAPESERVER_FAILED_TO_READ_MESSAGE_BODY, "Failed to read message body"},
{TAPESERVER_RECEIVE_RTCOPY_JOB, "Receiving remote-copy job"},
{TAPESERVER_RECEIVED_RTCOPY_JOB, "Received remote-copy job"},
{TAPESERVER_SUBMITTING_RTCOPY_JOB_TO_RTCPD, "Submitting remote-copy job to RTCPD"},
{TAPESERVER_FAILED_TO_SUBMIT_JOB_TO_RTCPD, "Failed to submit remote-copy job to RTCPD"},
{TAPESERVER_FAILED_TO_MARSHALL_RTCP_ACKN, "Failed to marshall RTCP acknowledge message"},
{TAPESERVER_FAILED_TO_SEND_RTCOPY_JOB_REPLY_TO_VDQM, "Failed to send remote-copy job reply to VDQM"},
{TAPESERVER_FAILED_TO_PROCESS_RCOPY_JOB_SUBMISSION, "Failed to process remote-copy job submission message"},
{TAPESERVER_RTCPD_HANDLER_SOCKET_IS_NULL, "The RtcpdHandlerThread has been passed a NULL socket pointer"},
{TAPESERVER_INITIAL_RTCPD_CALLBACK, "Received initial callback connection from RTCPD"},
{TAPESERVER_RTCPD_CALLBACK, "Received a callback connection from RTCPD"},
{TAPESERVER_GOT_VOLREQID, "Got volume request ID from RTCPD"},
{TAPESERVER_FAILED_TO_GET_VOLREQID, "Failed to get volume request ID from RTCPD"},
{TAPESERVER_FAILED_TO_MARSHALL_RTCOPY_JOB_REPLY_MESSAGE, "Failed to marshall remote-copy job reply message"},
{TAPESERVER_SIGNALLED_NO_MORE_REQUESTS, "Signalled no more requests to RTCPD"},
{TAPESERVER_FAILED_TO_COORDINATE_REMOTE_COPY, "Failed to coordinate remote-copy"},
{TAPESERVER_TRANSFER_FAILED, "Transfer failed"},
{TAPESERVER_GAVE_REQUEST_FOR_MORE_WORK, "Gave request for more work to RTCPD"},
{TAPESERVER_DATA_ON_INITIAL_RTCPD_CONNECTION, "Data has arrived on the initial RTCPD connection"},
{TAPESERVER_RECEIVED_RTCP_ENDOF_REQ, "Received RTCP_ENDOF_REQ"},
{TAPESERVER_TAPE_POSITIONED, "Tape positioned"},
{TAPESERVER_FILE_TRANSFERED, "File transfered"},
{TAPESERVER_GET_REQUEST_INFO_FROM_RTCPD, "Getting request information from RTCPD"},
{TAPESERVER_GOT_REQUEST_INFO_FROM_RTCPD, "Got request information from RTCPD"},
{TAPESERVER_TOLD_CLIENT_TO_START_TRANSFER, "Told client to start the transfer protocol"},
{TAPESERVER_GET_VOLUME_FROM_CLIENT, "Getting volume from client"},
{TAPESERVER_GOT_VOLUME_FROM_CLIENT, "Got volume from client"},
{TAPESERVER_GOT_NO_MORE_FILES_FROM_CLIENT, "Got no more files from client"},
{TAPESERVER_GET_FILE_TO_MIGRATE_FROM_CLIENT, "Getting file to migrate from client"},
{TAPESERVER_GOT_FILE_TO_MIGRATE_FROM_CLIENT, "Got file to migrate from client"},
{TAPESERVER_GET_FILE_TO_RECALL_FROM_CLIENT, "Getting file to recall from client"},
{TAPESERVER_GOT_FILE_TO_RECALL_FROM_CLIENT, "Got file to recall from client"},
{TAPESERVER_GIVE_VOLUME_TO_RTCPD, "Giving volume to RTCPD"},
{TAPESERVER_GAVE_VOLUME_TO_RTCPD, "Gave volume to RTCPD"},
{TAPESERVER_ASK_RTCPD_TO_RQST_MORE_RECALL_WORK, "Asking RTCPD to request more recall work"},
{TAPESERVER_ASKED_RTCPD_TO_RQST_MORE_RECALL_WORK, "Asked RTCPD to request more recall work"},
{TAPESERVER_ASK_RTCPD_TO_RQST_MORE_MIGRATE_WORK, "Asking RTCPD to request more migrate work"},
{TAPESERVER_ASKED_RTCPD_TO_RQST_MORE_MIGRATE_WORK, "Asked RTCPD to request more migrate work"},
{TAPESERVER_TELL_RTCPD_DUMP_TAPE, "Telling RTCPD to dump tape"},
{TAPESERVER_TOLD_RTCPD_DUMP_TAPE, "Told RTCPD to dump tape"},
{TAPESERVER_TELL_RTCPD_END_OF_FILE_LIST, "Telling RTCPD end of file list"},
{TAPESERVER_TOLD_RTCPD_END_OF_FILE_LIST, "Told RTCPD end of file list"},
{TAPESERVER_TELL_RTCPD_TO_ABORT, "Telling RTCPD to abort"},
{TAPESERVER_TOLD_RTCPD_TO_ABORT, "Told RTCPD to abort"},
{TAPESERVER_GIVE_RECALL_FILE_TO_RTCPD, "Giving recall file to RTCPD"},
{TAPESERVER_GAVE_RECALL_FILE_TO_RTCPD, "Gave recall file to RTCPD"},
{TAPESERVER_GIVE_MIGRATE_FILE_TO_RTCPD, "Giving migrate file to RTCPD"},
{TAPESERVER_GAVE_MIGRATE_FILE_TO_RTCPD, "Gave migrate file to RTCPD"},
{TAPESERVER_RECEIVE_MSGBODY_FROM_RTCPD, "Receiving message body from RTCPD"},
{TAPESERVER_RECEIVED_MSGBODY_FROM_RTCPD, "Received message body from RTCPD"},
{TAPESERVER_RECEIVE_FILERQSTBODY_FROM_RTCPD, "Receiving FileRqstBody from RTCPD"},
{TAPESERVER_RECEIVED_FILERQSTBODY_FROM_RTCPD, "Received FileRqstBody from RTCPD"},
{TAPESERVER_RECEIVE_FILERQSTERRBODY_FROM_RTCPD, "Receiving FileRqstErrBody from RTCPD"},
{TAPESERVER_RECEIVED_FILERQSTERRBODY_FROM_RTCPD, "Received FileRqstErrBody from RTCPD"},
{TAPESERVER_PROCESSING_TAPE_DISK_RQST, "Processing a tape/disk IO request from RTCPD"},
{TAPESERVER_PING_RTCPD, "Pinging RTCPD"},
{TAPESERVER_PINGED_RTCPD, "Pinged RTCPD"},
{TAPESERVER_SEND_ACK_TO_RTCPD, "Sending acknowledge to RTCPD"},
{TAPESERVER_SENT_ACK_TO_RTCPD, "Sent acknowledge to RTCPD"},
{TAPESERVER_SEND_HEADER_TO_RTCPD, "Sending message header to RTCPD"},
{TAPESERVER_SENT_HEADER_TO_RTCPD, "Sent message header to RTCPD"},
{TAPESERVER_RECEIVE_TAPERQSTBODY, "Receiving tape request message body"},
{TAPESERVER_RECEIVED_TAPERQSTBODY, "Received tape request message body"},
{TAPESERVER_RECEIVE_GIVEOUTPBODY, "Receiving GIVE_OUTP message body"},
{TAPESERVER_RECEIVED_GIVEOUTPBODY, "Received GIVE_OUTP message body"},
{TAPESERVER_RECEIVE_TAPERQSTERRBODY, "Receiving tape request message body with error appendix"},
{TAPESERVER_RECEIVED_TAPERQSTERRBODY, "Received tape request message body with error appendix"},
{TAPESERVER_SEND_DELAYED_REQUEST_MORE_WORK_ACK_TO_RTCPD, "Sending delayed acknowledge of request for more work to RTCPD"},
{TAPESERVER_SENT_DELAYED_REQUEST_MORE_WORK_ACK_TO_RTCPD, "Sent delayed acknowledge of request for more work to RTCPD"},
{TAPESERVER_CREATED_RTCPD_CALLBACK_PORT, "Created TCP/IP port for RTCPD callbacks"},
{TAPESERVER_CONNECTION_CLOSED_BY_RTCPD, "Connection closed by RTCPD"},
{TAPESERVER_CLOSED_CONNECTION, "Connection closed by tapeserver"},
{TAPESERVER_NOTIFY_CLIENT_FILE_MIGRATED, "Notifying client file migrated"},
{TAPESERVER_NOTIFIED_CLIENT_FILE_MIGRATED, "Notified client file migrated"},
{TAPESERVER_NOTIFY_CLIENT_FILE_RECALLED, "Notifying client file recalled"},
{TAPESERVER_NOTIFIED_CLIENT_FILE_RECALLED, "Notified client file recalled"},
{TAPESERVER_NOTIFY_CLIENT_END_OF_SESSION, "Notifying client end of session"},
{TAPESERVER_NOTIFIED_CLIENT_END_OF_SESSION, "Notified client end of session"},
{TAPESERVER_GET_DUMP_PARAMETERS_FROM_CLIENT, "Getting dump parameters from client"},
{TAPESERVER_GOT_DUMP_PARAMETERS_FROM_CLIENT, "Got dump parameters from client"},
{TAPESERVER_NOTIFY_CLIENT_DUMP_MESSAGE, "Notifying client dump message"},
{TAPESERVER_NOTIFIED_CLIENT_DUMP_MESSAGE, "Notified client dump message"},
{TAPESERVER_FAILED_TO_NOTIFY_CLIENT_END_OF_SESSION, "Failed to notify client end of session"},
{TAPESERVER_NOTIFY_CLIENT_END_OF_FAILED_SESSION, "Notifying client end of failed session"},
{TAPESERVER_NOTIFIED_CLIENT_END_OF_FAILED_SESSION, "Notified client end of failed session"},
{TAPESERVER_FAILED_TO_NOTIFY_CLIENT_END_OF_FAILED_SESSION, "Failed to notify client end of failed session"},
{TAPESERVER_SELECT_INTR, "Select interrupted"},
{TAPESERVER_ENTERING_BRIDGE_MODE, "Entering bridge mode"},
{TAPESERVER_PING_CLIENT, "Pinging client"},
{TAPESERVER_PINGED_CLIENT, "Pinged client"},
{TAPESERVER_CLOSED_INITIAL_CALLBACK_CONNECTION, "Closed initial callback connection"},
{TAPESERVER_RECEIVED_TAPE_INFO_FROM_VMGR, "Received tape information from VMGR"},
{TAPESERVER_SENT_FILETOMIGRATEREQUEST, "Sent FileToMigrateRequest to client"},
{TAPESERVER_RECEIVED_FILETOMIGRATE, "Received FileToMigrate from client"},
{TAPESERVER_SENT_FILETORECALLREQUEST, "Sent FileToRecallRequest to client"},
{TAPESERVER_RECEIVED_FILETORECALL, "Received FileToRecall from client"},
{TAPESERVER_SENT_FILEMIGRATEDNOTIFICATION, "Sent FileMigratedNotification to client"},
{TAPESERVER_SENT_FILERECALLEDNOTIFICATION, "Sent FileRecalledNotification to client"},
{TAPESERVER_RECEIVED_NOMOREFILES, "Recieved NoMoreFiles from client"},
{TAPESERVER_RECEIVED_ACK_OF_NOTIFICATION, "Recieved acknowledge of notification from client"},
{TAPESERVER_RECEIVED_ENDNOTIFCATIONERRORREPORT, "Received EndNotificationErrorReport from client"},
{TAPESERVER_RECEIVED_NOTIFCATIONACKNOWLEDGE, "Received NotificationAcknowledge from client"},
{TAPESERVER_SEND_END_OF_SESSION_TO_RTCPD, "Sending end-of-session to RTCPD"},
{TAPESERVER_FAILED_TO_PARSE_TPCONFIG, "Failed to parse TPCONFIG file"},
{TAPESERVER_PARSED_TPCONFIG, "Parsed TPCONFIG"},
{TAPESERVER_CLOSED_RTCPD_DISK_TAPE_CONNECTION_DUE_TO_PEER, "Closed rtcpd disk/tape IO control connection due to rtcpd closing its end"},
{TAPESERVER_TOO_MANY_DRIVES_IN_TPCONFIG, "There are more drives in the TPCONFIG file than there were when tapeserverd was started.  Please restart tapeserverd."},
{-1, ""}};
