# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

mgm:
  xrd:
    # Additional tape-specific config
    # Allowing half the production (4k) size of the thread pool rather than the default 256.
    extraConfig: |
      mgmofs.reportstorepath /var/log/eos/report
      xrootd.chksum  adler32
      mgmofs.archivedir /var/eos/archive
      mgmofs.prepare.dest.space default
      mgmofs.tapeenabled true
      mgmofs.wfendpoint root://cta-frontend-wfe:10955
      mgmofs.wfresource /ctafrontend
      tpc.trace  all
      tpc.header2cgi  ArchiveMetadata archivemetadata
      taperestapi.sitename  cern-tape-archive-{{ include "mgm.instancename" . }}

      # TODO: remove this once the EOS PR gets merged
      mgmofs.protowfendpoint cta-frontend-wfe:10955
      mgmofs.protowfresource /ctafrontend
      # END

  # Generate the self-signed certificates for http
  initContainer: &init-container
    enabled: true
    script: |
      #!/usr/bin/bash
      /mkcert-ssl.sh
      chown -R daemon:daemon /etc/grid-security/certificates
    volumeMounts:
      - name: grid-security
        mountPath: /etc/grid-security

  extraVolumes: &extra-volumes
    volumeMounts:
      # varlog-tmp is the location where core dumps will end up
      - name: varlog-tmp
        mountPath: /var/log/tmp
      - name: grid-security
        mountPath: /etc/grid-security
        readOnly: true
    volumes:
      - name: varlog-tmp
        emptyDir: {}
      - name: grid-security
        emptyDir: {}

fst:
  replicaCount: 1
  podManagementPolicy: Parallel

  xrd:
    # Increasing 2x the thread pool size w.r.t. the minimal default 256.
    extraConfig: |
      xrootd.redirect {{ include "utils.mgm_address" . }}:1094 chksum
      fstofs.wfendpoint root://cta-frontend-wfe:10955
      fstofs.wfresource /ctafrontend
      fstofs.filemd_handler  attr
      tpc.trace  all

      # TODO: remove this once the EOS PR gets merged
      fstofs.protowfendpoint cta-frontend-wfe:10955
      fstofs.protowfresource /ctafrontend
      # END

  initContainer: *init-container
  extraVolumes: *extra-volumes
