# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

frontend-wfe:
  port: 10955
  legacy_xrootd_mode: true

frontend-admin:
  port: 10955
  legacy_xrootd_mode: true

cli:
  conf:
    cta:
      endpoint: cta-frontend-admin:10955
