# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

global:

  # With the /var/log custom mounts, we need to be both priviledged and allowPrivilegeEscalation
  securityContext:
    allowPrivilegeEscalation: True
    privileged: True

  # It should be noted that many logs also go to stdout which is still written to /var/log on the node itself
  # So this means not all log-related writes go to an SSD
  extraVolumes:
    volumes:
      - name: coredumps
        emptyDir: {}
    volumeMounts:
      - name: coredumps
        mountPath: /var/log/tmp

frontend:
  grpc:
    enabled: true
    conf:
      catalogue:
        numberOfConnections: 50
      logger:
        logLevel: "ERR"
  xrd:
    enabled: false
taped:
  logMask: "WARNING"

maintd:
  logging:
    level: "ERR"
