#!/usr/bin/perl
use strict;
use Time::HiRes qw( usleep ) ;

my $tag = shift @ARGV;

my $state = 0;
my $startstate=$state;
my $timeout = 30;           # 30 seconds
my $readtimeout = 60*60*48; # 48 hours
my $date=`date`; chomp $date;
my $passed;
my $now;
my $reqstatefile     = "/var/log/xroot/server/openrw/" . $tag;
my $reqstatefiledone = "/var/log/xroot/server/openrw/" . $tag . ".done";

my $starttime = time;
system("mkdir -p /var/log/xroot/server");
if (open FD , ">> /var/log/xroot/server/x2castorjob.log" ) {
    select ((select (FD), $| = 1)[0]);
    $date=`date`; chomp $date;
    print FD "$date x2castorjob [ $tag ] INFO  : starttime=$starttime showupttimeout=$timeout maxreadtimeout=$readtimeout\n";

    while (1) {
	if ( ($state==0) && (-r $reqstatefile )) {
	    $state = 1 ;
	    printf FD "$date x2castorjob [ $tag ] INFO  : is now open\n";
	}
	if ( ( -r "$reqstatefiledone" ) ) {
	    if ($state == 1 ) {
		printf FD "$date x2castorjob [ $tag ] INFO  : is now closed\n";
		$state = 2;
	    } else {
		printf FD "$date x2castorjob [ $tag ] INFO  : is now closed - but open was not seen\n";
		$state = 2;
	    }

	    system("pgrep -f stagerJob.*$tag > $reqstatefile.pid");

	    if ( -r $reqstatefile )    { unlink $reqstatefile;}
	    if ( -r $reqstatefiledone ) { unlink $reqstatefiledone; }
	}
	$now = time;
	$passed = $now - $starttime;
	$date=`date`; chomp $date;

	if ( ($state == 0 ) && ($passed > $timeout) ) {
            printf FD "$date x2castorjob [ $tag ] ERROR : no open seen within $timeout seconds\n";
            close FD;
            exit(-1);
        }

	if ( ($state != 2 ) && ($passed > $readtimeout) ) {
	    printf FD "$date x2castorjob [ $tag ] ERROR : no close seen within $readtimeout seconds\n";
	    close FD;
	    exit(-2);
	}
	
	if ( $state == 2 ) {
	    printf FD "$date x2castorjob [ $tag ] INFO  : stoptime=$now passed=$passed\n";
	    close FD;
	    exit(0);
	}
	usleep(100000);
    }
    close FD;
} else {
    printf STDERR "$date x2castorjob [ $tag ] ERROR : cannot open log file /var/log/xroot/server/x2castorjob.log\n";
    exit(-99);
}
