/*********************************************************************************/
/* File including the constants to represent the DLF Messages for the new */
/*******************************************************************************/

#ifndef TAPEGATEWAY_DLF_MESSAGES_HPP
#define TAPEGATEWAY_DLF_MESSAGES_HPP 1


namespace castor {
  namespace tape {
    namespace tapegateway{

      enum DlfCodes{

	DAEMON_START = 1,
	DAEMON_STOP = 2,
	NO_RETRY_POLICY_FOUND = 3,
	FATAL_ERROR  = 4, 

	PRODUCER_GETTING_TAPE = 5,
	PRODUCER_NO_TAPE = 6,
	PRODUCER_TAPE_FOUND =7,
	PRODUCER_CANNOT_UPDATE_DB = 8,
	PRODUCER_QUERYING_VMGR = 9,
	PRODUCER_VMGR_ERROR = 10,
	PRODUCER_SUBMITTING_VDQM = 11,
	PRODUCER_VDQM_ERROR = 12,
	PRODUCER_REQUEST_SAVED =13,

	CHECKER_GETTING_TAPES = 14,
        CHECKER_NO_TAPE = 15,
	CHECKER_QUERYING_VDQM = 16,
	CHECKER_LOST_VDQM_REQUEST = 17,
	CHECKER_CANNOT_UPDATE_DB = 18,
	CHECKER_RELEASING_UNUSED_TAPE = 19,
	CHECKER_VMGR_ERROR = 20,
	CHECHER_TAPES_FOUND = 21,
	CHECKER_TAPES_RESURRECTED = 22,

	LINKER_GETTING_STREAMS = 23,
	LINKER_NO_STREAM = 24,
	LINKER_QUERYING_VMGR = 25,
	LINKER_LINKING_TAPE_STREAM = 26,
	LINKER_CANNOT_UPDATE_DB = 27,
	LINKER_RELEASED_BUSY_TAPE = 28,
	LINKER_NO_TAPE_AVAILABLE = 29,
	LINKER_STREAMS_FOUND = 30,
	LINKER_TAPES_ATTACHED = 31,

	MIG_ERROR_GETTING_FILES = 32,
	MIG_ERROR_NO_FILE = 33,
	MIG_ERROR_RETRY = 34,
	MIG_ERROR_FAILED = 35,
	MIG_ERROR_RETRY_BY_DEFAULT = 36,
	MIG_ERROR_CANNOT_UPDATE_DB = 37,
	MIG_ERROR_TAPECOPIES_FOUND = 38,
	MIG_ERROR_RESULT_SAVED = 39,
	
	REC_ERROR_GETTING_FILES = 40,
	REC_ERROR_NO_FILE = 41,
	REC_ERROR_RETRY = 42,
	REC_ERROR_FAILED = 43,
	REC_ERROR_RETRY_BY_DEFAULT = 44,
	REC_ERROR_CANNOT_UPDATE_DB = 45,
	REC_ERROR_TAPECOPIES_FOUND = 46,
	REC_ERROR_RESULT_SAVED = 47,
	
	WORKER_MESSAGE_RECEIVED = 48,
	WORKER_UNKNOWN_CLIENT = 49,
	WORKER_INVALID_REQUEST =  50,
	WORKER_INVALID_CAST = 51,
	WORKER_DISPATCHING = 52,
	WORKER_RESPONDING = 53,
	WORKER_CANNOT_RESPOND  = 54,
	WORKER_CANNOT_RECEIVE = 55,
	WORKER_UNKNOWN_EXCEPTION = 56,
	 
	WORKER_VOLUME_REQUESTED = 57,
	WORKER_GETTING_VOLUME = 58,
	WORKER_NO_VOLUME = 59,
	WORKER_NO_FILE = 60,
	WORKER_VOLUME_FOUND = 61,

	WORKER_RECALL_NOTIFIED = 62,
	WORKER_RECALL_GET_DB_INFO = 63, 
	WORKER_RECALL_FILE_NOT_FOUND = 64,
	WORKER_RECALL_NS_CHECK = 65,
	WORKER_RECALL_NS_FAILURE = 66,
	WORKER_RECALL_DB_UPDATE = 67,
	WORKER_RECALL_CANNOT_UPDATE_DB = 68,
	WORKER_RECALL_CHECK_FILE_SIZE = 69,
	WORKER_RECALL_WRONG_FILE_SIZE= 70, 
	WORKER_RECALL_COMPLETED_UPDATE_DB = 71,
	
	WORKER_MIGRATION_NOTIFIED = 72,
	WORKER_MIGRATION_GET_DB_INFO = 73,
	WORKER_MIGRATION_FILE_NOT_FOUND = 74,
	WORKER_MIGRATION_VMGR_UPDATE = 75,
	WORKER_MIGRATION_NS_UPDATE = 76,
	WORKER_REPACK_NS_UPDATE = 78,
	WORKER_MIGRATION_NS_FAILURE = 79,
	WORKER_MIGRATION_VMGR_FAILURE = 80,
	WORKER_MIGRATION_DB_UPDATE = 81,
	WORKER_MIGRATION_CANNOT_UPDATE_DB = 82,

	WORKER_RECALL_REQUESTED = 83,
	WORKER_RECALL_RETRIEVED = 84,
	WORKER_RECALL_RETRIEVING_DB_ERROR = 85,
	WORKER_NO_FILE_TO_RECALL = 86,
	
	WORKER_MIGRATION_REQUESTED = 87,
	WORKER_MIGRATION_RETRIEVED = 88,
	WORKER_MIGRATION_RETRIEVING_DB_ERROR = 89,
	WORKER_NO_FILE_TO_MIGRATE = 90,

	WORKER_END_NOTIFICATION = 91,
	WORKER_END_DB_UPDATE = 92,
	WORKER_END_DB_ERROR = 93,
	WORKER_END_GET_TAPE_TO_RELEASE = 94,
	WORKER_END_RELEASE_TAPE = 95,
	WORKER_CANNOT_RELEASE_TAPE = 96,
	
	WORKER_TAPE_MAKED_FULL = 97,
	WORKER_CANNOT_MARK_TAPE_FULL = 98,

	WORKER_FAIL_NOTIFICATION = 99,
	WORKER_FAIL_DB_UPDATE = 100,
	WORKER_FAIL_DB_ERROR = 101,
	WORKER_FAIL_GET_TAPE_TO_RELEASE = 102,
	WORKER_FAIL_RELEASE_TAPE = 103,

	ORA_FILE_TO_MIGRATE_NS_ERROR = 104,
	ORA_DB_ERROR = 105,
	ORA_IMPOSSIBLE_TO_SEND_RMMASTER_REPORT = 106,
	ORA_FILE_TO_RECALL_NS_ERROR =107,
	LINKER_NOT_POOL = 108

      };
    }// end namespace tapegateway
  }// end namespace tape
}// end namespace castor

#endif

