'''
Created on Jul 13, 2010
suggesting parameters to TreeCalculators and TreeDesigner.
These properties are used as standard values, if nothing else is given.
Using these guideline values, TreeCalculators and TreeDesigner set properties for every ViewNode in ViewTree.

All of this result in following Properties of a ViewNode:

set by TreeCalculators:
treenode - original TreeNode object from data tree generated by TreeBuilder
spacesize - space to neighbour rectangles, in px
headersize - height of the rectangle header, in px
width - rectangle width
height - rectangle height
x - rectangle x pos in the image
y - rectangle y pos in the image
nbchildren - number of children the node has (for potential use)

set by TreeDesigner:
headertext - text string to show in the rectangle header
headertextisbold - defines if the header text should be bold
htmltooltiptext - defines the tooltip text for that node
fillcolor - color the rectangle should be filled with
level - level inside of the data tree (root is 0, ascending)
radiallight {'brightness': b, 'hue':h, 'opacity': o } - defines brightness, hue and opacity of the "light" shining at the rectangle

@author: kblaszcz
'''
#numbers must be floats!
from app.treemap.objecttree.ObjectTree import ObjectTree
from app.treemap.viewtree.ViewTree import ViewTree
treemap_props = {
'pxwidth': 800.0, #width
'pxheight': 600.0, #height
'objecttree': None,
'viewtree': None,    
'captionsize': 12.0,#headersize
'spacesize': 3.0,
'minspacesize': 1.0,
'inbordersize': 0.0,
'captionfontsize': 12.0, #headerfontsize
'radiallightbrightness': 0.4,
'captiontextisbold': True #headertextisbold
}

def checkAndPartiallyCorrectTreemapProps(props):
    height = props['pxheight']
    width = props['pxwidth']
    headersize = props['captionsize']
    spacesize = props['spacesize']
    minspacesize = props['minspacesize']
    inbordersize = props['inbordersize']
    headerfontsize = props['captionfontsize']
    radiallightbrightness = props['radiallightbrightness']
    headerfontsize = props['captionfontsize']
    
    if headersize > height:
        props['captionsize'] = height * 0.02
        
    if spacesize > min(width, height) * 0.25:
        props['spacesize'] = 4.0
        
    if minspacesize <= spacesize and minspacesize >= 0.0:
        props['minspacesize'] = minspacesize
        
    assert(isinstance(props['objecttree'], ObjectTree) or isinstance(props['objecttree'], None))
        
    if inbordersize > min(width, height) * 0.1:
        props['inbordersize'] = 1.0

        
    if headerfontsize > headersize - inbordersize:
        props['captionfontsize'] = headersize - inbordersize
        
    if radiallightbrightness > 1.0 or radiallightbrightness < 0.0:
        props['radiallightbrightness'] = 0.4
    
    assert(isinstance(props['viewtree'], ViewTree) or isinstance(props['viewtree'], None))

        


        