/**** This file has been autogenerated by gencastor from Umbrello UML model ***/

/******************************************************************************
 *                      castor/vdqm/TapeRequestStatusCode.h
 *
 * This file is part of the Castor project.
 * See http://castor.web.cern.ch/castor
 *
 * Copyright (C) 2003  CERN
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * @(#)$RCSfile: TapeRequestStatusCode.h,v $ $Revision: 1.1 $ $Release$ $Date: 2005/04/22 13:58:44 $ $Author: mbraeger $
 *
 * 
 *
 * @author Castor Dev team, castor-dev@cern.ch
 *****************************************************************************/

#ifndef CASTOR_VDQM_TAPEREQUESTSTATUSCODE_H
#define CASTOR_VDQM_TAPEREQUESTSTATUSCODE_H

//------------------------------------------------------------------------------
// This defines a C interface to the following enum
// enum TapeRequestStatusCode
// Contains all possible status of a tape Request
//------------------------------------------------------------------------------

#define Cvdqm_TapeRequestStatusCode_t TapeRequestStatusCode

#include "TapeRequestStatusCode.hpp"

#endif // CASTOR_VDQM_TAPEREQUESTSTATUSCODE_H
