{{- /*
SPDX-FileCopyrightText: 2026 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

{{- if .Values.resetMountDecision -}}
{{- $name := include "mountDecisionReset.fullname" . }}
{{- $mountDecisionConfig := include "mountDecision.config" . | fromYaml }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}-job
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if eq $mountDecisionConfig.backend "postgres" }}
    "helm.sh/hook": post-install
    {{- end }}
    "helm.sh/hook-delete-policy": keep
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cta
    spec:
      restartPolicy: Never
      imagePullSecrets:
      {{- include "mountDecisionReset.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: {{ $name }}
          image: {{ include "mountDecisionReset.image" . }}
          imagePullPolicy: {{ include "mountDecisionReset.imagePullPolicy" . }}
          command: ["bash", "/scripts/reset_mount_decision.sh"]
          args: []
          securityContext:
            allowPrivilegeEscalation: false
          stdin: true
          resources:
            requests:
              memory: "256Mi"
              ephemeral-storage: "128Mi"
            limits:
              memory: "2Gi"
              ephemeral-storage: "1Gi"
          env:
            - name: MY_NAME
              value: {{ $name }}
            - name: MY_NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: INSTANCE_NAME
              value: {{ .Release.Namespace | quote }}
          volumeMounts:
            - name: scripts-volume
              mountPath: /scripts
            - name: mount-decision-config
              mountPath: /etc/cta/cta-mount-decision.conf
              subPath: cta-mount-decision.conf
      volumes:
        - name: scripts-volume
          configMap:
            name: scripts-mount-decision
            defaultMode: 0777
        - name: mount-decision-config
          configMap:
            name: cta-mount-decision-conf
{{- end }}
