.lf 1 dlf.man
.\" @(#)$RCSfile: dlf.man,v $ $Revision: 1.2 $ $Date: 2004/07/02 13:32:30 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLF 1 "$Date: 2004/07/02 13:32:30 $" CASTOR "DLF Commands"
.SH DESCRIPTION
A Distributed Logging Facility (DLF) Server stores log messages
into the DLF database. You can use DLF without the DLF server when
logging to the local log file. In this case message texts can be loaded
from a text file. You have to specify the path to this file and that you
are using a standalone mode. This can be done by one of the following:
.RS
.LP
setting environment variables:
.LP
.B
<YOUR_FACILITY_NAME>_LOGMODE=STANDALONE
.LP
.B
<YOUR_FACILITY_NAME>_TXTFILE=<path_to_the_text_file>
.LP
where <YOUR_FACILITY_NAME> must be in uppercase, for example:
.RS
.HP
setenv DLFTEST_LOGMODE STANDALONE
.HP
setenv DLFTEST_TXTFILE /etc/castor/dlftest.txt
.RE
.LP
or adding the lines to the
.B /etc/shift.conf
, for example:
.RS
.HP
dlftest LOGMODE STANDALONE
.HP
dlftest TXTFILE /etc/castor/dlftest.txt
.RE
.LP
The format of the text file must be as follows:
.LP
The first line:
.LP
.B
<your_facility_name><spaces><assigned_facility_number>
.LP
The rest lines:
.LP
.B
<message_number><spaces><message_text_until_the_end_of_line>
.LP
.LP
.RE
There should be lines specifying log destinations in the CASTOR common
configuration file
.B /etc/shift.conf
or you can specify log destinations through environment variables.
.LP
The main DLF Server can be specified by one of the
following ways:
.RS
.LP
setting an environment variable 
.B DLF_HOST
, for example: 
.RS
.HP
setenv DLF_HOST castordlf
.RE
.LP
or an entry in 
.B /etc/shift.conf
, for example:
.RS
.HP
DLF  HOST castordlf
.RE
.RE
.LP
The DLF server listen TCP port number can be defined in the similar way
through the environment variable 
.B DLF_PORT
or via the entry in 
.B /etc/shift.conf:
.RS
.RS
.HP
DLF PORT 5035
.RE
.RE
.LP
This is the DLF server which will be contacted first to retrieve information
about the facility and retrieve facility specific message texts.
The log destinations must be specified as entries in the CASTOR common
configuration file 
.B /etc/shift.conf
or through the environment variables.
The file line format is as follows:
.RS
.HP
.B <fname><sp><slvl><sp><log_dst>[<sp><log_dst>...]
.RE
.LP
and if you are using environment variables the format must be as follows:
.RS
.HP
.B <FNAME>_<SLVL>="<log_dst>[<sp><log_dst>...]"
.HP
where
.TP
.I fname
is the facility name;
.TP
.I FNAME
is the facility name in uppercase letters;
.TP
.I sp
is any number of space characters or tabs;
.TP
.I slvl or SLVL
is the keyword defining the severity level of the messages
to be logged and must be one of the following:
.RS
.TP
.B LOGALL
.TP
.B LOGEMERGENCY
.TP
.B LOGALERT
.TP
.B LOGERROR
.TP
.B LOGWARNING
.TP
.B LOGAUTH
.TP
.B LOGSECURITY
.TP
.B LOGUSAGE
.TP
.B LOGSYSTEM
.TP
.B LOGIMPORTANT 
.TP
.B LOGDEBUG
.RE
.TP
.I log_dst
is the log destination in the URL format, and may be one of the
following:
.RS
.HP
.B file://<path_to_local_file>
.RE
or
.RS
.HP
.B x-dlf://<dlf_server_name>[:<tcp_port_number>]/
.RE
.LP
If tcp port number is not specified it will be taken from the main DLF
server record.
Example:
.TP
.B dlftest     LOGALL    x-dlf://castordev.cern.ch:5035/
.LP
Or if you are using environment variable:
.TP
.B setenv DLFTEST_LOGALL  x-dlf://castordev.cern.ch:5035/
.LP
This means that all log messages from dlftest will go to castordev.cern.ch
and will be stored in the database.
.RE
.LP
Use 
.B man
command for details of the commands recognized by the DLF:
.TP 1.5i
dlfdeletefacility
remove the definition of a facility from the CASTOR DLF Database (admin only)
.TP
dlfdeletetext
remove a message text from the CASTOR DLF Database (admin only)
.TP
dlfenterfacility
enter a new facility into the CASTOR DLF Database (admin only)
.TP
dlfentertext
enter a new message text into the CASTOR DLF database (admin only)
.TP
dlflistfacility
list all known facilities
.TP
dlflisttext
list all texts of the given facility
.TP
dlfmodifyfacility
change the name of an existing facility in the CASTOR DLF database (admin only)
.TP
dlfmodifytext
modify the text of the given facility in the CASTOR DLF database (admin only)
.TP
dlflogstore
transfer log file to the DLF server
.TP
dlfshutdown
shutdown the CASTOR DLF Server (admin only)
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
