.lf 1 dlf_shutdown.man
.\" @(#)$RCSfile: dlf_shutdown.man,v $ $Revision: 1.1 $ $Date: 2006/03/28 12:15:57 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLF_SHUTDOWN 3 "$Date: 2006/03/28 12:15:57 $" CASTOR "DLF Library Functions"
.SH NAME
dlf_shutdown \- frees memory occupied by the  DLF structures
.SH SYNOPSIS
.br
\fB#include "dlf_api.h"\fR
.sp
.BI "void dlf_shutdown ()"
.SH DESCRIPTION
.B dlf_shutdown
frees memory occupied by the  DLF structures.
This function must be called at the application exit.
.SH SEE ALSO
.BR dlf_init(3)
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
