.lf 1 dlfdeletetext.man
.\" @(#)$RCSfile: dlfdeletetext.man,v $ $Revision: 1.1 $ $Date: 2003/08/20 13:01:52 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLFDELETETEXT 1 "$Date: 2003/08/20 13:01:52 $" CASTOR "DLF Administrator Commands"
.SH NAME
dlfdeletetext \- delete specified text for the given facility from the CASTOR
DLF database
.SH SYNOPSIS
.B dlfdeletetext
.BI -F " facility_name"
.BI -n " text_number"
.SH DESCRIPTION
.B dlfdeletetext
deletes specified message text for the given facility from the CASTOR DLF database.
.TP
.I facility_name
is alphanumeric. It must be at most DLF_MAXFACNAMELEN characters long.
.TP
.I text_number
is the message text assigned number.
It must be greater than 0 but less or equal to 65535.
.LP
This command requires ADMIN privilege in the Cupv database.
.SH EXAMPLES
.nf
.ft CW
dlfdeletetext -F staged -n 154
.ft
.fi
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Cupvlist(1) ,
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
