.lf 1 dlfdeletefacility.man
.\" @(#)$RCSfile: dlfdeletefacility.man,v $ $Revision: 1.1 $ $Date: 2003/08/20 13:01:12 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLFDELETEFACILITY 1 "$Date: 2003/08/20 13:01:12 $" CASTOR "DLF Administrator Commands"
.SH NAME
dlfdeletefacility \- delete the given facility entry from the CASTOR
DLF database
.SH SYNOPSIS
.B dlfdeletefacility
.BI -F " facility_name"
.SH DESCRIPTION
.B dlfdeletefacility
deletes the given facility entry from the CASTOR DLF database.
.TP
.I facility_name
is alphanumeric. It must be at most DLF_MAXFACNAMELEN characters long.
.LP
This command requires ADMIN privilege in the Cupv database.
.SH EXAMPLES
.nf
.ft CW
dlfdeletefacility -F sstaged
.ft
.fi
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Cupvlist(1) ,
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
