.lf 1 dlfenterfacility.man
.\" @(#)$RCSfile: dlfenterfacility.man,v $ $Revision: 1.1 $ $Date: 2003/08/20 13:02:43 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLFENTERFACILITY 1 "$Date: 2003/08/20 13:02:43 $" CASTOR "DLF Administrator Commands"
.SH NAME
dlfenterfacility \- enter a new facility in the CASTOR
DLF database
.SH SYNOPSIS
.B dlfenterfacility
.BI -F " facility_name"
.BI -n " facility_number"
.SH DESCRIPTION
.B dlfenterfacility
enters a new facility in the CASTOR DLF database.
.TP
.I facility_name
is alphanumeric. It must be at most DLF_MAXFACNAMELEN characters long.
.TP
.I facility_number
is the facility assigned number.
It must be greater than 0 but less or equal to 255.
.LP
This command requires ADMIN privilege in the Cupv database.
.SH EXAMPLES
.nf
.ft CW
dlfenterfacility -F staged -n 1
.ft
.fi
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Cupvlist(1) ,
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
