.lf 1 dlflisttext.man
.\" @(#)$RCSfile: dlflisttext.man,v $ $Revision: 1.1 $ $Date: 2003/08/20 13:04:59 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLFLISTTEXT 1 "$Date: 2003/08/20 13:04:59 $" CASTOR "DLF Administrator Commands"
.SH NAME
dlflisttext \- list all message texts for a given facility in the CASTOR
DLF database
.SH SYNOPSIS
.B dlflisttext
.BI -F " facility_name"
.SH DESCRIPTION
.B dlflisttext
lists all message texts for a given facility in the CASTOR DLF database in tabular form:
.HP 1.2i
text_number		message text assigned number
.HP
message_text		the text of the message
.SH EXAMPLES
.nf
.ft CW
dlflisttext -F dlftest

Facility: dlftest, Facility number: 255

1: DLFtest message number 1
2: DLFtest message number 2
3: DLFtest message number 3

.ft
.fi
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Cupvlist(1) ,
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
