.lf 1 dlflogstore.man
.\" @(#)$RCSfile: dlflogstore.man,v $ $Revision: 1.1 $ $Date: 2003/08/20 13:06:12 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLFLOGSTORE 1 "$Date: 2003/08/20 13:06:12 $" CASTOR "DLF Administrator Commands"
.SH NAME
dlflogstore \- store log messages from the given logfile into the CASTOR
DLF database
.SH SYNOPSIS
.B dlflogstore
.BI -f " file_name"
.BI -h " host_name"
[
.BI -p " port_number"
] [
.BI -s " severity_level"
]
.SH DESCRIPTION
.B dlflogstore
stores log messages from the given logfile into the CASTOR
DLF database.
.TP
.I file_name
is the name of the input log file. It must be at most
CA_MAXPATHLEN characters long.
.TP
.I host_name
is the name of the DLF server host.
.TP
.I port_number
is the TCP port number on which the DLF server is listening. If not specified
the default port will be used.
.TP
.I severity_level
is the name of the severity level. If specified only messages with this
severity level will be send to the DLF server for storing.
.SH EXAMPLE
.nf
.ft CW
dlflogstore -f /usr/spool/stage/log -h castor.cern.ch
.ft
.fi
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
