.lf 1 dlflistfacility.man
.\" @(#)$RCSfile: dlflistfacility.man,v $ $Revision: 1.1 $ $Date: 2003/08/20 13:04:09 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLFLISTFACILITY 1 "$Date: 2003/08/20 13:04:09 $" CASTOR "DLF Administrator Commands"
.SH NAME
dlflistfacility \- list all existing facilities in the CASTOR
DLF database
.SH SYNOPSIS
.B dlflistfacility
..SH DESCRIPTION
.B dlflistfacility
lists all existing facilities in the CASTOR DLF database in tabular form:
.HP 1.2i
facility_number		facility assigned number
.HP
facility_name		name of the facility
.SH EXAMPLE
.nf
.ft CW
dlflistfacility
List of facilities:
===================
160     test3
200     testx
201     test1
202     test2
255     dlftest
.ft
.fi
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Cupvlist(1) ,
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
