.lf 1 dlfmodifyfacility.man
.\" @(#)$RCSfile: dlfmodifyfacility.man,v $ $Revision: 1.1 $ $Date: 2003/08/20 13:06:52 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLFMODIFYFACILITY 1 "$Date: 2003/08/20 13:06:52 $" CASTOR "DLF Administrator Commands"
.SH NAME
dlfmodifyfacility \- modify the name of the given facility in the CASTOR
DLF database
.SH SYNOPSIS
.B dlfmodifyfacility
.BI -F " facility_new_name"
.BI -n " facility_number"
.SH DESCRIPTION
.B dlfmodifyfacility
modifies the name of the facility identified by its assigned number
in the CASTOR DLF database.
.TP
.I facility_new_name
is alphanumeric. It must be at most DLF_MAXFACNAMELEN characters long.
.TP
.I facility_number
is the facility assigned number.
.LP
This command requires ADMIN privilege in the Cupv database.
.SH EXAMPLES
.nf
.ft CW
dlfmodifyfacility -F sstaged -n 1
.ft
.fi
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Cupvlist(1) ,
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
