.lf 1 dlfmodifytext.man
.\" @(#)$RCSfile: dlfmodifytext.man,v $ $Revision: 1.1 $ $Date: 2003/08/20 13:07:26 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLFMODIFYTEXT 1 "$Date: 2003/08/20 13:07:26 $" CASTOR "DLF Administrator Commands"
.SH NAME
dlfmodifytext \- modify existing text for the given facility in the CASTOR
DLF database
.SH SYNOPSIS
.B dlfmodifytext
.BI -F " facility_name"
.BI -n " text_number"
.BI -t " message_text"
.SH DESCRIPTION
.B dlfmodifytext
modifies a message text for the given facility in the CASTOR DLF database.
.TP
.I facility_name
is alphanumeric. It must be at most DLF_MAXFACNAMELEN characters long.
.TP
.I text_number
is the message text assigned number.
It must be greater than 0 but less or equal to 65535.
.TP
.I message_text
is the text corresponding to text_number. It must be at most DLF_MAXSTRVALLEN
characters long.
.LP
This command requires ADMIN privilege in the Cupv database.
.SH EXAMPLES
.nf
.ft CW
dlfmodifytext -F staged -n 154 -t "Symbolic link not created"
.ft
.fi
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Cupvlist(1) ,
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
