.lf 1 dlfshutdown.man
.\" @(#)$RCSfile: dlfshutdown.man,v $ $Revision: 1.1 $ $Date: 2003/08/20 13:08:33 $ CERN IT-ADC Vitaly Motyakov
.\" Copyright (C) 2003 by CERN/IT/ADC
.\" All rights reserved
.\"
.TH DLFSHUTDOWN 1 "$Date: 2003/08/20 13:08:33 $" CASTOR "DLF Administrator Commands"
.SH NAME
dlfshutdown \- shutdown the dlf server
.SH SYNOPSIS
.B dlfshutdown
.RB [ -f ]
.SH DESCRIPTION
.B dlfshutdown
shuts the dlf server down.
It waits for outstanding requests to complete. New requests will be rejected
with
.B serrno
set to
.BR EDLFNACT .
Connections to the database server are closed one by one when they are not
used anymore and when all connections are closed, the dlf server exits.
.LP
This command requires ADMIN privilege in the Cupv database.
.SH OPTIONS
.TP
.B -f
force shutdown, i.e. long operations like storing log files can be aborted.
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.B Cupvlist(1)
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
