#!/bin/bash

EINVAL=22
ECANCELED=125

export XrdSecPROTOCOL=sss
export XrdSecSSSKT=/etc/ctafrontend_SSS_c.keytab

export XRD_STREAMTIMEOUT=600     # increased from 60s
export XRD_TIMEOUTRESOLUTION=600 # increased from 15s

if test $# -ne 5; then
  echo "Wrong number of command-line arguments"
  echo "Usage: delete_archive_file wf_tag rusername rgroupname archive_file_id file_path"
  exit ${EINVAL}
fi

WF_TAG="$1"
RUSERNAME="$2"
RGROUPNAME="$3"
ARCHIVE_FILE_ID="$4"
FILE_PATH="$5"

LOG_DATE=`/usr/bin/date +%s | /usr/bin/tr '\n' ' ' ; /usr/bin/date`
LOG_SCRIPT_NAME=`basename $0`
LOG_FILE="/var/log/eos/wfe/${WF_TAG}.log"

if test UNDEF = ${ARCHIVE_FILE_ID}; then
  echo "$LOG_DATE $LOG_SCRIPT_NAME ignoring deletion of non-existent tape archive file: rusername=${RUSERNAME} rgroupname=${RGROUPNAME} archiveFileId=${ARCHIVE_FILE_ID} path=${FILE_PATH}" >> ${LOG_FILE}
  exit 0
fi

if RESULT=`2>&1 /usr/bin/cta deletearchive --user ${RUSERNAME} --group ${RGROUPNAME} --id ${ARCHIVE_FILE_ID}`; then
  echo "$LOG_DATE $LOG_SCRIPT_NAME deleted tape archive file: rusername=${RUSERNAME} rgroupname=${RGROUPNAME} archiveFileId=${ARCHIVE_FILE_ID} path=${FILE_PATH}" >> ${LOG_FILE}
  exit 0
else
  echo "$LOG_DATE $LOG_SCRIPT_NAME failed to delete tape archive file: error=${RESULT} rusername=${RUSERNAME} rgroupname=${RGROUPNAME} archiveFileId=${ARCHIVE_FILE_ID} path=${FILE_PATH}" >> ${LOG_FILE}
  exit ${ECANCELED}
fi
