Document: castor
Title: Debian castor Manual
Author: <insert document author here>
Abstract: This manual describes what castor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/castor/castor.sgml.gz

Format: postscript
Files: /usr/share/doc/castor/castor.ps.gz

Format: text
Files: /usr/share/doc/castor/castor.text.gz

Format: HTML
Index: /usr/share/doc/castor/html/index.html
Files: /usr/share/doc/castor/html/*.html

  
