.\" @(#)$RCSfile: tpconfig.man,v $ $Revision: 1.4 $ $Date: 2001/09/26 09:13:56 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1990-2000 by CERN/IT/PDP/DM
.\" All rights reserved
.\"
.TH TPCONFIG 1 "$Date: 2001/09/26 09:13:56 $" CASTOR "Ctape Administrator Commands"
.SH NAME
tpconfig \- configure tape drive up/down
.SH SYNOPSIS
.B tpconfig
.I drive_name drive_status
.RI [ reason ]
.SH DESCRIPTION
.B tpconfig
configures drive up or down. This tells the tape daemon if the drive
can be allocated or not. The list of drive names may be found by using
.BR tpstat .
The
.B tpconfig
command is restricted to privileged users such as root and operator.
.TP 1.2i
.I drive_name
may be either a simple drive name if the program is executed on the tape server
itself or drivename@hostname.
.TP 1.2i
.I drive_status
can be
.B up
or
.BR down .
.TP
.I reason
is an optional alphanumeric string:
.LP
When
.I drive_status
is
.BR down ,
.I reason
may be one of the following:
.RS
.TP
.B cleaning
.TP
.B test
.TP
.B failure
.TP
.B system
.TP
.B suspect
.TP
.B upgrade
.TP
.B ops
.RE
.LP
When
.I drive_status
is
.BR up ,
.I reason
may be one of the following:
.RS
.TP
.B cleaned
.TP
.B replaced
.TP
.B repaired
.TP
.B preventive
.TP
.B upgraded
.TP
.B ops
.RE

.SH EXAMPLE
.nf
.ft CW
tpconfig dlt02@shd34 up cleaned
.ft
.fi
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Ctape_config(3) ,
.B Ctape_status(3)
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
