.\" @(#)$RCSfile: tpdaemon.man,v $ $Revision: 1.4 $ $Date: 2001/05/04 05:38:02 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1990-2001 by CERN/IT/PDP/DM
.\" All rights reserved
.\"
.TH TPDAEMON 1 "$Date: 2001/05/04 05:38:02 $" CASTOR "Ctape Administrator Commands"
.SH NAME
tpdaemon \- starts the tape daemon
.SH SYNOPSIS
.B  /usr/local/bin/tpdaemon
.SH DESCRIPTION
.LP
The 
.B tpdaemon
command starts the tape daemon.
This command is usually executed at system startup time
.RB ( /etc/rc.local ).
This will read the configuration file
/etc/TPCONFIG and look for requests. Short requests like
.B tpstat
are processed in the main loop. The daemon forks overlays to execute
long requests like mounting, positionning, unloading tapes or configuring
drives.
.LP
All error messages and statistical information are kept in a log.
.LP
The tape daemon listen port number can be defined on client hosts and
on the tape server itself in either of the following ways:
.RS
.LP
setting an environment variable TAPE_PORT
.RS
.HP
setenv TAPE_PORT 5011
.RE
.LP
an entry in
.B /etc/shift.conf
like:
.RS
.HP
TAPE	PORT	5011
.RE
.LP
an entry in
.B /etc/services
like:
.RS
.HP
tape          5011/tcp                        # CASTOR tape daemon
.RE
.RE
.LP
If none of these methods is used, the default port number is taken from the
definition of TAPE_PORT in Ctape_constants.h.
.LP
There must be one entry in the configuration file per tape drive giving:
.RS
.TP 1.2i
drive name
as seen by the operators in the mount messages.
The name cannot exceed 8 characters.
.TP
device group
must be a member of an installation defined set of "device groups"
.TP
device name
as defined in /dev.
The device must not rewind on close and have a Berkeley behaviour.
.TP
density
corresponding to the entry in /dev
.TP
initial status
.B up
or
.B down
.TP
robot/manual
if the drive is defined as part of a
.BR robot ,
there will be no check on the ring status. This field may also be set to
.BI lmcp xxxx
(Library Manager Control Point as defined in /dev)
if the IBM 3494/3495 robot is driven directly from an RS 6000,
.BI acs a,l,p,d
for an STK robot driven by ACSLS,
.BI R x
for a SONY DMS-24 or
.BI smc x
for a SCSI robot.
.TP
device type
for IBM
.B 3480
compatible drives, IBM
.BR 3590 ,
STK
.B SD3
(Redwood), STK
.B 9840
or drives equipped with Vision Boxes from Peripheral Vision
.RB ( /VB ) ,
the drive LED display will show
the vid requested or mounted or error messages like "wrong ring" or "wrong vsn".
For
.BR DLT s,
.BR SD3 s
and
.BR 9840 s
connected to DEC alpha or Linux systems or IBM
.BR 3590 s
connected to AIX or Linux platforms, fast tape positionning is used.
.RE
.LP
If a tape drive supports several densities, there must be one line per density.
.SH FILES
.TP 1.5i
.B /etc/TPCONFIG
configuration file
.TP
.B /usr/spool/tape/log
.SH EXAMPLES
.LP
Here is an example of a configuration file:

.nf
.ft CW
# 				Tape configuration
#
# drive	  dev		dev		density		initial	robot/	dev
# name	  group		name		(0 = N/A)	status	manual	type
#
cart0     CART		/dev/nrmt0	0		up	manual	3480
cart1     CART		/dev/nrmt1	0		up	manual	3480
exab0     8500		/dev/nrmt9	8500		up	manual	8500/VB
.ft
.fi
