{{- /*
SPDX-FileCopyrightText: 2025 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

{{- if .Values.enabled }}
{{- $name := "cta-frontend-admin" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ $name }}
  clusterIP: None
  ports:
  - name: {{ $name }}
    port: {{ .Values.port }}
    protocol: TCP
{{- end }}
