apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eos-status-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
