kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claimfst
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.fstStorage  }}
  selector:
    matchLabels:
      type: stg
