/**** This file has been autogenerated by gencastor from Umbrello UML model ***/

/******************************************************************************
 *                      castor/repack/FileListHelper.hpp
 *
 * This file is part of the Castor project.
 * See http://castor.web.cern.ch/castor
 *
 * Copyright (C) 2003  CERN
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * @(#)$RCSfile: FileListHelper.hpp,v $ $Revision: 1.2 $ $Release$ $Date: 2006/01/25 08:24:27 $ $Author: felixehm $
 *
 * 
 *
 * @author Castor Dev team, castor-dev@cern.ch
 *****************************************************************************/

#ifndef CASTOR_REPACK_FILELISTHELPER_HPP
#define CASTOR_REPACK_FILELISTHELPER_HPP

// Include Files
#include <vector>
#include <algorithm>
#include "castor/repack/RepackCommonHeader.hpp"
#include "castor/repack/RepackSegment.hpp"
#include "castor/repack/RepackRequest.hpp"
#include "castor/repack/RepackSubRequest.hpp"
#include "osdep.h"
#include "Cns_api.h"



namespace castor {

  namespace repack {

    /**
     * class FileListHelper
     */
    class FileListHelper {

    public:

      /**
       * Empty Constructor
       */
      FileListHelper();
      
      /**
       * Contructor, with initialises the FilelistHelper 
       * with a special nameserver
       */
      FileListHelper(std::string nameserver);

      /**
       * Empty Destructor
       */
      virtual ~FileListHelper();

      /**
       * Returns a vector with a filelist with full pathname.
       * @param rreq The Request of the Tape
       */
      std::vector<std::string>* getFileList(
      							castor::repack::RepackSubRequest *sreq) throw();

      /**
       * Fills the Request with the segments on the tape
       * elements
       * @param vid The Request of the Tape
       */
      int getFileListSegs(castor::repack::RepackSubRequest *sreq);
                          
	private:
		/**
		 * The nameserver this Class contacts
		 */
		std::string m_ns;
		
    }; // end of class FileListHelper

  }; // end of namespace repack

}; // end of namespace castor

#endif // CASTOR_REPACK_FILELISTHELPER_HPP
