.\" @(#)$RCSfile: vmgr.man,v $ $Revision: 1.4 $ $Date: 2001/02/23 16:49:23 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 2000 by CERN/IT/PDP/DM
.\" All rights reserved
.\"
.TH VMGR 1 "$Date: 2001/02/23 16:49:23 $" CASTOR "vmgr Commands"
.SH DESCRIPTION
A vmgr daemon manages the tape pool space.
A tape pool consists in a set of cartridges.
It can be private to an experiment or public.
Use 
.B man
command for details of the commands recognized by the vmgr:
.TP 1.5i
vmgrdeletepool
remove the definition of a pool of tapes from the CASTOR Volume Manager Database (admin only)
.TP
vmgrdeletetape
remove a tape from the CASTOR Volume Manager Database (admin only)
.TP
vmgrenterdenmap
enter a new triplet model/media_letter/density in the CASTOR Volume Manager Database (admin only)
.TP
vmgrentermodel
enter a new model of cartridge in the CASTOR Volume Manager Database (admin only)
.TP
vmgrenterpool
define a new tape pool (admin only)
.TP
vmgrentertape
enter a new tape in the CASTOR Volume Manager Database (admin or operator only)
.TP
vmgrlistdenmap
list all existing triplets model/media_letter/density
.TP
vmgrlistmodel
query the CASTOR Volume Manager about a given model or list all existing cartridge models
.TP
vmgrlistpool
query the CASTOR Volume Manager about a given tape pool or list all existing pools
.TP
vmgrlisttape
query the CASTOR Volume Manager about a tape or list all existing tapes
.TP
vmgrmodifypool
modify the definition of an existing tape pool in the CASTOR Volume Manager (admin only)
.TP
vmgrmodifytape
modify an existing tape volume entry in the CASTOR Volume Manager (admin or operator only)
.TP
vmgrshutdown
shutdown the CASTOR Volume Manager (admin only)
