.lf 3 dlf_isinitialized.man
.TH dlf_isinitialized 3 "CERN IT-FIO" CASTOR "DLF Library Functions"
.SH NAME
dlf_isinitialized \- checks to see if the DLF interface is initialized
.SH SYNOPSIS
.B #include "dlf_api.h"

.BI "void dlf_isinitialized (void)"
.SH DESCRIPTION
.B dlf_isinitialized
checks to see if the DLF interface has been previsouly initialized via a call to
.BR dlf_init().
The function returns 1 if the interface has been initialized, 0 if it has not.

.SH "SEE ALSO"
.BR dlf_init (3)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
