.lf 3 dlf_reqtext.man
.TH dlf_reqtext 3 "2006/06/12 12:00:00 CERN IT-FIO" CASTOR "DLF Library Functions"
.SH NAME
dlf_regtext \- register a message text for the given facility 
.SH SYNOPSIS
.B #include "dlf_api.h"

.BI "int dlf_init (unsigned short " msg_no, " const char * " msg_text ")"
.SH DESCRIPTION
.B dlf_regtext
is used to register a message text for a given facility, previously defined in a call to
.BR "dlf_init" (3) 
with the DLF client api. All message texts should be registered with the api after calling
.BR "dlf_init" (3) 
and before any calls to log messages through 
.BR "dlf_write" (3) 
If the message is not registered any logging messages which would like to log a message with that particular 
text will fail.

The
.I msg_no
argument is the unique message number associated with the message text.

The
.I msg_text
argument is a string to the text associated with the message number

.SH "RETURN VALUE"
The function returns 0 on success and -1 on error normally caused by the maximum amount of messages texts 
being reached.

.SH NOTE
The api will not register more then
.BR DLF_MAX_MSGTEXTS 
.\- 1024 messages at any given time and the message itself cannot exceed more then
.BR DLF_LEN_MSGTEXTS
.\- 512 chacraters in length.


.SH "SEE ALSO"
.BR dlf_init (3),
.BR dlf_shutdown (3),
.BR dlf_write (3)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
