.lf 3 dlf_shutdown.man
.TH dlf_shutdown 3 "CERN IT-FIO" CASTOR "DLF Library Functions"
.SH NAME
dlf_shutdown \- shutdown the DLF interface
.SH SYNOPSIS
.B #include "dlf_api.h"

.BI "int dlf_shutdown (int " wait ")"
.SH DESCRIPTION
.B dlf_shutdown
shuts down the DLF interface. If the interface is already shutdown by a previous call or the interface was not previous initialised with a call to
.BR "dlf_init" (3)
then no action will be taken.

If a
.I wait
time is greater then 0, then the api will wait up to X seconds for the threads to flush their messages queues to the
.BR dlfserver

Note: once shutdown the api cannot be re initialised
.BR "dlf_init" (3)

.SH "RETURN VALUE"
The function always returns 0 indicating success.

.SH "SEE ALSO"
.BR dlf_init (3),

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
