.lf 3 dlf_create_threads.man
.TH dlf_create_threads 3 "CERN IT-FIO" CASTOR "DLF Library Functions"
.SH NAME
dlf_create_threads \- starts the dlf threads
.SH SYNOPSIS
.B #include "dlf_api.h"

.BI "void dlf_create_threads (int " erase")"
.SH DESCRIPTION
.B dlf_create_threads
used to create the dlf threads enabling communication between client and server. This call is only required if remote logging is enabled and dlf_init() was called with the usethreads = 0. This call is designed to be used in special cases whereby creation of the dlf threads should not be done with a call to
.BR dlf_child()
but at the discretion of the callee. For example, at daemonization time the callee may decide in the child process that the first thing to create is a signal handler thread before the creation of dlf thread. Why before? because the re-creation of the dlf threads will inherit the signal mask of the child. If the signal mask has not been setup correctly, the dlf threads have the potential of trapping signals sent to the process as opposed to the dedicated signal handler. This will cause signals to be interrupted incorrectly.

The
.I erase 
flag indicates whether the messages cached in the threads buffer populated by calls to 
.I dlf_writep()
should be erased before creating the thread.

.SH "SEE ALSO"
.BR dlf_init (3)
.BR dlf_child (3)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
