# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

secrets:
  image: registry.cern.ch/docker.io/almalinux/9-minimal:9.7

kerberos:
  image: registry.cern.ch/docker.io/almalinux/9-minimal:9.7
  defaultRealm: TEST.CTA
  adminPrinc:
    name: root
    password: "defaultcipassword"
