.\" Copyright (C) 2003  CERN
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.TH READTP 1 "$Date: 2009/07/31 11:59:45 $" CASTOR "Set a volume priority"
.SH NAME
readtp \- read from a tape
.SH SYNOPSIS
.BI "readtp VID SEQUENCE [OPTIONS] [FILE]..."

.SH DESCRIPTION
.B readtp
reads one or files from a tape and writes them to disk.
.P
This command gives privileged users direct access to the tape system.
.P
The tape to be read is specified by the \fBVID\fP argument.  The tape files to
be read are specified as a \fBSEQUENCE\fP of tape file sequence numbers.  The
syntax used to specify the sequence is as follows:
.RS
.TP 1.5i
.I f1\-f2
Files
.I f1
to
.I f2
inclusive.
.TP
.I f1\-
Files
.I f1
to the last file on the tape.
.TP
.I f1\-f2,\|f4,\|f6-
A series of non\-consecutive ranges of files.
.RE
.P
The filenames of the destination disk files can be specified using two
mutually-exclusive methods.  They can be entered on the command-line
(\fB[FILE]\fP) or in a "file-list" file using the
.B -f, --filelist
option.

.SH OPTIONS
.TP
\fB\-d, \-\-debug
Prints debug information.
.TP
\fB\-h, \-\-help
Prints the usage message.
.TP
\fB\-s, \-\-server server
Specifies the tape server to be used, therefore overriding the drive scheduling
of the VDQM.  If this option is not set then the VDQM will allocate the first
free drive it finds that is suitable for reading the tape.
.TP
\fB\-f, \-\-filelist file
File containing the list of destination filenames in RFIO notation
[host:]local_path.  There should be one filename per line with no whitespace or
comments.  Please note that this option is mutually exclusive with the method
of providing filenames on the command-line.

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
