# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "eos-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
cern-st-grpc = { workspace = true }
eos-protobuf = { workspace = true }
log          = { workspace = true }
nix          = { workspace = true, features = ["fs"] }
thiserror    = { workspace = true }
tokio-stream = { workspace = true }
tonic        = { workspace = true }

[dev-dependencies]
bytes        = { workspace = true }
tokio        = { workspace = true }
url          = { workspace = true }

[lints]
workspace = true
