# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

# Take care with increasing this number, as CTA has not been tested with multiple frontend replicas
# Increasing this will most likely not work as expected
replicas: 1
enabled: true
port: 10956

conf:
  numberOfThreads: 512

  catalogue:
    numberOfConnections: 10
    # Reduced value for test environment
    missingFileCopiesMinAgeSecs: 5

  frontend:
    archiveFileMaxSizeGb: 1000
    zeroLengthFilesForbidden: true
    zeroLengthFilesForbiddenVoExceptionList: ""
    # repackBufferUrl

  schedulerdb:
    numberOfConnections: 3
    numberOfThreads: 500
    threadStackSizeMb: 1
    disableRepackRequests: false
    disableUserRequests: false
    tapeCacheMaxAgeSecs: 1
    retrieveQueueCacheMaxAgeSecs: 1

  logger:
    logLevel: "DEBUG"
    logFormat: json
    ssiLogLevel: "warning"

  tls:
    serverKey: /etc/grpc-certs/key/server-wfe.key.pem
    serverCert: /etc/grpc-certs/cert/server-wfe.crt.pem
    caCert: /etc/grpc-certs/ca/ca.crt.pem

  auth:
    method: jwt
    config:
      kerberos:
        secretName: cta-frontend-keytab
        subPath: cta-frontend.keytab
        keytab: /etc/cta/cta-frontend.krb5.keytab
        service_principal: "cta/cta-frontend-admin@TEST.CTA"


  telemetry:
    enabled: false
    retainInstanceIdOnRestart: false
    metrics:
      backend: "NOOP"
      exportInterval: 1000
      exportTimeout: 500
      otlp:
        endpoint: ""
        auth:
          basic:
            username: ""
            passwordSecret: ""
      file:
        endpoint: ""

# Script to execute in the main container before starting the frontend service
preRun:
  enabled: false
  script: |
    #!/usr/bin/bash

# Script to execute in the main container after frontend exited
postRun:
  enabled: true
  script: |
    #!/usr/bin/bash
    echo "Process crashed. Sleeping..."
    sleep infinity

pod:
  extraSpec:
    terminationGracePeriodSeconds: 1

extraEnv:

extraVolumes:
  volumes:
  volumeMounts:
