/**** This file has been autogenerated by gencastor from Umbrello UML model ***/

/******************************************************************************
 *                      castor/infoPolicy/DbInfoPolicy.hpp
 *
 * This file is part of the Castor project.
 * See http://castor.web.cern.ch/castor
 *
 * Copyright (C) 2003  CERN
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * @(#)$RCSfile$ $Revision$ $Release$ $Date$ $Author$
 *
 * 
 *
 * @author Castor Dev team, castor-dev@cern.ch
 *****************************************************************************/

#ifndef CASTOR_INFOPOLICY_DBINFOPOLICY_HPP
#define CASTOR_INFOPOLICY_DBINFOPOLICY_HPP

// Include Files
#include "castor/IObject.hpp"
#include <iostream>
#include <string>

namespace castor {

  // Forward declarations
  class ObjectSet;

  namespace infoPolicy {

    // Forward declarations
    class PolicyObj;

    /**
     * class DbInfoPolicy
     */
    class DbInfoPolicy : public virtual castor::IObject {

    public:

      /**
       * Empty Destructor
       */
      virtual ~DbInfoPolicy() throw() {};

      /**
       * Outputs this object in a human readable format
       * @param stream The stream where to print this object
       * @param indent The indentation to use
       * @param alreadyPrinted The set of objects already printed.
       * This is to avoid looping when printing circular dependencies
       */
      virtual void print(std::ostream& stream,
                         std::string indent,
                         castor::ObjectSet& alreadyPrinted) const = 0;

      /**
       * Outputs this object in a human readable format
       */
      virtual void print() const = 0;

      /**
       * Get the value of m_policyObject
       * @return the value of m_policyObject
       */
      PolicyObj* policyObject() const {
        return m_policyObject;
      }

      /**
       * Set the value of m_policyObject
       * @param new_var the new value of m_policyObject
       */
      void setPolicyObject(PolicyObj* new_var) {
        m_policyObject = new_var;
      }

    private:

      PolicyObj* m_policyObject;

    }; /* end of class DbInfoPolicy */

  } /* end of namespace infoPolicy */

} /* end of namespace castor */

#endif // CASTOR_INFOPOLICY_DBINFOPOLICY_HPP
