/**** This file has been autogenerated by gencastor from Umbrello UML model ***/

/******************************************************************************
 *                      castor/infoPolicy/DbInfoMigrationPolicyCInt.cpp
 *
 * This file is part of the Castor project.
 * See http://castor.web.cern.ch/castor
 *
 * Copyright (C) 2003  CERN
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * @(#)$RCSfile$ $Revision$ $Release$ $Date$ $Author$
 *
 * 
 *
 * @author Castor Dev team, castor-dev@cern.ch
 *****************************************************************************/

// Include Files
#include "castor/IObject.hpp"
#include "castor/infoPolicy/DbInfoMigrationPolicy.hpp"
#include "castor/infoPolicy/DbInfoPolicy.hpp"
#include "castor/infoPolicy/PolicyObj.hpp"
#include "osdep.h"

extern "C" {

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_create
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_create(castor::infoPolicy::DbInfoMigrationPolicy** obj) {
    *obj = new castor::infoPolicy::DbInfoMigrationPolicy();
    return 0;
  }
  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_delete
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_delete(castor::infoPolicy::DbInfoMigrationPolicy* obj) {
    delete obj;
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_getDbInfoPolicy
  //----------------------------------------------------------------------------
  castor::infoPolicy::DbInfoPolicy* CinfoPolicy_DbInfoMigrationPolicy_getDbInfoPolicy(castor::infoPolicy::DbInfoMigrationPolicy* obj) {
    return obj;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_fromDbInfoPolicy
  //----------------------------------------------------------------------------
  castor::infoPolicy::DbInfoMigrationPolicy* CinfoPolicy_DbInfoMigrationPolicy_fromDbInfoPolicy(castor::infoPolicy::DbInfoPolicy* obj) {
    return dynamic_cast<castor::infoPolicy::DbInfoMigrationPolicy*>(obj);
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_getIObject
  //----------------------------------------------------------------------------
  castor::IObject* CinfoPolicy_DbInfoMigrationPolicy_getIObject(castor::infoPolicy::DbInfoMigrationPolicy* obj) {
    return obj;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_fromIObject
  //----------------------------------------------------------------------------
  castor::infoPolicy::DbInfoMigrationPolicy* CinfoPolicy_DbInfoMigrationPolicy_fromIObject(castor::IObject* obj) {
    return dynamic_cast<castor::infoPolicy::DbInfoMigrationPolicy*>(obj);
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_print
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_print(castor::infoPolicy::DbInfoMigrationPolicy* instance) {
    instance->print();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_TYPE
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_TYPE(int* ret) {
    *ret = castor::infoPolicy::DbInfoMigrationPolicy::TYPE();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_policyObject
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_policyObject(castor::infoPolicy::DbInfoMigrationPolicy* instance, castor::infoPolicy::PolicyObj** var) {
    *var = instance->policyObject();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_setPolicyObject
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_setPolicyObject(castor::infoPolicy::DbInfoMigrationPolicy* instance, castor::infoPolicy::PolicyObj* new_var) {
    instance->setPolicyObject(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_type
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_type(castor::infoPolicy::DbInfoMigrationPolicy* instance,
                                             int* ret) {
    *ret = instance->type();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_clone
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_clone(castor::infoPolicy::DbInfoMigrationPolicy* instance,
                                              castor::IObject** ret) {
    *ret = instance->clone();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_tapeCopyId
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_tapeCopyId(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64* var) {
    *var = instance->tapeCopyId();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_setTapeCopyId
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_setTapeCopyId(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64 new_var) {
    instance->setTapeCopyId(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_copyNb
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_copyNb(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64* var) {
    *var = instance->copyNb();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_setCopyNb
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_setCopyNb(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64 new_var) {
    instance->setCopyNb(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_castorFileName
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_castorFileName(castor::infoPolicy::DbInfoMigrationPolicy* instance, const char** var) {
    *var = instance->castorFileName().c_str();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_setCastorFileName
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_setCastorFileName(castor::infoPolicy::DbInfoMigrationPolicy* instance, const char* new_var) {
    std::string snew_var(new_var, strlen(new_var));
    instance->setCastorFileName(snew_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_fileId
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_fileId(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64* var) {
    *var = instance->fileId();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_setFileId
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_setFileId(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64 new_var) {
    instance->setFileId(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_tapePoolName
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_tapePoolName(castor::infoPolicy::DbInfoMigrationPolicy* instance, const char** var) {
    *var = instance->tapePoolName().c_str();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_setTapePoolName
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_setTapePoolName(castor::infoPolicy::DbInfoMigrationPolicy* instance, const char* new_var) {
    std::string snew_var(new_var, strlen(new_var));
    instance->setTapePoolName(snew_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_nsHost
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_nsHost(castor::infoPolicy::DbInfoMigrationPolicy* instance, const char** var) {
    *var = instance->nsHost().c_str();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_setNsHost
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_setNsHost(castor::infoPolicy::DbInfoMigrationPolicy* instance, const char* new_var) {
    std::string snew_var(new_var, strlen(new_var));
    instance->setNsHost(snew_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_tapePoolId
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_tapePoolId(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64* var) {
    *var = instance->tapePoolId();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_setTapePoolId
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_setTapePoolId(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64 new_var) {
    instance->setTapePoolId(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_castorFileSize
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_castorFileSize(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64* var) {
    *var = instance->castorFileSize();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_setCastorFileSize
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_setCastorFileSize(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64 new_var) {
    instance->setCastorFileSize(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_id
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_id(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64* var) {
    *var = instance->id();
    return 0;
  }

  //----------------------------------------------------------------------------
  // CinfoPolicy_DbInfoMigrationPolicy_setId
  //----------------------------------------------------------------------------
  int CinfoPolicy_DbInfoMigrationPolicy_setId(castor::infoPolicy::DbInfoMigrationPolicy* instance, u_signed64 new_var) {
    instance->setId(new_var);
    return 0;
  }

} // End of extern "C"
