CREATE TABLE CTA_STATISTICS(
  GID UINT32TYPE DEFAULT 0 CONSTRAINT CTA_STATISTICS_GID_NN NOT NULL,
  TIMESTAMP UINT64TYPE DEFAULT 0 CONSTRAINT CTA_STATISTICS_TS_NN NOT NULL,
  NB_MASTER_FILES UINT64TYPE NOT NULL,
  MASTER_DATA_BYTES UINT64TYPE NOT NULL,
  UPDATE_TIME UINT64TYPE NOT NULL,
  CONSTRAINT CTA_STATISTICS_GID_TS_PK PRIMARY KEY (GID, TIMESTAMP)
);