CREATE TABLE VO_STATISTICS (
  VO VARCHAR(100) CONSTRAINT VO_STATISTICS_VO_NN NOT NULL,
  NB_MASTER_FILES UINT64TYPE CONSTRAINT VO_STATISTICS_NMF_NN NOT NULL,
  MASTER_DATA_IN_BYTES UINT64TYPE CONSTRAINT VO_STATISTICS_MDIB_NN NOT NULL,
  NB_COPY_NB_1 UINT64TYPE CONSTRAINT VO_STATISTICS_NCN1_NN NOT NULL,
  NB_COPY_NB_1_IN_BYTES UINT64TYPE CONSTRAINT VO_STATISTICS_CN1IB_NN NOT NULL,
  NB_COPY_NB_GT_1 UINT64TYPE CONSTRAINT VO_STATISTICS_NCNG1_NN NOT NULL,
  NB_COPY_NB_GT_1_IN_BYTES UINT64TYPE CONSTRAINT VO_STATISTICS_NCNG1IB_NN NOT NULL,
  UPDATE_TIME UINT64TYPE CONSTRAINT VO_STATISTICS_UT_NN NOT NULL,
  CONSTRAINT VO_STATISTICS_VO_UT_PK PRIMARY KEY(VO, UPDATE_TIME)
);
CREATE TABLE FILE_STATISTICS (
  NB_MASTER_FILES UINT64TYPE CONSTRAINT FILE_STATISTICS_NMF_NN NOT NULL,
  MASTER_DATA_IN_BYTES UINT64TYPE CONSTRAINT FILE_STATISTICS_MDIB_NN NOT NULL,
  NB_COPY_NB_1 UINT64TYPE CONSTRAINT FILE_STATISTICS_NCN1_NN NOT NULL,
  NB_COPY_NB_1_IN_BYTES UINT64TYPE CONSTRAINT FILE_STATISTICS_CN1IB_NN NOT NULL,
  NB_COPY_NB_GT_1 UINT64TYPE CONSTRAINT FILE_STATISTICS_NCNG1_NN NOT NULL,
  NB_COPY_NB_GT_1_IN_BYTES UINT64TYPE CONSTRAINT FILE_STATISTICS_NCNG1IB_NN NOT NULL,
  UPDATE_TIME UINT64TYPE CONSTRAINT FILE_STATISTICS_UT_NN NOT NULL,
  CONSTRAINT FILE_STATISTICS_UT_PK PRIMARY KEY(UPDATE_TIME)
);
