# If required, the user can specify a custom image here
image:
component: maintenance
partOf: cta
nameOverride: cta-maintenance
isPrivileged: true

terminationGracePeriodSeconds: 1 # This is low on purpose as the current process has no gracefull shutdown process

conf:
  maintenance:
    secProtocol: "sss"
    secSssktPath: "/etc/cta"
    ctaMaintenanceSss: "cta-maintenance.sss.keytab"
    catalogueConfigPath: "/etc/cta/cta-catalogue.conf"
    repackMaxRequestsToExpand: 2
    tapeCacheMaxAgeSecs: 600
    retrieveQueueCacheMaxAgeSecs: 10
  general:
    instanceName: "CI"

maintenance:
  resources:
    requests:
      memory: "256Mi"
      ephemeral-storage: "1Gi"
    limits:
      memory: "4Gi"
      ephemeral-storage: "8Gi"
