# If required, the user can specify a custom image here
isPrivileged: true

conf:
  maintenance:
    secProtocol: "sss"
    secSssktPath: "/etc/cta"
    ctaMaintenanceSss: "cta-maintenance.sss.keytab"
    catalogueConfigPath: "/etc/cta/cta-catalogue.conf"
    repackMaxRequestsToExpand: 2
    tapeCacheMaxAgeSecs: 600
    retrieveQueueCacheMaxAgeSecs: 10
  general:
    instanceName: "CI"

pod:
  extraSpec:
    terminationGracePeriodSeconds: 1

extraEnv:

extraVolumes:
  volumes:
  volumeMounts:
