/**** This file has been autogenerated by gencastor from Umbrello UML model ***/

/******************************************************************************
 *                      castor/query/DiskServerDescriptionCInt.cpp
 *
 * This file is part of the Castor project.
 * See http://castor.web.cern.ch/castor
 *
 * Copyright (C) 2003  CERN
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * @(#)$RCSfile$ $Revision$ $Release$ $Date$ $Author$
 *
 * 
 *
 * @author Castor Dev team, castor-dev@cern.ch
 *****************************************************************************/

// Include Files
#include "castor/IObject.hpp"
#include "castor/query/DiskPoolQueryResponse.hpp"
#include "castor/query/DiskServerDescription.hpp"
#include "castor/query/FileSystemDescription.hpp"
#include "osdep.h"
#include <vector>

extern "C" {

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_create
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_create(castor::query::DiskServerDescription** obj) {
    *obj = new castor::query::DiskServerDescription();
    return 0;
  }
  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_delete
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_delete(castor::query::DiskServerDescription* obj) {
    delete obj;
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_getIObject
  //----------------------------------------------------------------------------
  castor::IObject* Cquery_DiskServerDescription_getIObject(castor::query::DiskServerDescription* obj) {
    return obj;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_fromIObject
  //----------------------------------------------------------------------------
  castor::query::DiskServerDescription* Cquery_DiskServerDescription_fromIObject(castor::IObject* obj) {
    return dynamic_cast<castor::query::DiskServerDescription*>(obj);
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_print
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_print(castor::query::DiskServerDescription* instance) {
    instance->print();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_TYPE
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_TYPE(int* ret) {
    *ret = castor::query::DiskServerDescription::TYPE();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_type
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_type(castor::query::DiskServerDescription* instance,
                                        int* ret) {
    *ret = instance->type();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_clone
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_clone(castor::query::DiskServerDescription* instance,
                                         castor::IObject** ret) {
    *ret = instance->clone();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_name
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_name(castor::query::DiskServerDescription* instance, const char** var) {
    *var = instance->name().c_str();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_setName
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_setName(castor::query::DiskServerDescription* instance, const char* new_var) {
    std::string snew_var(new_var, strlen(new_var));
    instance->setName(snew_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_status
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_status(castor::query::DiskServerDescription* instance, int* var) {
    *var = instance->status();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_setStatus
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_setStatus(castor::query::DiskServerDescription* instance, int new_var) {
    instance->setStatus(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_freeSpace
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_freeSpace(castor::query::DiskServerDescription* instance, u_signed64* var) {
    *var = instance->freeSpace();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_setFreeSpace
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_setFreeSpace(castor::query::DiskServerDescription* instance, u_signed64 new_var) {
    instance->setFreeSpace(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_totalSpace
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_totalSpace(castor::query::DiskServerDescription* instance, u_signed64* var) {
    *var = instance->totalSpace();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_setTotalSpace
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_setTotalSpace(castor::query::DiskServerDescription* instance, u_signed64 new_var) {
    instance->setTotalSpace(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_id
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_id(castor::query::DiskServerDescription* instance, u_signed64* var) {
    *var = instance->id();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_setId
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_setId(castor::query::DiskServerDescription* instance, u_signed64 new_var) {
    instance->setId(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_query
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_query(castor::query::DiskServerDescription* instance, castor::query::DiskPoolQueryResponse** var) {
    *var = instance->query();
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_setQuery
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_setQuery(castor::query::DiskServerDescription* instance, castor::query::DiskPoolQueryResponse* new_var) {
    instance->setQuery(new_var);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_addFileSystems
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_addFileSystems(castor::query::DiskServerDescription* instance, castor::query::FileSystemDescription* obj) {
    instance->addFileSystems(obj);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_removeFileSystems
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_removeFileSystems(castor::query::DiskServerDescription* instance, castor::query::FileSystemDescription* obj) {
    instance->removeFileSystems(obj);
    return 0;
  }

  //----------------------------------------------------------------------------
  // Cquery_DiskServerDescription_fileSystems
  //----------------------------------------------------------------------------
  int Cquery_DiskServerDescription_fileSystems(castor::query::DiskServerDescription* instance, castor::query::FileSystemDescription*** var, int* len) {
    std::vector<castor::query::FileSystemDescription*>& result = instance->fileSystems();
    *len = result.size();
    *var = (castor::query::FileSystemDescription**) malloc((*len) * sizeof(castor::query::FileSystemDescription*));
    for (int i = 0; i < *len; i++) {
      (*var)[i] = result[i];
    }
    return 0;
  }

} // End of extern "C"
