/*********************************************************************************/
/* File including the constants to represent the DLF Messages for the new */
/*******************************************************************************/

#ifndef TAPEGATEWAY_DLF_MESSAGES_HPP
#define TAPEGATEWAY_DLF_MESSAGES_HPP 1


namespace castor {
  namespace tape {
    namespace tapegateway{

      enum DlfCodes{

	DAEMON_START = 1,
	DAEMON_STOP = 2,
	NO_RETRY_POLICY_FOUND = 3,
	FATAL_ERROR  = 4, 

	PRODUCER_GETTING_TAPES = 5,
	PRODUCER_NO_TAPE = 6,
	PRODUCER_CANNOT_UPDATE_DB = 7,
	PRODUCER_QUERYING_VMGR = 8,
	PRODUCER_VMGR_ERROR = 9,
	PRODUCER_SUBMITTING_VDQM = 10,
	PRODUCER_VDQM_ERROR = 11,

	CHECKER_GETTING_TAPES = 12,
        CHECKER_NO_TAPE = 13,
	CHECKER_QUERYING_VDQM = 14,
	CHECKER_LOST_VDQM_REQUEST = 15,
	CHECKER_CANNOT_UPDATE_DB = 16,
	CHECKER_RELEASING_UNUSED_TAPE = 17,
	CHECKER_VMGR_ERROR = 18,

	LINKER_GETTING_STREAMS = 19,
	LINKER_NO_STREAM = 20,
	LINKER_QUERYING_VMGR = 21,
	LINKER_LINKING_TAPE_STREAM = 22,
	LINKER_CANNOT_UPDATE_DB = 23,
	LINKER_RELEASED_BUSY_TAPE = 24,
	LINKER_NO_TAPE_AVAILABLE = 25,	


	MIG_ERROR_GETTING_FILES = 26,
	MIG_ERROR_NO_FILE = 27,
	MIG_ERROR_RETRY = 28,
	MIG_ERROR_FAILED = 29,
	MIG_ERROR_RETRY_BY_DEFAULT = 30,
	MIG_ERROR_CANNOT_UPDATE_DB = 31,
	

	REC_ERROR_GETTING_FILES = 32,
	REC_ERROR_NO_FILE = 33,
	REC_ERROR_RETRY = 34,
	REC_ERROR_FAILED = 35,
	REC_ERROR_RETRY_BY_DEFAULT = 36,
	REC_ERROR_CANNOT_UPDATE_DB = 37,
	
	WORKER_MESSAGE_RECEIVED = 38,
	WORKER_UNKNOWN_CLIENT = 39,
	WORKER_INVALID_REQUEST =  40,
	WORKER_INVALID_CAST = 41,
	WORKER_DISPATCHING = 42,
	WORKER_RESPONDING = 43,
	WORKER_CANNOT_RESPOND  = 44,
	WORKER_CANNOT_RECEIVE = 45,
	WORKER_UNKNOWN_EXCEPTION = 46,
	 
	WORKER_VOLUME_REQUESTED = 47,
	WORKER_GETTING_VOLUME = 48,
	WORKER_NO_VOLUME = 49,
	WORKER_NO_FILE = 50,
	WORKER_VOLUME_FOUND = 51,

	WORKER_RECALL_NOTIFIED = 52,
	WORKER_RECALL_GET_DB_INFO = 53, 
	WORKER_RECALL_FILE_NOT_FOUND = 54,
	WORKER_RECALL_NS_CHECK = 55,
	WORKER_RECALL_NS_FAILURE = 56,
	WORKER_RECALL_DB_UPDATE = 57,
	WORKER_RECALL_CANNOT_UPDATE_DB = 58,
	WORKER_RECALL_CHECK_FILE_SIZE = 59,
	WORKER_RECALL_WRONG_FILE_SIZE= 60, 
	WORKER_RECALL_COMPLETED_UPDATE_DB = 61,
	
	
	WORKER_MIGRATION_NOTIFIED = 62,
	WORKER_MIGRATION_GET_DB_INFO = 63,
	WORKER_MIGRATION_FILE_NOT_FOUND = 64,
	WORKER_MIGRATION_VMGR_UPDATE = 65,
	WORKER_MIGRATION_NS_UPDATE = 66,
	WORKER_REPACK_NS_UPDATE = 67,
	WORKER_MIGRATION_NS_FAILURE = 68,
	WORKER_MIGRATION_VMGR_FAILURE = 69,
	WORKER_MIGRATION_DB_UPDATE = 70,
	WORKER_MIGRATION_CANNOT_UPDATE_DB = 71,

	WORKER_RECALL_REQUESTED = 72,
	WORKER_RECALL_RETRIEVED = 73,
	WORKER_RECALL_RETRIEVING_DB_ERROR = 74,
	WORKER_NO_FILE_TO_RECALL = 75,
	
	
	WORKER_MIGRATION_REQUESTED = 76,
	WORKER_MIGRATION_RETRIEVED = 77,
	WORKER_MIGRATION_RETRIEVING_DB_ERROR = 78,
	WORKER_NO_FILE_TO_MIGRATE = 79,

	WORKER_END_NOTIFICATION = 80,
	WORKER_END_DB_UPDATE = 81,
	WORKER_END_DB_ERROR = 82,
	WORKER_END_RELEASE_TAPE = 83,
	WORKER_CANNOT_RELEASE_TAPE = 84,
	
	WORKER_FILE_ERROR_NOTIFIED = 85,
	WORKER_FILE_ERROR_DB_UPDATE = 86,
	WORKER_FILE_ERROR_CANNOT_UPDATE_DB = 87,
	WORKER_TAPE_MAKED_FULL = 88,
	WORKER_CANNOT_MARK_TAPE_FULL = 89,

	WORKER_FAIL_NOTIFICATION = 90,
	WORKER_FAIL_DB_UPDATE = 91,
	WORKER_FAIL_DB_ERROR = 92,
	WORKER_FAIL_RELEASE_TAPE = 93,

	ORA_FILE_TO_MIGRATE_NS_ERROR = 94,
	ORA_DB_ERROR = 95,
	ORA_IMPOSSIBLE_TO_SEND_RMMASTER_REPORT = 96,
	ORA_FILE_TO_RECALL_NS_ERROR =97

      };
    }// end namespace tapegateway
  }// end namespace tape
}// end namespace castor

#endif

