.TH TAPEGATEWAYD "$Date: 2009/08/18 09:42:55 $" CASTOR "TapeGateway"
.SH NAME
tapegatewayd \- tape gateway daemon
.SH SYNOPSIS
.B tapegateway
[
.BI -f
]
.SH DESCRIPTION
.B tapegatewayd
is the CASTOR component which handles the interface between the disk cache and the tape backend, providing support for the new generation tape format.
This component is a multi-threaded application, database centric, which uses the CASTOR framework.
It submits drive requests to VDQM when migrations and/or recalls are required.
The migrations/recalls are triggered thanks to the interaction of different daemons ( stager, mighunter, rechandler), each of them is in charge of different db transactions.
The tapegateway interacts with the VDQM using messages over TCP/IP.
The tapegateway is also sending report to RmMaster over TCP/IP to monitor the load on the diskservers.
The comunication between tapegateway and the several aggregators, which are running on the tape servers, is a based on TCP/IP messages too.
The tapegatewayd relies on the DLF logging interface. Logs can be accessed by web interface or locally on the machine using the /var/log/castor/tapegatewayd.log log file.
 
.SH OPTIONS
.BI \-f
To run in foreground

There are several parameters that can be provided in the : 
.B /etc/castor/castor.conf 

There are four parameters used to specify the location of the files, where all the policy functions are declared, and the name of them.
These policies are used by the system to tune the number of times that failed recalls/migrations should be retried.
  
i.e. :

.B Policy  RetryMigration  /etc/castor/policies/migrationRetry.py

.B Policy  RetryMigrationFunction migrationRetry

.B Policy  RetryRecall     /etc/castor/policies/recallRetry.py

.B Policy  RetryRecallFunction     recallRetry

If RetryMigration and/or RetryMigrationFunction are not provided, all the failed  migrations will be always retried.
If RetryMigrationRecall and/or RetryRecallFunction are not provided, all the failed  recalls will be always retried.

There are also paramenter to change the max/min number of threads for the thread pool in charge to serve aggregator's requests.

i.e. :

.B TAPEGATEWAY MINWORKERTHREADS    5
.B TAPEGATEWAY MAXWORKERTHREADS    240

If these parameters are not provided the default ones are used: 5 as minimum, 240 as maximum.

The port used for the comunication between the aggregator and the tapegateway is also defined in this file.

.B TAPEGATEWAY     PORT    62801

If the port is not provided, 62801 is used as default.

.SH EXAMPLE
.fi
# tapegatewayd
.fi
# tapegatewayd  -f

.SH EXIT STATUS
This program returns 0 if the operation was successful or > 0 if the operation
failed.

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
