# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

[tests]

krb5_realm = "TEST.CTA"

[tests.stress]

# For the actual stress test we currently have 40 directories with 50.000 files each
# mhvtl is mounted in-memory, so we keep the file size small and easily compressible (unique string + zero padding)
num_dirs = 10
num_files_per_dir = 5000
# file size in bytes
file_size = 512
# number of parallel processes to be used for archival
io_threads = 40
# Files per batch when enqueueing work (beneficial for large file counts as it should reduce queue contention)
batch_size = 200
check_copy_interval_sec = 20
check_archive_interval_sec = 10

[tests.stress.prequeue]

# If true, put drives down before archiving and only put them up after num_files_to_put_drives_up files are created.
# This prevents drives from outpacing the queueing capabilities of EOS.
enabled = false
num_files_to_put_drives_up = 1000000
# timeout in seconds
timeout_to_put_drives_up_sec = 3600
# how often to count number of files when prequeueing
check_interval_sec = 300
