.TH DELETETAPEPOOL 1 "2011" CASTOR "stager catalogue administrative commands"
.SH NAME
deletetapepool \- deletes existing tape pools from the stager catalogue

.SH SYNOPSIS
.B deletetapepool
[
.BI -h
]
.BI <tapePoolName>
[:...]

.SH DESCRIPTION
.B deletetapepool
deletes existing tape pools from the CASTOR stager catalog
.LP
.BI \-h,\ \-\-help
Get usage information
.TP
.BI <tapePoolName>
name of tape pools to delete. Several names can be given, colon separated

.SH EXAMPLES
.nf
.ft CW
# printtapepool -a
        NAME     MIGRSELECTPOLICY SVCCLASSES       ID
-----------------------------------------------------
stager_dev01 defaultMigrSelPolicy    default        6
testtapepool           testPolicy          - 93545831
 newtapepool defaultMigrSelPolicy          - 93543828

# deletetapepool newtapepool
successfully dropped the following tape pools : newtapepool

# printtapepool -a
        NAME     MIGRSELECTPOLICY SVCCLASSES       ID
-----------------------------------------------------
stager_dev01 defaultMigrSelPolicy    default        6
testtapepool           testPolicy          - 93545831

# deletetapepool newtapepool:testtapepool
successfully dropped the following tape pools : testtapepool
WARNING : some tape pool(s) did not exist : newtapepool

# printtapepool -a
        NAME     MIGRSELECTPOLICY SVCCLASSES ID
-----------------------------------------------
stager_dev01 defaultMigrSelPolicy    default  6

# deletetapepool stager_dev01
TapePools cannot be dropped when used by some service classes and
  - tape pool stager_dev01 is in use by service class default
You may want to use modifysvcclass to correct this

.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from castor.conf.

.SH SEE ALSO
.BR entertapepool,
.BR modifytapepool,
.BR printtapepool,
.BR deletediskpool,
.BR deletesvcclass,
.BR deletefileclass,
.BR adminMultiInstance

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
