#!/usr/bin/python
#/******************************************************************************
# *                      deletemigrationroute
# *
# * This file is part of the Castor project.
# * See http://castor.web.cern.ch/castor
# *
# * Copyright (C) 2003  CERN
# * This program is free software; you can redistribute it and/or
# * modify it under the terms of the GNU General Public License
# * as published by the Free Software Foundation; either version 2
# * of the License, or (at your option) any later version.
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# *
# * @author Castor Dev team, castor-dev@cern.ch
# *****************************************************************************/

'''command line deleting the given migration route(s)'''

import sys
import getopt
import castor_tools

# usage function
def usage(exitCode):
    '''prints usage'''
    print 'Usage : ' + sys.argv[0] + ' [-h|--help] <fileClassName> [...]'
    sys.exit(exitCode)

# first parse the options
try:
    options, args = getopt.getopt(sys.argv[1:], 'hv', ['help', 'verbose'])
except Exception, e:
    print e
    usage(1)
verbose = False
for f, v in options:
    if f == '-h' or f == '--help':
        usage(0)
    elif f == '-v' or f == '--verbose':
        verbose = True
    else:
        print "unknown option : " + f
        usage(1)

# Deal with arguments
if len(args) != 0:
    fileclasses = set(args)
else:
    print "Missing arguments"
    usage(1)

try:
    # connect to stager
    stconn = castor_tools.connectToStager()
    stcur = stconn.cursor()
    # check file class existences
    nonexistingFileClasses = []
    existingRoutes = []
    for fileClassName in fileclasses:
        stcur.execute("SELECT id FROM FileClass WHERE name=:name", name=fileClassName)
        rows = stcur.fetchall()
        if len(rows) == 0:
            nonexistingFileClasses.append(fileClassName)
            continue
        fileClassId = int(rows[0][0])
        existingRoutes.append(fileClassName)
        # drop route(s)
        stcur.execute('DELETE FROM MigrationRouting WHERE fileClass=:fileClass',
                      fileClass=fileClassId)
    # commit work
    stconn.commit()
    # Inform user
    if existingRoutes:
        print 'successfully dropped the route(s) for the following FileClass(es) :'
        for fileClassName in existingRoutes:
            print '  ', fileClassName
    if nonexistingFileClasses:
        print 'WARNING : the file class(es) of the following rule(s) did not exist :'
        for fileClassName in nonexistingFileClasses:
            print '  ', fileClassName
    # close DB connections
    try:
        castor_tools.disconnectDB(stconn)
    except Exception:
        pass
except Exception, e:
    print e
    if verbose:
        import traceback
        traceback.print_exc()
    sys.exit(-1)
