.TH DELETEPRIORITY 1 "$Date: 2008/06/27 14:05:39 $" CASTOR "Delete entries from the priority map table used by VDQM"
.SH NAME
deletePriority
.SH SYNOPSIS
.B deletePriority
[
.BI -u 
.BID uid
]
[
.BI -g 
.BID gid
]
[
.BI -h 
]
.SH DESCRIPTION
.B deletePriority
deletes entries from the Priority Map Table.

.SH EXAMPLES
.fi

deletePriority -u 444, to delete all the entries associated to the user 

deletePriority -g 999, to delete all the entries associated to the group 

deletePriority  -u 444 -g 999, to delete the entry with uid=444 and gid=999

.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from /etc/castor/ORASTAGERCONFIG

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
