#!/usr/bin/python
#/******************************************************************************
# *                      entersvcclass
# *
# * This file is part of the Castor project.
# * See http://castor.web.cern.ch/castor
# *
# * Copyright (C) 2003  CERN
# * This program is free software; you can redistribute it and/or
# * modify it under the terms of the GNU General Public License
# * as published by the Free Software Foundation; either version 2
# * of the License, or (at your option) any later version.
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# *
# * @author castor dev team
# *****************************************************************************/

'''allows to enter a new service class into the castor stager'''

import sys, re, os, pwd
import getopt
import castor_tools

# usage function
def usage(exitCode):
    '''prints usage'''
    print 'Usage : ' + sys.argv[0] + ' [-h|--help] ' + \
          '[--defaultfilesize <defaultFileSize>] [--maxreplicanb <maxReplicaNb>] ' + \
          '[--failjobswhennospace <[yes|no]>] [--disk1behavior <[yes|no]>] ' + \
          '[--forcedfileclass <forcedFileClass>] [--replicateonclose <[yes|no]>] ' + \
          '--gcpolicy <gcPolicyName> [--recallerpolicy <recallerPolicy>] ' + \
          '[--diskpools <diskPoolName>:[...]] <svcClassName>'
    sys.exit(exitCode)

def parsePositiveInt(name, svalue):
    '''parses a positive int value and exits with proper error message in case the value does not fit'''
    try:
        value = int(svalue)
        if value < 0:
            raise ValueError
        return value
    except ValueError:
        print 'Invalid %s %s' % (name, svalue)
        usage(1)

def parsePositiveNonNullInt(name, svalue):
    '''parses a positive, non null int value and exits with proper error message in case the value does not fit'''
    value = parsePositiveInt(name, svalue)
    if value == 0:
        print '%s cannot be set to 0' % name
        usage(1)
    return value

def parseBool(name, svalue):
    '''parses a boolean value and exits with proper error message in case the value does not fit'''
    validTrues = ['true', '1', 't', 'y', 'yes']
    validFalses = ['false', '0', 'f', 'n', 'no']
    if svalue.lower() in validTrues:
        return True
    elif svalue.lower() in validFalses:
        return False
    else:
        print 'Invalid %s %s' % (name, svalue)
        print 'Note that accepted booleans are %s and %s' % (','.join(validTrues), ','.join(validFalses))
        usage(1)

def parseDataAmount(name, svalue):
    '''parses a value describing an amount of data. Exits with proper error message in case the value does not fit'''
    try:
        exts = {'K' : 1000, 'M' : 1000*1000, 'G' : 1000*1000*1000, 'T' : 1000*1000*1000*1000,
                'Ki' : 1024, 'Mi' : 1024*1024, 'Gi' : 1024*1024*1024, 'Ti' : 1024*1024*1024*1024}
        regexp = re.compile('^(?P<nb>\d+)(?P<ext>(?:[KMGT]i?)?)B?$')
        m = regexp.match(svalue)
        if not m:
            raise ValueError
        value = int(m.group('nb'))
        if m.group('ext'):
            value *= exts[m.group('ext')]
        return value
    except ValueError:
        print 'Invalid %s %s' % (name, svalue)
        usage(1)

# first parse the options
try:
    options, args = getopt.getopt(sys.argv[1:], 'hv',
                                  ['help', 'verbose', 'defaultfilesize=', 'maxreplicanb=',
                                   'failjobswhennospace=', 'disk1behavior=', 'forcedfileclass=',
                                   'replicateonclose=', 'gcpolicy=', 'recallerpolicy=', 'diskpools='])
except Exception, e:
    print e
    usage(1)
verbose = False
defaultfilesize = 2147483648 # 2GiB
maxreplicanb = 1
failjobswhennospace = True
disk1behavior = False
forcedfileclass = None
replicateonclose = False
gcpolicy = None
recallerpolicy = None
diskpools = []
for f, v in options:
    if f == '-h' or f == '--help':
        usage(0)
    elif f == '-v' or f == '--verbose':
        verbose = True
    elif f == '--defaultfilesize':
        defaultfilesize = parseDataAmount('defaultfilesize', v)
    elif f == '--maxreplicanb':
        maxreplicanb = parsePositiveNonNullInt('maxreplicanb', v)
    elif f == '--failjobswhennospace':
        failjobswhennospace = parseBool('failjobswhennospace', v)
    elif f == '--disk1behavior':
        disk1behavior = parseBool('disk1behavior', v)
    elif f == '--forcedfileclass':
        forcedfileclass = v
    elif f == '--replicateonclose':
        replicateonclose = parseBool('replicateonclose', v)
    elif f == '--gcpolicy':
        gcpolicy = v
    elif f == '--recallerpolicy':
        recallerpolicy = v
    elif f == '--diskpools':
        diskpools = set(v.split(':'))
    else:
        print "unknown option : " + f
        usage(1)

# Deal with arguments
if len(args) == 0:
    print "Missing arguments"
    usage(1)
elif len(args) > 1:
    print "Too many arguments"
    usage(1)
else:
    svcclassname = args[0]

# check some arguments
if gcpolicy == None:
    if disk1behavior:
        gcPolicy = 'default'
    else:
        print "gcpolicy argument is mandatory but is missing. Did you mean 'default' ?"
        usage(1)

try:
    # connect to stager
    stconn = castor_tools.connectToStager()
    stcur = stconn.cursor()
    # check that the service class does not exist
    stcur.execute('SELECT id FROM SvcClass WHERE name=:name', name=svcclassname)
    rows = stcur.fetchall()
    if len(rows) != 0:
        print 'SvcClass %s already exists in the stager DB' % svcclassname
        print 'Giving up'
        sys.exit(1)
    # check that the service class exists
    stcur.execute('SELECT name FROM GcPolicy WHERE name=:name', name=gcpolicy)
    rows = stcur.fetchall()
    if len(rows) == 0:
        print 'GcPolicy %s does not exist in the stager DB' % gcpolicy
        sys.exit(1)
    # Get DiskPool info (and check existence)
    if diskpools:
        stcur.execute("SELECT name, id FROM DiskPool WHERE name IN ('" + "', '".join(diskpools) + "')")
        rows = stcur.fetchall()
        existingdiskpools = set([row[0] for row in rows])
        nonexistingdiskpools = diskpools - existingdiskpools
        if nonexistingdiskpools:
            print 'Invalid or non existent diskpool(s) given : %s' % (', '.join(nonexistingdiskpools))
            sys.exit(1)
        diskpools = [row[1] for row in rows]
    else:
        # Oracle needs at least one element...
        diskpools = [-1]
    # check that the forced file class does exist, and retrieve its id
    if forcedfileclass:
        stcur.execute('SELECT id FROM FileClass WHERE name=:name', name=forcedfileclass)
        rows = stcur.fetchall()
        if len(rows) == 0:
            print 'Invalid or non existent FileClass %s' % forcedfileclass
            print 'Giving up'
            sys.exit(1)
        else:
            forcedfileclass = rows[0][0]
    else:
        forcedfileclass = 0
    # get info on user running this command
    lasteditor = pwd.getpwuid(os.getuid())[0]
    # insert new SvcClass
    insertFCSQL = '''
    DECLARE
      scId NUMBER;
      diskPoolIds castor."cnumList" := :diskPoolIds;
    BEGIN
      INSERT INTO SvcClass (name, defaultFileSize, maxReplicaNb,
                            recallerPolicy, gcPolicy, disk1Behavior, replicateOnClose,
                            failJobsWhenNoSpace, id, forcedFileClass, lastEditor, lastEditionTime)
             VALUES (:name, :defaultFileSize, :maxReplicaNb,
                     :recallerPolicy, :gcPolicy, :disk1Behavior, :replicateOnClose,
                     :failJobsWhenNoSpace, ids_seq.nextval, :forcedFileClass, :lastEditor, gettime())
             RETURNING id INTO scId;
      IF diskPoolIds.COUNT != 1 OR diskPoolIds(1) != -1 THEN
        FORALL i IN diskPoolIds.FIRST .. diskPoolIds.LAST
          INSERT INTO DiskPool2SvcClass (parent, child) VALUES (diskPoolIds(i), scId);
      END IF;
    END;'''
    stcur.execute(insertFCSQL, name=svcclassname, defaultFileSize=defaultfilesize,
                  maxReplicaNb=maxreplicanb, recallerPolicy=recallerpolicy,
                  gcPolicy=gcpolicy, disk1Behavior=disk1behavior,
                  replicateOnClose=replicateonclose, failJobsWhenNoSpace=failjobswhennospace,
                  forcedFileClass=forcedfileclass, diskPoolIds=diskpools,
                  lastEditor=lasteditor)
    # commit insertion and tell user
    stconn.commit()
    print 'inserted service class %s successfully' % svcclassname
    # close DB connections
    try:
        castor_tools.disconnectDB(stconn)
    except Exception:
        pass
except Exception, e:
    print e
    if verbose:
        import traceback
        traceback.print_exc()
    sys.exit(-1)
