.\" @(#)$RCSfile: enterPriority.man,v $ $Revision: 1.1 $ $Date: 2008/05/28 08:07:11 $ CERN IT/ADC Olof Barring
.\" Copyright (C) 2005 by CERN IT/ADC
.\" All rights reserved
.\"
.TH ENTERPRIORITY 1 "$Date: 2008/05/28 08:07:11 $" CASTOR "set the priority for a specific uid-gid couple"
.SH NAME
enterPriority
.SH SYNOPSIS
.B enterPriority
.BI -u 
.BI uid 
.BI -g 
.BI gid 
.BI -p 
.BI priority
[
.BI -h 
]
.SH DESCRIPTION
.B enterPriority 
maps a uid-gid to a specific priority, which will be used by vdqm.

uid, gid and priority must be positive intergers.

.SH EXAMPLES
.fi
enterPriority -u 333 -g 333 -p 6
.fi

.SH NOTES
This command requires database client access to the stager catalogue.

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
