.TH LISTPRIORITY 1 "$Date: 2008/08/14 14:30:36 $" CASTOR "List the entries in the priority map table used by VDQM"
.SH NAME
listPriority
.SH SYNOPSIS
.B listPriority
[
.BI -u/--uid 
.BI uid
]
[
.BI -g/--gid 
.BI gid
]
[
.BI -p/--priority 
.BI priority
]
[
.BI -h 
]

.B listPriority
[
.BI -U/--user
.BI username
]
[
.BI -G/--group 
.BI groupname
]
[
.BI -p/--priority 
.BI priority
]
[
.BI -h 
]

.SH DESCRIPTION
.B listPriority
lists the entries from the Priority Map Table, depending the option given.

.SH EXAMPLES
.fi

listPriority --user name --group group 

listPriority -U name -G group

listPriority --user name

listPriority -u 444, to list all the entries associated to the user 

listPriority -g 999, to list all the entries associated to the group

listPriority -p 5, to list all the entries associated to a specific priority
 
.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from /etc/castor/ORASTAGERCONFIG.

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
