.\" @(#)$RCSfile: listSvcClass.man,v $ $Revision: 1.5 $ $Date: 2005/07/29 15:35:46 $ CERN IT/ADC Olof Barring
.\" Copyright (C) 2005 by CERN IT/ADC
.\" All rights reserved
.\"
.TH LISTSVCCLASS 1 "$Date: 2005/07/29 15:35:46 $" CASTOR "list existing service classes in the stager"
.SH NAME
listSvcClass
.SH SYNOPSIS
.B listSvcClass
[
.BI -h, 
.BI --help
]
.SH DESCRIPTION
.B listSvcClass
list the services classes existing in the stager
.LP
.BI \-h,\ \-\-help
Get usage information
.SH EXAMPLES
.fi
# listSvcClass
.fi
default
.fi
wan
.fi
phedex
.ft
.fi
.SH NOTES
This command connects directly to the stager database through
the perl DBI interface to ORACLE. Thus it can only run on
a machine providing it.
Configuration for the database access is taken from castor.conf.
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
