.\" @(#)$RCSfile: printFileClass.man,v $ $Revision: 1.2 $ $Date: 2006/04/24 16:13:40 $ CERN IT/ADC Olof Barring
.\" Copyright (C) 2005 by CERN IT/ADC
.\" All rights reserved
.\"
.TH PRINTFILECLASS 1 "$Date: 2006/04/24 16:13:40 $" CASTOR "Prints out a given file class"
.SH NAME
printFileClass
.SH SYNOPSIS
.B printFileClass
[
.BI -h, 
.BI --help
]
fileClassName
.SH DESCRIPTION
.B printFileClass
prints out the file class
.LP
.BI \-h,\ \-\-help
Get usage information
.LP
.BI fileClassName
the name of the file class to print out
.SH EXAMPLES
.fi
.BI #\ printFileClass\ test
.fi
[# FileClass #]
.fi
name : test
.fi
minFileSize : 0
.fi
maxFileSize : 0
.fi
nbCopies : 1
.fi
id : 1
.fi
.ft
.fi

.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from castor.conf.

.SH SEE ALSO
.BR adminMultiInstance(1castor)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
