.TH PRINTSVCCLASS 1 "2011" CASTOR "Prints out the given service class(es)"
.SH NAME
printsvcclass
.SH SYNOPSIS
.B printsvcclass
[
.BI -h
]
[
.BI -a
]
[
.BI <svcClassName>
[:...]
]

.SH DESCRIPTION
.B printsvcclass
prints out definitions of the given services classes
.LP
.BI \-h,\ \-\-help
Get usage information
.TP
.BI \-a,\ \-\-all
List all service classes
.TP
.BI <svcClassName>
name of service classes to list. Several names can be given, colon separated. Note that
no name should be given if -a/--all is used.

.SH EXAMPLES
.nf
.ft CW
# printsvcclass -a
    NAME DEFAULTFILESIZE NBDRIVES FAILJOBSWHENNOSPACE MAXREPLICANB FORCEDFILECLASS REPLICATEONCLOSE DISK1BEHAVIOR        STREAMPOLICY GCPOLICY         MIGRATORPOLICY RECALLERPOLICY DISKPOOLS    TAPEPOOLS           ID
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
diskonly        10485760        0                True            1            temp            False          True                   -        - defaultMigrationPolicy              -     extra            -           10
     dev        10485760        0                True            1               -            False         False                   -        - defaultMigrationPolicy              -     extra            -            8
 default        10485760        1                True            1               -            False         False defaultStreamPolicy        - defaultMigrationPolicy              -   default stager_dev01            5

# printsvcclass dev:nonexisting
NAME DEFAULTFILESIZE NBDRIVES FAILJOBSWHENNOSPACE MAXREPLICANB FORCEDFILECLASS REPLICATEONCLOSE DISK1BEHAVIOR STREAMPOLICY GCPOLICY         MIGRATORPOLICY RECALLERPOLICY DISKPOOLS TAPEPOOLS           ID
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 dev        10485760        0                True            1               -            False         False            -        - defaultMigrationPolicy              -     extra         -            8
WARNING : the following service classes do not exist : nonexisting

.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from castor.conf.

.SH SEE ALSO
.BR entersvcclass,
.BR modifysvcclass,
.BR deletesvcclass,
.BR printtapepool,
.BR printdiskpool,
.BR printfileclass,
.BR adminMultiInstance

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
