.TH PRINTTAPEPOOL 1 "2011" CASTOR "Prints out the given tape pool(s)"
.SH NAME
printtapepool
.SH SYNOPSIS
.B printtapepool
[
.BI -h
]
[
.BI -a
]
[
.BI <tapePoolName>
[:...]
]

.SH DESCRIPTION
.B printtapepool
prints out definitions of the given tape pools
.LP
.BI \-h,\ \-\-help
Get usage information
.TP
.BI \-a,\ \-\-all
List all tape pools found in the stager catalog.
.TP
.BI <TapePoolName>
name of tape pools to list. Several names can be given, colon separated. Note that
no name should be given if -a/--all is used.

.SH EXAMPLES
.nf
.ft CW
# printtapepool -a
        NAME     MIGRSELECTPOLICY SVCCLASSES ID
-----------------------------------------------
stager_dev01 defaultMigrSelPolicy    default  6
stager_dev02                    -    default  7

# printtapepool stager_dev01:nonexisting
        NAME     MIGRSELECTPOLICY SVCCLASSES ID
-----------------------------------------------
stager_dev01 defaultMigrSelPolicy    default  6
WARNING : the following tape pools do not exist : nonexisting

.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from castor.conf.

.SH SEE ALSO
.BR entertapepool,
.BR modifytapepool,
.BR deletetapepool,
.BR printdiskpool,
.BR printsvcclass,
.BR printfileclass,
.BR adminMultiInstance

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
