.TH PRINTDISKPOOL 1 "2011" CASTOR "Prints out the given disk pool(s)"
.SH NAME
printdiskpool
.SH SYNOPSIS
.B printdiskpool
[
.BI -h
]
<diskPoolName>
[...]

.SH DESCRIPTION
.B printdiskpool
prints out definitions of disk pools
.LP
.BI \-h,\ \-\-help
Get usage information
.TP
.BI <DiskPoolName>
when disk pool names are given, only the definitions of the listed disk pool are printed.
If no disk pool name is given, all disk pool definitions are printed.

.SH EXAMPLES
.nf
.ft CW
# printdiskpool
   NAME NSFILESYSTEMS    SVCCLASSES ID
--------------------------------------
  extra            10 dev, diskonly  9
default            10       default  7

# printdiskpool extra nonexisting
 NAME NSFILESYSTEMS    SVCCLASSES ID
------------------------------------
extra            10 dev, diskonly  9
WARNING : the following disk pools do not exist : nonexisting

.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from castor.conf.

.SH SEE ALSO
.BR enterdiskpool
.BR deletediskpool
.BR printsvcclass
.BR printdiskserver
.BR adminMultiInstance

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
