.TH "PRINTRECALLSTATUS" "8" "2.1.14" "CASTOR" "Castor stager tools"
.SH "NAME"
printrecallstatus \- Prints the pending recall statistics by tape pool
.SH "SYNOPSIS"
[CASTOR_STAGER=<stager_name>]
.B 
printrecallstatus
[
.BI \-h
]

.SH "DESCRIPTION"
.B printrecallstatus
prints out pending recall statistics, by tapepool. For each tape pool, 3 totals are available: the total of data (tapes, files and bytes) to be recalled, the total submitted to VDQM (currently mounted or not) and the total for tapes currently mounted.
.LP 
.BI \-h,\ \-\-help
Get usage information
.TP 

.SH "EXAMPLES"
.nf 
.ft CW
# printrecallstatus
   TAPEPOOL FILES FILES_QUEUED FILES_RECALLING TOTAL_SIZE SIZE_QUEUED SIZE_RECALLING TAPES TAPES_QUEUED TAPES_RECALLING MIN_AGE   MAX_AGE
-----------------------------------------------------------------------------------------------------------------------------------------
   cms_user   712          634             634     987GiB      897GiB         897GiB    38           12              12      0s 3h42mn15s
 r_cms_user    39           39              39      52GiB       52GiB          52GiB     2            2               2      0s  1h3mn18s
cms_prod_08     3            0               0       7GiB          0B             0B     3            0               0 27mn35s  3h8mn45s
 cms_raw_08     3            0               0    3875MiB          0B             0B     3            0               0  2mn15s    35mn4s

.SH "NOTES"
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from ORASTAGERCONFIG.

.SH "SEE ALSO"
.BR printmigrationstatus
.BR printrecallfilestatus
.BR printrecalltapequeue
.BR printrecalluserqueue
.SH "AUTHOR"
\fBCASTOR\fP Team <castor.support@cern.ch>
