.TH PRINTDISKPOOL 1 "2011" CASTOR "Prints out the given disk pool(s)"
.SH NAME
printdiskpool
.SH SYNOPSIS
.B printdiskpool
[
.BI -h
]
[
.BI -a
]
[
.BI <diskPoolName>
[:...]
]

.SH DESCRIPTION
.B printdiskpool
prints out definitions of the given disk pools
.LP
.BI \-h,\ \-\-help
Get usage information
.TP
.BI \-a,\ \-\-all
List all disk pools found in the stager catalog.
.TP
.BI <DiskPoolName>
name of disk pools to list. Several names can be given, colon separated. Note that
no name should be given if -a/--all is used.

.SH EXAMPLES
.nf
.ft CW
# printdiskpool -a
   NAME NSFILESYSTEMS    SVCCLASSES ID
--------------------------------------
  extra            10 dev, diskonly  9
default            10       default  7

# printdiskpool extra:nonexisting
 NAME NSFILESYSTEMS    SVCCLASSES ID
------------------------------------
extra            10 dev, diskonly  9
WARNING : the following disk pools do not exist : nonexisting

.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from castor.conf.

.SH SEE ALSO
.BR enterdiskpool,
.BR deletediskpool,
.BR printtapepool,
.BR printsvcclass,
.BR printfileclass,
.BR adminMultiInstance

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
