.\" @(#)$RCSfile: printtapestatesummary.man,v $ $Revision: 1.5 $ $Date: 2008/10/17 13:13:59 $ CERN IT/ADC Olof Barring
.\" Copyright (C) 2005 by CERN IT/ADC
.\" All rights reserved
.\"
.TH PRINTTAPESTATESUMMARY 1 "$Date: 2011/11/16 15:25:39 $" CASTOR "Prints the tape state summary"
.SH NAME
printtapestatesummary
.SH SYNOPSIS
.B printtapestatesummary
[
.BI -h, 
.BI --help
]
.SH DESCRIPTION
.B printtapestatesummary
Prints a summary of the states of the tapes in the stager database.
.LP
.BI \-h,\ \-\-help
Get usage information
.LP
.SH EXAMPLES
printtapestatesummary
.br
Number of RECALL    tapes in status TAPE_PENDING          = 0
.br
Number of RECALL    tapes in status TAPE_WAITDRIVE        = 0
.br
Number of RECALL    tapes in status TAPE_WAITMOUNT        = 0
.br
Number of RECALL    tapes in status TAPE_MOUNTED          = 0
.br
Number of RECALL    tapes in status TAPE_FINISHED         = 0
.br
Number of RECALL    tapes in status TAPE_FAILED           = 0
.br
Number of RECALL    tapes in status TAPE_UNKNOWN          = 0
.br
Number of RECALL    tapes in status TAPE_WAITPOLICY       = 0
.br
Number of RECALL    tapes in status TAPE_ATTACHEDTOSTREAM = 0
.br
Number of MIGRATION tapes in status TAPE_PENDING          = 0
.br
Number of MIGRATION tapes in status TAPE_WAITDRIVE        = 0
.br
Number of MIGRATION tapes in status TAPE_WAITMOUNT        = 0
.br
Number of MIGRATION tapes in status TAPE_MOUNTED          = 0
.br
Number of MIGRATION tapes in status TAPE_FINISHED         = 0
.br
Number of MIGRATION tapes in status TAPE_FAILED           = 0
.br
Number of MIGRATION tapes in status TAPE_UNKNOWN          = 0
.br
Number of MIGRATION tapes in status TAPE_WAITPOLICY       = 0
.br
Number of MIGRATION tapes in status TAPE_ATTACHEDTOSTREAM = 0
.br

.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from castor.conf.

.SH SEE ALSO
.BR adminMultiInstance(1castor)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
