.\" ******************************************************************************
.\"                      repack
.\"
.\" This file is part of the Castor project.
.\" See http://castor.web.cern.ch/castor
.\"
.\" Copyright (C) 2003  CERN
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.\"
.\" man page for the repack command.
.\"
.\" @author Castor Dev team, castor-dev@cern.ch
.\" *****************************************************************************/
.TH repack 8 "July, 2011" CASTOR "Moves data away from a tape"
.SH NAME
repack \- Move files from tape(s) to other tape destination
.SH SYNOPSIS
.B repack
.BI -h
.br
.B repack
.BI \-V\ <VID>[:<VID>[...]]\ \-o\ OutputServiceClass
.br
.B repack
.BI \-\-bulkvolumeid\ <file>\ \-o\ OutputServiceClass
.br
.B repack
.BI \-R\ <VID>[:<VID>[...]]
.br
.B repack
.BI \-\-bulkdelete\ <file>
.br
.B repack
.BI \-s\
.br
.B repack
.BI \-S\ <VID>[:<VID>[...]]
.br
.B repack
.BI \-e\ <VID>[:<VID>[...]]\ [\-n\ <nbErrorsDisplayed>]
.br

.SH DESCRIPTION
.B repack
allows to move files from one or several tapes to new media.
It also allows to get the status overview of the ongoing repack activity in the system.
Note that only volumes having
.B FULL
status may be repacked.

When the repack process has been successfully completed (FINISHED status), the volume can be
reclaimed using the reclaim command.

.SH OPTIONS

.TP
.BI \-h,\ \-\-help
displays command usage help.
.TP
.BI \-V,\ \-\-volumeid
submits the repacking of the given tapes and returns immediately. The tapes are given by their VID
and the list is colon separated. The actual repack processes are asynchronously started, one by one,
by the database.
.TP
.BI \-\-bulkvolumeid
submits the repacking of the tapes given in the provided file. The file must contain a list of VIDs,
one per line. Spaces and anything appearing after the '#' sign on a given line are ignored.
.TP
.BI \-o,\ \-\-svcclass
the service class to be used for repacking the given tapes.
.TP
.BI \-R,\ \-\-delete
cancels the repacking of the given tapes. The tapes are given by their VID and the list is colon separated.
Note that the cancelation may be refused in case too many repacks are already being launched or aborted.
The maximum number is defined in the Repack/MaxNbConcurrentClients entry of the CastorConfig table
in the stager database. The default value is 5.
.TP
.BI \-\-bulkdelete
cancels the repacking of the tapes given in the provided file. The file must contain alist of VIDs,
one per line. Spaces and anything appearing after the '#' sign on a given line are ignored.
Note that the cancelation may be refused in case too many repacks are already being launched or aborted.
The maximum number is defined in the Repack/MaxNbConcurrentClients entry of the CastorConfig table
in the stager database. The default value is 5.
.TP
.BI \-s,\ \-\-statusAll
shows the status of all ongoing and finished repacks. If multiple repack requests were issued for a given
tape, only the last request is shown. Note that old completed repacks are automatically removed
from the database and are not shown any longer.
.TP
.BI \-S,\ \-\-status
shows the status of ongoing and finished repacks for the given tape(s). The tape(s) is(are) given by their
VID and the list is colon separated. As opposed to the \-s option, here the entire history is shown.
.TP
.BI \-e,\ \-\-errors
displays the errors that occured during the repack of a given tape, file by file. By default, the number of
errors displayed is limited to 10. This can be changed using the \-n option
.TP
.BI \-n,\ \-\-nbErrorsDisplayed
in conjunction with \-e, sets the maximum number of errors to display.

.SH EXAMPLE
.nf
.ft CW
> repack -V V00000:V10025:V13049 -o default
vmgrlisttape: No such tape
Caught exception when executing vmgrlisttape for tape V00000, skipping
Tape V10025 is not marked FULL, ignoring it
Tape V13049 is already being repacked by user root, ignoring it

> repack -V I10551:I10552 -o default
Repack submitted for tape I10551
Repack submitted for tape I10552

> repack -s
============================================================================================================================================
SubmitTime              User                       Machine      Vid      Total        Size  toRecall    toMigr    Failed  Migrated    Status
--------------------------------------------------------------------------------------------------------------------------------------------
23-Jun-11 14:34     sponcec3         lxcastordev01.cern.ch   I10551         44    47.41KiB         0        43         1         0  STARTING
22-Jun-11 17:19     sponcec3         lxcastordev01.cern.ch   I10552          1        721B         0         0         0         1  FINISHED

> repack -S I10552
============================================================================================================================================
SubmitTime              User                       Machine      Vid      Total        Size  toRecall    toMigr    Failed  Migrated    Status
--------------------------------------------------------------------------------------------------------------------------------------------
23-Jun-11 14:34     sponcec3         lxcastordev01.cern.ch   I10552          1        721B         0         0         1         0   ABORTED 
22-Jun-11 17:19     sponcec3         lxcastordev01.cern.ch   I10552          1        721B         0         0         0         1  FINISHED
22-Jun-11 17:16     sponcec3         lxcastordev01.cern.ch   I10552         66    47.41KiB         0         0         1        65    FAILED

> repack -S I10551
============================================================================================================================================
SubmitTime              User                       Machine      Vid      Total        Size  toRecall    toMigr    Failed  Migrated    Status
--------------------------------------------------------------------------------------------------------------------------------------------
23-Jun-11 14:34     sponcec3         lxcastordev01.cern.ch   I10551         66    47.41KiB         0        65         1         0   ONGOING

> repack -R I10551

> repack -S I10551
============================================================================================================================================
SubmitTime              User                       Machine      Vid      Total        Size  toRecall    toMigr    Failed  Migrated    Status
--------------------------------------------------------------------------------------------------------------------------------------------
23-Jun-11 14:34     sponcec3         lxcastordev01.cern.ch   I10551         66    47.41KiB         0        25        41         0  ABORTING

> repack -S I10551
============================================================================================================================================
SubmitTime              User                       Machine      Vid      Total        Size  toRecall    toMigr    Failed  Migrated    Status
--------------------------------------------------------------------------------------------------------------------------------------------
23-Jun-11 14:34     sponcec3         lxcastordev01.cern.ch   I10551         66    47.41KiB         0         0        66         0   ABORTED

> repack -e I10551

     *** Tape  I10551  ***

--------------------------------------------------------------------------------------------
Fileid         CopyNo         ErrorCode      ErrorMessage
--------------------------------------------------------------------------------------------
5000053222     n/a            16             File is currently being written or migrated
5000157562     n/a            1701           Aborted explicitely
5000157580     n/a            1701           Aborted explicitely
5000156311     n/a            1701           Aborted explicitely
5000157587     n/a            1701           Aborted explicitely
5000157605     n/a            1701           Aborted explicitely
5000157611     n/a            1701           Aborted explicitely
5000157625     n/a            1701           Aborted explicitely
5000157632     n/a            1701           Aborted explicitely
5000157638     n/a            1701           Aborted explicitely

Output restricted to 10 errors. There are more errors for this tape

> repack -e I10551 -n 3

     *** Tape  I10551  ***

--------------------------------------------------------------------------------------------
Fileid         CopyNo         ErrorCode      ErrorMessage
--------------------------------------------------------------------------------------------
5000053222     n/a            16             File is currently being written or migrated
5000157562     n/a            1701           Aborted explicitely
5000157580     n/a            1701           Aborted explicitely

Output restricted to 3 errors. There are more errors for this tape

.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from castor.conf.

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch
