.\" @(#)$RCSfile: showPriority.man,v $ $Revision: 1.1 $ $Date: 2008/05/28 08:07:11 $ CERN IT/ADC Olof Barring
.\" Copyright (C) 2005 by CERN IT/ADC
.\" All rights reserved
.\"
.TH SHOWPRIORITY 1 "$Date: 2008/05/28 08:07:11 $" CASTOR "show entries in the priority map table used by vdqm"
.SH NAME
showPriority
.SH SYNOPSIS
.B showPriority
[
.BI -u 
.BID uid
.BI -g 
.BID gid
.BI -p 
.BID priority
.BI -h 
]
showPriority
.SH DESCRIPTION
.B showPriority
show the entries from the Priority Map Table, depending the option given.

.SH EXAMPLES
.fi

showPriority -u 444, to show all the entries associated to the user 

showPriority -g 999, to show all the entries associated to the group

showPriority -p 5, to show  all the entrirs associates to a specific priority
 
.SH NOTES
This command requires database client access to the stager catalogue.
Configuration for the database access is taken from castor.conf.

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
