.\" @(#)springCleaning.man,v 0.0 2006/02/28 11:00:00 CERN IT-FIO giulia taurelli
.\" Copyright (C) 2006 by CERN/IT/FIO
.\" All rights reserved
.\"
.TH SPRINGCLEANING 1 "2006/02/28 11:00:00 CERN IT-FIO" CASTOR "Perl script to clean all old requests."
.SH NAME
perl springCleaning\- run the script.
.SH SYNOPSIS
.B perl springCleaning [-t|--timeOut days] [-h|--help]
.SH DESCRIPTION
.LP
This script removes all requests older than the number of days specified with -t or --timeOut options. If nothing is specified the default value of 60 days is used.
.LP

.SH SEE ALSO
.BR adminMultiInstance(1castor)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>