.\" Copyright (C) 2003  CERN
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License
.\" as published by the Free Software Foundation; either version 2
.\" of the License, or (at your option) any later version.
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
.TH VDQMSETVOLPRIORITY 1 "$Date: 2008/05/20 20:52:00 $" CASTOR "Set a volume priority"
.SH NAME
vdqmsetvolpriority \- set a VDQM unlimited lifespan volume priority
.SH SYNOPSIS
.BI "vdqmsetvolpriority -v VID -a mode -p priority [ -h ]"

.SH DESCRIPTION
.B vdqmsetvolpriority
sets a VDQM unlimited lifespan volume priority

.SH OPTIONS
.TP
\fB\-v, \-\-vid VID\fR
volume visual Identifier
.TP
\fB\-a, \-\-tapeAccessMode mode
tape access mode 0 for read-only or 1 for write-enabled
.TP
\fB\-p, \-\-priority priority
volume priority
.TP
\fB\-h, \-\-help
get usage information

.SH EXAMPLES
.nf

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
