CREATE SEQUENCE ARCHIVE_FILE_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE
  MINVALUE 1
  NO CYCLE
  CACHE 20;
CREATE SEQUENCE LOGICAL_LIBRARY_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE
  MINVALUE 1
  NO CYCLE
  CACHE 20;
CREATE SEQUENCE MEDIA_TYPE_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE
  MINVALUE 1
  NO CYCLE
  CACHE 20;
CREATE SEQUENCE STORAGE_CLASS_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE
  MINVALUE 1
  NO CYCLE
  CACHE 20;
CREATE SEQUENCE TAPE_POOL_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE
  MINVALUE 1
  NO CYCLE
  CACHE 20;
CREATE SEQUENCE VIRTUAL_ORGANIZATION_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE
  MINVALUE 1
  NO CYCLE
  CACHE 20;
CREATE SEQUENCE FILE_RECYCLE_LOG_ID_SEQ
  INCREMENT BY 1
  START WITH 1
  NO MAXVALUE
  MINVALUE 1
  NO CYCLE
  CACHE 20;
