CREATE TABLE ARCHIVE_FILE_ID(
  ID INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE LOGICAL_LIBRARY_ID(
  ID INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE MEDIA_TYPE_ID(
  ID INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE STORAGE_CLASS_ID(
  ID INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE TAPE_POOL_ID(
  ID INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE VIRTUAL_ORGANIZATION_ID(
  ID INTEGER PRIMARY KEY AUTOINCREMENT
);
CREATE TABLE FILE_RECYCLE_LOG_ID(
  ID INTEGER PRIMARY KEY AUTOINCREMENT
);
