.\" $Id: print_stcp.man,v 1.2 2002/10/08 13:45:50 jdurand Exp $
.\"
.\" @(#)$RCSfile: print_stcp.man,v $ $Revision: 1.2 $ $Date: 2002/10/08 13:45:50 $ CERN IT-DS/HSM Jean-Damien Durand
.\" Copyright (C) 2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH PRINT_STCP "3" "$Date: 2002/10/08 13:45:50 $" "CASTOR" "Stage Library Functions"
.SH NAME
print_stcp \- Dumps an stgcat_entry to stdout
.SH SYNOPSIS
.BI "#include <" stage_api.h ">"
.sp
.BI "void print_stcp (struct stgcat_entry *" stcp ");"

.SH DESCRIPTION
The \fBprint_stcp\fP API method prints to standard output the content of an stgcat_entry structure.

.SH PARAMETERS
.TP 1.5i
.I stcp
Pointer to an stgcat_entry structure.

.SH EXAMPLE
See \fBstage_qry_Hsm\fP(3).

.SH SEE ALSO
\fBstage_struct\fP(3), \fBstage_qry_Hsm\fP(3)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>

