.\" $Id: stageshutdown.man,v 1.11 2002/12/13 15:31:25 jdurand Exp $
.\"
.\" @(#)$RCSfile: stageshutdown.man,v $ $Revision: 1.11 $ $Date: 2002/12/13 15:31:25 $ CERN IT-PDP/DM Jean-Damien Durand
.\" Copyright (C) 1995-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGESHUTDOWN "1" "$Date: 2002/12/13 15:31:25 $" "CASTOR" "Stager Administrator Commands"
.SH NAME
stageshutdown \- tells stgdaemon to exit
.SH SYNOPSIS
.B stageshutdown
[
.B \-F
]
.BI \-h " host"

.SH DESCRIPTION
.B stageshutdown
tells stgdaemon to exit. Before such exit, stgdaemon will send a interrupt signal to all of its child processes he is aware of.
.B stageshutdown
is a privileged command restricted for use by an administrator.

.SH OPTIONS
.TP
.B \-F
The command is executed immediately: new stage requests are rejected but
the daemon does not wait for existing stage requests to complete,
they just continue to run in parallel.
.TP
.BI \-h " host"
Sends the request to the stager on
.IR host .
This option is mandatory, regardless of environment variable $STAGE_HOST or entry 'STG HOST' in /etc/shift.conf.

.SH RETURN CODES
\
.br
0	Ok.
.br
1	Command aborted or another stageshutdown is pending.
.br
2	System error.
.br
3	Unknown error.
.br
187	CASTOR User Privilege validation not active
.br
198	Stager daemon not active

.SH SEE ALSO
\fBstage_shutdown\fP(3)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>

