.\" @(#)$RCSfile: stageping.man,v $ $Revision: 1.1 $ $Date: 2001/12/05 10:14:54 $ CERN IT-PDP/DM Jean-Damien Durand
.\" Copyright (C) 2001 by CERN/IT/PDP/DM
.\" All rights reserved
.\"
.TH STAGEPING l "$Date: 2001/12/05 10:14:54 $"
.SH NAME
stageping \- ping the stager daemon and get internal information about it
.SH SYNOPSIS
.B stageping
[
.BI -h " host"
] [
.BI -v
]
.SH DESCRIPTION
.B stageping
is used to check if the stager daemon answer to incoming requests.
.SH OPTIONS
.TP
.BI \-h " host"
sends the request to the stager on
.IR host .
This may also be specified thru the environment variable STAGE_HOST.
.TP
.BI \-v
Asks for additional information, like CASTOR package version, generated time and uptime.
.SH RETURN CODES
\
.br
0	Ok.
.br
1	Bad parameter.
.br
2	System error.
.br
4	Configuration error.
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>

