.\" $Id: stage_clr_Path.man,v 1.2 2002/12/13 15:30:00 jdurand Exp $
.\"
.\" @(#)$RCSfile: stage_clr_Path.man,v $ $Revision: 1.2 $ $Date: 2002/12/13 15:30:00 $ CERN IT-DS/HSM Jean-Damien Durand
.\" Copyright (C) 2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGE_CLR_PATH "3" "$Date: 2002/12/13 15:30:00 $" "CASTOR" "Stage Library Functions"
.SH NAME
stage_clr_Path \- Asks for a data file to be removed
.SH SYNOPSIS
.BI "#include <" stage_api.h ">"
.sp
.BI "int stage_clr_Path(u_signed64 " flags ,
.BI "char *" hostname ,
.BI "char *" pathname ");"

.SH DESCRIPTION
The \fBstage_clr_Path\fP API method asks the stager to delete a data file using its internal pathname. Outputs are the default ttys (unless you use \fBstage_setlog\fP).

.SH PARAMETERS
.TP 1.5i
.I flags
Can be zero or a bit-wise of the following values:
.RS
.TP
.I STAGE_CONDITIONAL
The remove operation is done only if the free space in the pool is lower than a minimum, defined with disk pools on the stager daemon side.
.TP
.I STAGE_FORCE
Delete found record even if it is in an intermediate state, protected against a\-priori user error.
.TP
.I STAGE_NODISK
Prevent any disk access. Just remove the entry.
.TP
.I STAGE_SILENT
No output in send back to the client.
.TP
.I STAGE_REMOVEHSM
Removes the HSM file
.I hsmname
from its Name Server, if
.I pathname
is found to refer an HSM file whose name is
.I hsmname.
.RE
.TP
.I hostname
Gives explicitely the hostname where is the stager daemon. If it NULL, default value apply: either the environment variable $STAGE_HOST, an entry 'STG HOST' in /etc/shift.conf file, or the default "stagepublic".
.TP
.I pathname
Full path of the internal filename

.SH RETURN VALUE
0 on success, -1 on failure.

.SH ERRORS
If failure, the serrno variable might contain one of the following error codes:
.TP 1.9i
.B SENOMAPFND
Can't open mapping database (Windows only)
.TP
.B EFAULT
Bad address
.TP
.B EINVAL
Invalid argument
.TP
.B ESTGROUP
Invalid group
.TP
.B ESTGRPUSER
Invalid group user
.TP
.B SECONNDROP
Connection closed by remote end
.TP
.B SECOMERR
Communication error
.TP
.B SEINTERNAL
Internal error
.TP
.B SEUSERUNKN
User unknown
.TP
.B ESTLINKNAME
User link name processing error
.TP
.B SEOPNOTSUP
Operation not supported (should not happen)
.TP
.B ENOENT
No such file or directory
.TP
.B SESYSERR
System error
.TP
.B EBUSY
Device or resource busy
.TP
.B ESTLNKNSUP
Symbolic link not supported
.TP
.B ESTNACT
Stager not active (if you specify the STAGE_NORETRY flag - default is to retry forever)
.TP
.B SENOSHOST
Host not known
.TP
.B SETIMEDOUT
Timed out

.SH SEE ALSO
\fBstageclr\fP(1), \fBstage_setlog\fP(3)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>

