.\" $Id: stageout.man,v 1.13 2002/10/03 14:03:56 jdurand Exp $
.\"
.\" @(#)$RCSfile: stageout.man,v $ $Revision: 1.13 $ $Date: 2002/10/03 14:03:56 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1994-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGEOUT "1" "$Date: 2002/10/03 14:03:56 $" "CASTOR" "Stage User Commands"
.SH NAME
stageout \- allocate space and store the option values in the stgdaemon catalog
for use by stageput later.
.SH SYNOPSIS
.B stageout 
[
.BI \-h " host"
] [ 
.BI \-K
] [
.BI \-M " hsmfile"
] [
.BI \-p " pool"
] [
.BI \-s " size"
] [ 
.BI \-\-noretry
] [ 
.I files
]
.SH DESCRIPTION
This command sends a request to a stage daemon which allocates space in a pool
and stores the option values in its catalog.
Then the daemon creates an empty file and sets the ownership and permissions.
.LP
.I file
may be a local path, the combination
.I machine:fullpath
(NFS syntax), a full path starting with the NFS_ROOT, i.e. /shift,
or absent.
.SH OPTIONS
.TP
.BI \-h " host"
Sends the request to the stager on
.IR host .
This may also be specified thru the environment variable STAGE_HOST.
.BI \-K
Keeps file on disk.
If this option is absent, the disk file is removed as soon as the
.B stageput
operation is successful.
.TP
.BI \-M " hsmfile"
Gives the name of a Hierarchical Storage Manager (HSM) file. In this case,
.B rfcp
will be used to copy the file from the staging pool to that HSM file.
.TP
.BI \-p " poolname"
Allocates the file in the pool
.IR poolname .
This may also be specified thru the environment variable STAGE_POOL.
.TP
.BI \-s " size"
If specified, only 
.I size 
Mbytes will be copied.
Only digits followed by eventual unit are accepted. The unit can be 'b' for byte, 'k' for kilo-byte, 'M' for Mega-byte (default), 'G' for Giga-byte, 'T' for Tera-byte and 'P' for Peta-byte. In the case of multiple files, a series of size values may be given,
separated by ":"s. These apply to the tape files in the specified order.
If there are more files than size values, the last one will be used for all
remaining files. Thus, a single size value may be given which applies to all files on the tape.
.TP
.B \-\-noretry
There will be no retry in case of any failure.

.SH EXAMPLES
.LP
To allocate disk space for two files on output,
generate the data and delegate them for the CASTOR storage migration:
.RS
stageout -s 10:20 \\
.br
\-M $CASTOR_HOME/stageout_file \\
.br
\M $CASTOR_HOME/stageout_file2 \\
.br
out out2
.LP
a.out out
.br
b.out out2
.LP
stageupdc out out2
.RE

.SH RETURN CODES
\
.br
0	Ok.
.br
1	Bad parameter.
.br
2	System error.
.br
4	Configuration error.
.br
16	EBUSY: Device or resource busy.
.br
28	ENOSPC: No space left on device.
.br
192	Request cancelled by stageclr.
.br
198	Stager not active

.SH SEE ALSO
\fBstageupdc\fP(1), \fBstageput\fP(1), \fBstage_other_options\fP(1)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
