.\" $Id: stagealloc.man,v 1.11 2002/10/27 23:29:12 jdurand Exp $
.\"
.\" @(#)$RCSfile: stagealloc.man,v $ $Revision: 1.11 $ $Date: 2002/10/27 23:29:12 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1995-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGEALLOC "1" "$Date: 2002/10/27 23:29:12 $" "CASTOR" "Stage User Commands"
.SH NAME
stagealloc \- allocate space in a disk pool

.SH SYNOPSIS
.B stagealloc  
[
.BI \-h " host"
] [
.BI \-P 
] [
.BI \-p " pool"
] [
.BI \-s " size"
]
.I file
.SH DESCRIPTION
This command sends a request to a stager daemon which allocates space,
creates an empty file with the correct privileges, establishes a symbolic link
.I file
to it and updates its catalog.
.LP
Then the internal path name or the link can be used by the application program
to write the data to disk. When the file is complete,
.B stageupdc
should be called to update the actual file size in the stager catalog. See the
example below.
.LP
.I file
may be a local path, the combination
.I machine:fullpath
(NFS syntax), a full path starting with the NFS_ROOT, i.e. /shift,
or absent if a Fortran unit number is specified.
.LP
.SH OPTIONS
.TP
.BI \-h " host"
Sends the request to the stager on
.IR host .
This may also be specified thru the environment variable STAGE_HOST.
.TP
.B \-P
prints on stdout the internal path name.
.TP
.BI \-p " poolname"
Allocates the file in the pool
.IR poolname .
This may also be specified thru the environment variable STAGE_POOL.
.TP
.BI \-s " size"
If specified, only 
.I size 
Mbytes will be allocated.
Only digits followed by eventual unit are accepted. The unit can be 'b' for byte, 'k' for kilo-byte, 'M' for Mega-byte (default), 'G' for Giga-byte, 'T' for Tera-byte and 'P' for Peta-byte.

.SH EXAMPLES
To allocate space for a 10 Mbytes file, write data and update the stager
catalog, the following set of commands could be used:
.RS
stagealloc \-s 10 out
.br
a.out out
.br
stageupdc out
.RE
.SH RETURN CODES
\
.br
0	Ok.
.br
1	Bad parameter.
.br
2	System error.
.br
28	ENOSPC: unable to find enough disk space.
.br
192	Request cancelled by stageclr.

.SH SEE ALSO
\fBstage_other_options\fP(3)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
