.\" $Id: stagein.man,v 1.28 2004/03/08 17:39:29 jdurand Exp $
.\"
.\" @(#)$RCSfile: stagein.man,v $ $Revision: 1.28 $ $Date: 2004/03/08 17:39:29 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1994-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGEIN "1" "$Date: 2004/03/08 17:39:29 $" "CASTOR" "Stager User Commands"
.SH NAME
stagein \- allocate space in a disk pool and copy files from tape to disk or from disk to disk
.SH SYNOPSIS
.B stagein  
[
.BI \-A " allocation_policy"
] [
.BI \-h " host"
] [
.BI \-M " hsmfile"
] [
.BI \-p " pool"
] [
.BI \-s " size"
] [ 
.BI \-\-nocopy
] [ 
.BI \-\-noretry
] [ 
.BI \-\-nowait
] [ 
.BI \-\-rdonly
.\" ] [ 
.\" .BI \-\-side " sidenumber"
] [ 
.BI \-\-silent
] [ 
.I files
] 
.SH DESCRIPTION
This command sends a request to a stage daemon which checks its catalog.
If the file has already been staged, the catalog is updated
(number of accesses, last access time) and if
.I file
is different from previous job, a symbolic link is created and the control
given back to the user.
If the file is not staged yet, pools have been configured and
.B \-p NOPOOL
is not specified, the file is allocated in a pool of which the space is managed
by the stage daemon.
If no pool has been configured or
.B \-p NOPOOL
is specified, the tape is staged directly in the location given by
.I file
and no space management is done.
To do the actual copy, a
.B tpread
or an
.B rfcp
is issued.
When complete, if
.I file
is specified, a symbolic link pointing at the actual file is created with that
name.
.LP
.I file
may be a local path, the combination
.I machine:fullpath
(NFS syntax), a full path starting with the NFS_ROOT, i.e. /shift,
or absent.

.SH OPTIONS
.TP
.BI \-A " allocation_policy"
Disk space allocation policy may be:
.RS
.TP
.B immediate
The disk space is allocated when receiving the stage request.
This is the default.
.TP
.B deferred
The disk space is allocated only when needed, i.e. one file at a time.
In case of multifile stageing, space is allocated for the first file, the copy
from tape to disk is done, the unused space is released; the process is 
then repeated for every tape file requested and found on the tape.
This mode increases the lifetime of files in the pool and is very useful when
files are of unknown size or vary a lot in size.
.RE
.TP
.BI \-h " host"
Sends the request to the stager on
.IR host .
This may also be specified thru the environment variable STAGE_HOST, or an entry 'STG HOST' in /etc/shift.conf.
.TP
.BI \-M " hsmfile"
Gives the name of a file stored in an Hierarchical Storage Manager (HSM).
.B rfcp
is used to copy the file to the staging pool. The option
.B \-s
is not needed for a complete file stageing: the stager queries the HSM system
about the file size and allocates correctly the disk space in the pool.
Partial stageing is supported.
.TP
.BI \-p " poolname"
Allocates the file in the pool
.IR poolname .
This may also be specified thru the environment variable STAGE_POOL.
.TP
.BI \-s " size"
If specified, only 
.I size 
Mbytes will be copied.
Only digits followed by eventual unit are accepted. The unit can be 'b' for byte, 'k' for kilo-byte, 'M' for Mega-byte (default), 'G' for Giga-byte, 'T' for Tera-byte and 'P' for Peta-byte.
In the case of multiple files, a series of size values may be given,
separated by ":"s. These apply to the tape files in the specified order.
If there are more files than size values, the last one will be used for all
remaining files. Thus, a single size value may be given which applies to all files on the tape.
.TP
.B \-\-nocopy
If disk pools does allow export of HSM file, then the stager might decide to do a disk-to-disk copy instead of a real recall. This option supresses the optionnal internal copy between pools.
.TP
.B \-\-noretry
There will be no retry in case of any failure. Can be set using environment variable STAGE_NORETRY to a non-zero value, or an entry 'STG NORETRY' in /etc/shift.conf.
.TP
.B \-\-nowait
Does not hang the client. Recall is done internally without further notification.
.TP
.B \-\-rdonly
Tells the stager that you are requesting this file for read-only purpose.
.TP
.B \-\-silent
Tells the stager not to output you any message. This does not prevent very few messages generated on the client side to appear, in particular when the stager is in pause mode.
.\" .TP
.\" .B \-\-side "sidenumber"
.\" Tells which side of the device you want to stage in (applies to multi-side medias, like DVD). It apply only when used with
.\" .B \-V
.\" and/or
.\" .B \-v
.\" options.

.SH EXAMPLES
.LP
To get the CASTOR file $CASTOR_HOME/testfile into the default stage pool:
.RS
stagein \-M $CASTOR_HOME/testfile
.RE
.LP
To get more than one CASTOR file, with recommended deferred allocation mode:
.RS
stagein \-A deferred \-M $CASTOR_HOME/testfile1 \\
.br
\-M $CASTOR_HOME/testfile2
.RE
.LP
If your intention was only to read the CASTOR file and never modify it, it is recommended to add the \-\-rdonly parameter:
.RS
stagein \-\-rdonly \-A deferred \\
.br
\-M $CASTOR_HOME/testfile1 \\
.br
\-M $CASTOR_HOME/testfile2
.RE

.SH RETURN CODES
\
.br
0	Ok.
.br
1	Bad parameter.
.br
2	System error.
.br
3	Unknown error.
.br
16	EBUSY: Device or resource busy.
.br
28	ENOSPC: No space left on device.
.br
188	Tape hosting the data is held
.br
192	Request cancelled by stageclr.
.br
193	Blocks were skipped.
.br
194	Blocks were skipped and stageing limited by size.
.br
195	Stagein stopped: too many tape errors, but \-E keep.
.br
196	Request killed
.br
197	Stageing limited by size.
.br
198	Stager not active
.br
200	Bad checksum

.SH SEE ALSO
\fBstage_other_options\fP(1)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
