.\" $Id: stageupdc.man,v 1.12 2002/10/27 23:29:13 jdurand Exp $
.\"
.\" @(#)$RCSfile: stageupdc.man,v $ $Revision: 1.12 $ $Date: 2002/10/27 23:29:13 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1995-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGEUPDC "1" "$Date: 2002/10/27 23:29:13 $" "CASTOR" "Stager User Commands"
.SH NAME
stageupdc \- update the stager catalog
.SH SYNOPSIS
.B stageupdc
[
.BI \-h " host"
] [
.I files
]
.LP
.B stageupdc
[
.BI \-h " host"
] [
.BI \-R " exit_code"
] [
.BI \-s " size"
] [
.BI \-T " transfer_time"
]
.BI \-Z " stage_reqid"
.SH DESCRIPTION
.B stageupdc
updates the stager catalog.
.LP
The first format may only be used after a
.B stagealloc
or
.B stageout
command. The
.I file
parameter must match the one used on
.B stagealloc
or
.BR stageout .
The file must be in state STAGEALLOC or STAGEOUT.
.I file
may be a local path, the combination
.I machine:fullpath
(NFS syntax) or a full path starting with the NFS_ROOT, i.e. /shift.
.LP
When applied on a CASTOR HSM file, previously created with
.B stageout
, 
.B stageupdc
makes it eligible for automatic migration.
.LP
The second format was used by rtcopy to send back information to the stager.
.SH OPTIONS
.TP
.BI \-h " host"
Sends the request to the stager on
.IR host .
This may also be specified thru the environment variable STAGE_HOST.
.TP
.BI \-R " exit_code"
Exit code for the file stage subrequest.
.TP
.BI \-s " size"
Gives the actual filesize in bytes. Only digits followed by eventual unit are accepted. The unit can be 'b' for byte (default), 'k' for kilo-byte, 'M' for Mega-byte, 'G' for Giga-byte, 'T' for Tera-byte and 'P' for Peta-byte.
.TP
.BI \-T " transfer_time"
Time spent transferring data between store and disk server.
.TP
.BI \-Z " stage_reqid"
The value is in the form
.BR "reqid.key@stagehost" .

.SH RETURN CODES
\
.br
0       Ok.
.br
1       Bad parameter.
.br
2       System error.

.SH SEE ALSO
\fBstageout\fP(1), \fBstage_other_options\fP(1)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>

