.\" $Id: stage.man,v 1.10 2002/10/08 14:55:11 jdurand Exp $
.\"
.\" @(#)$RCSfile: stage.man,v $ $Revision: 1.10 $ $Date: 2002/10/08 14:55:11 $ CERN IT-PDP/DM Jean-Philippe Baud Jean-Damien Durand
.\" Copyright (C) 1996-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGE "1" "$Date: 2002/10/08 14:55:11 $" "CASTOR" "Stage User and Admin Commands"
.SH DESCRIPTION
The staging facilities offer fast access to data via copies in a disk pool.
A stage daemon manages the pool space and keeps a catalog of staged files.
A disk pool consists in a number of file systems distributed over different
machines.
It can be private to an experiment or public.
Use 
.B man
.I command
for details of the commands recognized by the stager:
.TP 15
stagealloc
allocate space in a disk pool
.TP
stagecat
put an entry in the stage daemon catalog for an existing file (admin only)
.TP
stagechng
change files attributes
.TP
stageclr
remove staged files
.TP
stageget
find file allocated in a disk pool with
.BR stagealloc .
.TP
stagein
allocate space in a disk pool and copy files from
tape to disk or from disk to disk
.TP
stageinit
tell stgdaemon to reread the pool configuration file (admin only)
.TP
stageout
allocate space and store the option values in the
stgdaemon catalog for use by stageput later
.TP
stageping
ping stager daemon
.TP
stageput
copy disk files to tape. It can only be used for a file allocated with stageout
.TP
stageqry
give the status of all staged tapes
.TP
stageupdc
update the stager catalog
.TP
stagewrt
copy existing files from disk to tape or from disk to disk
.TP
stageshutdown
stops stager daemon (admin only)

.SH NOTES
Old options, not for new applications, are in the \fBstage_other_options\fP(1) man page.

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
