.\" $Id: stagecat.man,v 1.14 2002/10/27 23:29:12 jdurand Exp $
.\"
.\" @(#)$RCSfile: stagecat.man,v $ $Revision: 1.14 $ $Date: 2002/10/27 23:29:12 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1994-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGECAT "1" "$Date: 2002/10/27 23:29:12 $" "CASTOR" "Stage User Commands"
.SH NAME
stagecat \- put an entry in the stage daemon catalog for an existing file

.SH SYNOPSIS
.B stagecat 
[
.BI \-h " host"
] [
.BI \-M " hsmfile"
] [
.BI \-p " pool"
] [
.BI \-s " size"
] 
.I file
.SH DESCRIPTION
This command sends a request to a stage daemon
to create an entry in the catalog for an already existing data
.IR file .
.LP
.I file
may be a local path, the combination
.I machine:fullpath
(NFS syntax) or a full path starting with the NFS_ROOT, i.e. /shift.
.LP
.B stagecat
is a privileged command restricted for use by an administrator.
.SH OPTIONS
.TP
.BI \-h " host"
Sends the request to the stager on
.IR host .
This may also be specified thru the environment variable STAGE_HOST.
.TP
.BI \-M " hsmfile"
Specifies hsm filename associated with this file. Please note that the file in the HSM tree will not be created, stagecat remains an internal stage operation. It is then the user's responsability to make sure file will exist in the HSM tree and will be migrated.
.TP
.BI \-p " poolname"
The file resides in the pool
.IR poolname .
This may also be specified thru the environment variable STAGE_POOL.
.TP
.BI \-s " size"
If specified, the number of Mbytes was limited to
.I size 
when the data was copied from tape to disk. Only digits followed by eventual unit are accepted. The unit can be 'b' for byte, 'k' for kilo-byte, 'M' for Mega-byte (default), 'G' for Giga-byte, 'T' for Tera-byte and 'P' for Peta-byte.

.SH RETURN CODES
\
.br
0	Ok.
.br
1	Bad parameter.
.br
2	System error.
.br
198	Stager not active

.SH SEE ALSO
\fBstage_other_options\fP(1)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
