.\" $Id: stageping.man,v 1.7 2002/10/19 14:47:12 jdurand Exp $
.\"
.\" @(#)$RCSfile: stageping.man,v $ $Revision: 1.7 $ $Date: 2002/10/19 14:47:12 $ CERN IT-PDP/DM Jean-Damien Durand
.\" Copyright (C) 2001-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGEPING "1" "$Date: 2002/10/19 14:47:12 $" "CASTOR" "Stage User Commands"
.SH NAME
stageping \- ping the stager daemon
.SH SYNOPSIS
.B stageping
[
.BI \-h " host"
] [
.BI \-v
] [ 
.BI \-\-noretry
]

.SH DESCRIPTION
.B stageping
is used to check if the stager daemon answer to incoming requests.

.SH OPTIONS
.TP
.BI \-h " host"
sends the request to the stager on
.IR host .
This may also be specified thru the environment variable STAGE_HOST.
.TP
.BI \-v
Asks for additional information, like CASTOR package version, generated time and uptime.
.TP
.B \-\-noretry
There will be no retry in case of any failure. Can be set using environment variable STAGE_NORETRY to a non-zero value, or an entry 'STG NORETRY' in /etc/shift.conf.

.SH RETURN CODES
\
.br
0	Ok.
.br
1	Bad parameter.
.br
2	System error.
.br
4	Configuration error.
.br
198	Stager not active

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>

