.\" $Id: stageput.man,v 1.14 2002/10/08 11:45:58 baud Exp $
.\"
.\" @(#)$RCSfile: stageput.man,v $ $Revision: 1.14 $ $Date: 2002/10/08 11:45:58 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1994-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGEPUT "1" "$Date: 2002/10/08 11:45:58 $" "CASTOR" "Stage User Commands"
.SH NAME
stageput \- copy disk files to tape, to an external disk file or to a
Hierarchical Storage Management System.
.SH SYNOPSIS
.B stageput
[
.BI \-h " host"
] [
.BI \-\-noretry
] [
.BI \-\-nowait
] [
.I files
]
.LP
.B stageput
[
.BI \-h " host"
] [
.BI \-M " hsmfile"
] [
.BI \-M ...
] [
.BI \-\-noretry
] [
.BI \-\-nowait
]
.SH DESCRIPTION
.B stageput
copies disk files to tape, to an external disk file or to a
Hierarchical Storage Management System. It can only be used after a
.B stageout
command. The
.I file
parameter must match the one used on
.BR stageout .
The file must be in state STAGEOUT or PUT_FAILED.
.I file
may be a local path, the combination
.I machine:fullpath
(NFS syntax) or a full path starting with the NFS_ROOT, i.e. /shift.
.SH OPTIONS
.TP
.BI \-h " host"
Sends the request to the stager on
.IR host .
This may also be specified thru the environment variable STAGE_HOST.
.TP
.BI \-M " hsmfile"
Gives the name(s) of Hierarchical Storage Manager (HSM) file(s). In this case,
.B rfcp
is used to copy the file from the staging pool to that HSM file. This is a deprecated use of the stage s/w and \fBstagewrt\fP should be used instead.
.TP
.B \-\-noretry
There will be no retry in case of any failure.
.TP
.BI \-\-nowait
specifies that the command should return immediately. Copy in done in the background of the stager daemon.
.SH RETURN CODES
\
.br
0	Ok.
.br
1	Bad parameter.
.br
2	System error.
.br
4	Configuration error.
.br
28	ENOSPC: tape volume overflow.
.br
188	Tape is held
.br
192	Request cancelled by stageclr.
.br
197	Stageing limited by size.
.br
198	Stager not active

.SH SEE ALSO
\fBstageout\fP(1), \fBstage_other_options\fP(1)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
