.\" $Id: stagewrt.man,v 1.26 2002/12/13 15:31:25 jdurand Exp $
.\"
.\" @(#)$RCSfile: stagewrt.man,v $ $Revision: 1.26 $ $Date: 2002/12/13 15:31:25 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1994-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGEWRT "1" "$Date: 2002/12/13 15:31:25 $" "CASTOR" "Stage User Commands"
.SH NAME
stagewrt \- copy existing files from disk to tape, from disk to disk or from
disk to a Hierarchical Storage Management System.
.SH SYNOPSIS
.B stagewrt 
[
.BI \-A " deferred"
] [
.BI \-h " host"
] [ 
.BI \-K
] [
.BI \-M " hsmfile"
[
.BI \-M " hsmfile2"
[
.BI \-M " ..."
]]] [
.BI \-p " pool"
] [
.BI \-s " size"
] [
.BI \-\-nohsmcreat
] [
.BI \-\-noretry
] [ 
.\" .BI \-\-side " sidenumber"
.\" ] [ 
.BI \-\-silent
] [
.BI \-\-tppool " tape_pool"
] [
.BI \-\-volatile_tppool
] 
.I files
.SH DESCRIPTION
This command sends a request to a stage daemon to copy existing disk files
to tape or to disk. They must be not empty. To do the actual copy a
.B tpwrite
is issued.
.LP
.I file
may be a local path, the combination
.I machine:fullpath
(NFS syntax), a full path starting with the NFS_ROOT, i.e. /shift,
or absent if a Fortran unit number is specified.
.SH OPTIONS
.TP
.BI \-A " deferred"
is valid only when doing stagewrt of CASTOR HSM files. It puts your request in the migration queue, the HSM files will be automatically migrated later. If there is no error when parsing the input, the client then returns immediately. This option requires at least one \-M option and one user file as parameter. The user files must reside in a filesystem known to the stagein system.
.TP
.BI \-h " host"
Sends the request to the stager on
.IR host .
This may also be specified thru the environment variable STAGE_HOST.
.TP
.BI \-K
Keeps file on disk.
If this option is absent, the disk file is removed as soon as the
.B stagewrt
operation is successful.
.TP
.BI \-M " hsmfile"
Gives the name of a Hierarchical Storage Manager (HSM) file. For CASTOR files multiple \-M options is possible, requiring then that the same number of disk files is given and that \-M option values are unique.
.TP
.BI \-p " poolname"
Indicates that the file resides in the pool
.IR poolname .
This may also be specified thru the environment variable STAGE_POOL.
.TP
.BI \-s " size"
If specified, only 
.I size 
Mbytes will be copied.  Only digits followed by eventual unit are accepted. The unit can be 'b' for byte (default), 'k' for kilo-byte, 'M' for Mega-byte, 'G' for Giga-byte, 'T' for Tera-byte and 'P' for Peta-byte. In the case of multiple files, a series of size values may be given,
separated by ":"s. These apply to the tape files in the specified order. If there are more files than size values, the last one will be used for all remaining files. Thus, a single size value may be given which applies to all files on the tape.
.TP
.BI \-\-nohsmcreat
Do not create entry in the HSM if it does not yet exist.
.TP
.B \-\-noretry
There will be no retry in case of any failure.
.TP
.B \-\-silent
Tells the stager not to output you any message.
.\" .TP
.\" .B \-\-side "sidenumber"
.\" Tells which side of the device you want to stage in (applies to multi-side medias, like DVD). It apply only when used with
.\" .B \-V
.\" and/or
.\" .B \-v
.\" options.
.TP
.BI \-\-tppool " tape_pool "
Forces a specific tape pool. This applies only to CASTOR HSM files to be migrated.
.TP
.BI \-\-volatile_tppool
Says that the stager is allowed to switch to another tape pool if necessary when migrating. This apply only to CASTOR files that have a fileclass that specify one copy only but with more than one available tape pool. If the tape pool you eventually gave on the command-line (
.BI \-\-tppool
) appears to be full, the migration process will try with other tape pool(s).

.SH EXAMPLES
.LP
To write into CASTOR
.RS
stagewrt \-M /castor/cern.ch/... diskfile
.RE
.SH NOTES
\fBstagewrt\fP do not support concatenation of files.
.SH RETURN CODES
\
.br
0	Ok.
.br
1	Bad parameter.
.br
2	System error.
.br
3	Unknown error.
.br
16	EBUSY: Device or resource busy.
.br
28	ENOSPC: No space left on device.
.br
188	Tape is held
.br
192	Request cancelled by stageclr.
.br
197	Stageing limited by size.
.br
198	Stager not active

.SH SEE ALSO
\fBstage_other_options\fP(1)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
