.\" $Id: stageget.man,v 1.8 2002/10/03 14:03:56 jdurand Exp $
.\"
.\" @(#)$RCSfile: stageget.man,v $ $Revision: 1.8 $ $Date: 2002/10/03 14:03:56 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1996-2002 by CERN/IT/DS/HSM
.\" All rights reserved
.\"
.TH STAGEGET "1" "$Date: 2002/10/03 14:03:56 $" "CASTOR" "Stage User Commands"
.SH NAME
stageget \- find file allocated in a disk pool with stagealloc
.SH SYNOPSIS
.B stageget  
[
.BI \-h " host"
] [
.BI \-P 
] [
.BI \-p " pool"
]
.I file
.SH DESCRIPTION
This command sends a request to a stager daemon which finds the file previously
allocated with
.BR stagealloc ,
establishes a symbolic link
.I file
to it and updates its catalog (number of accesses and last access date).
.LP
Then the internal path name or the link can be used by the application program
to read the data from disk.
The file must be in state STAGED, i.e.
.B stagealloc
and
.B stageupdc
must have been both used for that file. See the
example below.
.LP
.I file
may be a local path, the combination
.I machine:fullpath
(NFS syntax), a full path starting with the NFS_ROOT, i.e. /shift,
or absent if a Fortran unit number is specified.
.LP
.SH OPTIONS
.TP
.BI \-h " host"
Sends the request to the stager on
.IR host .
This may also be specified thru the environment variable STAGE_HOST.
.TP
.B \-P
prints on stdout the internal path name.
.TP
.BI \-p " poolname"
Restricts the search to the pool
.IR poolname .

.SH EXAMPLES
.TP
A first session could save a large program in the pool:
.sp
stagealloc \-s 20 MyDice_XXX.sav
.br
rfcp MyDice_XXX MyDice_XXX.sav
.br
stageupdc MyDice_XXX.sav
.TP
A new job could retrieve it and use it by saying:
.sp
stageget MyDice_XXX.sav
.br
rfcp MyDice_XXX.sav MyDice_XXX
.br
MyDice_XXX

.SH RETURN CODES
\
.br
0	Ok.
.br
1	Bad parameter.
.br
2	System error.
.br
4	Configuration error.

.SH SEE ALSO
\fBstage_other_options\fP(1)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
