.\" @(#)$RCSfile: stgcastor_to_shift.man,v $ $Revision: 1.4 $ $Date: 2002/01/30 08:12:54 $ CERN IT-PDP/DM Jean-Damien Durand
.\" Copyright (C) 1994-1999 by CERN/IT/PDP/DM
.\" All rights reserved
.\"
.TH STGCASTOR_TO_SHIFT l "$Date: 2002/01/30 08:12:54 $"
.SH NAME
stgcastor_to_shift \- Convert CASTOR stager catalogs to SHIFT disk ones
.SH SYNOPSIS
.B stgcastor_to_shift [options] stgcat_castor stgpath_castor stgcat_shift stgpath_shift
.SH DESCRIPTION
.LP
The
.B stgcastor_to_shift
command will convert CASTOR's stdgaemon catalogs to SHIFT's stgdaemon ones.
.P
See the \fBEXAMPLE\fP section below.
.SH OPTIONS
The options are:
.RS
.B \-h
.RS
Online help
.RE
.B \-C
.RS
Ignore main catalog (stgcat) processing
.RE
.B \-L
.RS
Ignore second catalog (stgpath) processing
.RE
.BI "\-n <" number ">"
.RS
Online output frequency on your terminal. Default is every 1000 processed entries
.RE
.RE

.SH EXAMPLE
.ft 3
.nf
.sp
stgcastor_to_shift /usr/spool/stage/stgcat /usr/spool/stage/stgpath ./stgcat_shift ./stgpath_shift
.ft
.LP
.fi

.SH SEE ALSO
\fBstgconvert\fP(1), \fBstgshift_to_castor\fP(1), \fBstgshift_cmp_shift\fP(1)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
