.\" @(#)$RCSfile: stgshift_cmp_shift.man,v $ $Revision: 1.4 $ $Date: 2002/01/30 08:12:54 $ CERN IT-PDP/DM Jean-Damien Durand
.\" Copyright (C) 1994-1999 by CERN/IT/PDP/DM
.\" All rights reserved
.\"
.TH STGSHIFT_CMP_SHIFT l "$Date: 2002/01/30 08:12:54 $"
.SH NAME
stgshift_cmp_shift \- Compares two SHIFT stager catalogs
.SH SYNOPSIS
.B stgshift_cmp_shift [options] stgcat_shift1 stgpath_shift1 stgcat_shift2 stgpath_shift2
.SH DESCRIPTION
.LP
The
.B stgshift_cmp_shift
command will compare two SHIFT's stdgaemon catalogs.
.P
See the \fBEXAMPLE\fP section below.
.SH OPTIONS
The options are:
.RS
.B \-h
.RS
Online help
.RE
.B \-b
.RS
Do a binary (\fBmemcmp()\fP) diff instead of a member per member comparison
.RE
.B \-C
.RS
Ignore main catalog (stgcat) processing
.RE
.B \-L
.RS
Ignore second catalog (stgpath) processing
.RE
.BI "\-n <" number ">"
.RS
Online output frequency on your terminal. Default is every 1000 processed entries
.RE
.RE

.SH EXAMPLE
.ft 3
.nf
.sp
stgshift_cmp_shift /usr/spool/stage/stgcat.1 /usr/spool/stage/stgpath.1 /usr/spool/stage/stgcat.2 /usr/spool/stage/stgpath.2
.ft
.LP
.fi

.SH SEE ALSO
\fBstgconvert\fP(1), \fBstgcastor_to_shift\fP(1), \fBstgshift_to_castor\fP(1)

.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
