# SPDX-FileCopyrightText: 2015 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

# This module will set the following variables:
#     ORACLE-INSTANTCLIENT_FOUND
#     ORACLE-INSTANTCLIENT_INCLUDE_DIRS
#     ORACLE-INSTANTCLIENT_LIBRARIES
#     ORACLE-INSTANTCLIENT_RPATH

file(GLOB ORACLE_INCLUDE_DIRS "/usr/include/oracle/*/client64")
file(GLOB ORACLE-INSTANTCLIENT_RPATH "/usr/lib/oracle/*/client64/lib")


find_path(ORACLE-INSTANTCLIENT_INCLUDE_DIRS
  occi.h
  PATHS ${ORACLE_INCLUDE_DIRS}
  NO_DEFAULT_PATH)

find_library(ORACLE-INSTANTCLIENT_CLNTSH_LIBRARY
  NAME clntsh
  PATHS ${ORACLE-INSTANTCLIENT_RPATH}
  NO_DEFAULT_PATH)

find_library(ORACLE-INSTANTCLIENT_OCCI_LIBRARY
  NAME libocci.so
  PATHS ${ORACLE-INSTANTCLIENT_RPATH}
  NO_DEFAULT_PATH)

set(ORACLE-INSTANTCLIENT_LIBRARIES
  ${ORACLE-INSTANTCLIENT_OCCI_LIBRARY}
  ${ORACLE-INSTANTCLIENT_CLNTSH_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(oracle-instantclient DEFAULT_MSG
  ORACLE-INSTANTCLIENT_INCLUDE_DIRS
  ORACLE-INSTANTCLIENT_LIBRARIES
  ORACLE-INSTANTCLIENT_RPATH)
