echo /tmp/vdqm_CloseConn.c; diff /tmp/vdqm_CloseConn.c .
echo /tmp/vdqm_InitNW.c; diff /tmp/vdqm_InitNW.c .
echo /tmp/vdqm_InitPool.c; diff /tmp/vdqm_InitPool.c .
echo /tmp/vdqm_Listen.c; diff /tmp/vdqm_Listen.c .
echo /tmp/vdqm_PoolOp.c; diff /tmp/vdqm_PoolOp.c .
echo /tmp/vdqm_ProcReq.c; diff /tmp/vdqm_ProcReq.c .
echo /tmp/vdqm_QueueOp.c; diff /tmp/vdqm_QueueOp.c .
echo /tmp/vdqm_RcopyOp.c; diff /tmp/vdqm_RcopyOp.c .
echo /tmp/vdqm_Replica.c; diff /tmp/vdqm_Replica.c .
echo /tmp/vdqm_RtcopyOp.c; diff /tmp/vdqm_RtcopyOp.c .
echo /tmp/vdqm_SendRecv.c; diff /tmp/vdqm_SendRecv.c .
echo /tmp/vdqm_test.c; diff /tmp/vdqm_test.c .
echo /tmp/vdqmapi.c; diff /tmp/vdqmapi.c .
echo /tmp/vdqmserv.c; diff /tmp/vdqmserv.c .
