.\" @(#)$RCSfile: nschmod.man,v $ $Revision: 1.2 $ $Date: 2006/01/26 15:36:21 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 1999-2002 by CERN/IT/PDP/DM
.\" All rights reserved
.\"
.TH NSCHMOD 1 "$Date: 2006/01/26 15:36:21 $" CASTOR "Cns User Commands"
.SH NAME
nschmod \- change access mode of a CASTOR directory/file in the name server
.SH SYNOPSIS
.B nschmod
.I absolute_mode
.IR path ...
.SH DESCRIPTION
.B nschmod
sets the access mode of CASTOR directory/file(s) in the name server to the octal
value in
.IR absolute_mode .
Symbolic mode changes are not supported yet.
.LP
The effective user ID of the process must match the owner of the file or
the caller must have ADMIN privilege in the Cupv database.
.TP
.I path
specifies the CASTOR pathname.
If
.I path
does not start with
.BR / ,
it is prefixed by the content of the
.B CASTOR_HOME
environment variable.
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Castor_limits(4) ,
.BR Cns_chmod(3) ,
.BR Cupvlist(1)
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
