.\" @(#)$RCSfile: nsdeleteclass.man,v $ $Revision: 1.2 $ $Date: 2006/01/26 15:36:22 $ CERN IT-PDP/DM Jean-Philippe Baud
.\" Copyright (C) 2000-2002 by CERN/IT/PDP/DM
.\" All rights reserved
.\"
.TH NSDELETECLASS 1 "$Date: 2006/01/26 15:36:22 $" CASTOR "Cns Administrator Commands"
.SH NAME
nsdeleteclass \- delete a fileclass definition
.SH SYNOPSIS
.B nsdeleteclass
.BI --id " classid"
.BI --name " class_name"
[
.BI -h " name_server"
]
.SH DESCRIPTION
.B nsdeleteclass
deletes a fileclass definition.
The fileclass can be identified by
.I classid
or by
.IR class_name .
If both are specified, they must point at the same class.
.LP
This command requires ADMIN privilege in the Cupv database.
.SH OPTIONS
.TP
.BI -h " name_server"
.TP
.BI --id " classid"
The class number of the class to be deleted.
.TP
.BI --name " class_name"
The name of the class to be deleted.
.SH EXAMPLES
.nf
.ft CW
nsdeleteclass --id 2 --name user
.ft
.fi
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Castor_limits(4) ,
.BR Cns_deleteclass(3) ,
.B Cupvlist(1)
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
