.\" @(#)$RCSfile: nsgetpath.man,v $ $Revision: 1.2 $ $Date: 2008/11/03 10:37:05 $ CERN Castor Dev team
.\" Copyright (C) 2003  CERN
.\" All rights reserved
.\"
.TH NSGETPATH 1 "$Date: 2008/11/03 10:37:05 $" CASTOR "Cns User Commands"
.SH NAME
nsgetpath \- get file path from fileid
.SH SYNOPSIS
.B nsgetpath
<\fCNSHOST\fR> [FILEID|-x HEXID\fR]
.SH DESCRIPTION
.B nsgetpath
gets the name of the castorfile given by its fileid and the name
server where it resides.
.SH OPTIONS
.TP
.B -x,\ \-\-hex=HEXID
Fileid expressed in hexadecimal form.
.TP
.B \-\-help
display this help and exit
.SH EXAMPLES
.BI #\ nsgetpath\ cnsuser\ 183591842
.fi
/castor/cern.ch/c3/itdc/notape/47eb6a9a-7cd5-439f-b156-0a953098b1ca

.BI #\ nsgetpath\ cnsuser\ -x\ AF163A2
.fi
/castor/cern.ch/c3/itdc/notape/47eb6a9a-7cd5-439f-b156-0a953098b1ca

.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation failed.
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>

