.\" @(#)$RCSfile: nsmodifyusrmap.man,v $ $Revision: 1.2 $ $Date: 2006/01/26 15:36:23 $ CERN IT-GD/SC Jean-Philippe Baud
.\" Copyright (C) 2005 by CERN/IT/GD/SC
.\" All rights reserved
.\"
.TH NSMODIFYUSRMAP 3 "$Date: 2006/01/26 15:36:23 $" CASTOR "Cns Administrator Commands"
.SH NAME
nsmodifyusrmap \- modify user entry corresponding to a given virtual uid
.SH SYNOPSIS
.B nsmodifyusrmap
.BI --uid " uid"
.BI --user " newname"
.SH DESCRIPTION
.B nsmodifyusrmap
modifies the user entry corresponding to a given virtual uid.
.LP
This command requires ADMIN privilege.
.SH OPTIONS
.TP
.BI --uid " uid"
specifies the Virtual User Id.
.TP
.BI --user " newname"
specifies the new user name.
It must be at most 255 characters long.
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.B Cns_modifyusrmap(3)
