.\" @(#)$RCSfile: nssetchecksum.man,v $ $Revision: 1.3 $ $Date: 2008/11/03 10:22:31 $ CERN IT/DM
.\" Copyright (C) 2004 by CERN/IT/D
.\" All rights reserved
.\"
.TH NSSETCHECKSUM 1 "$Date: 2008/11/03 10:22:31 $" CASTOR "Cns User Commands"
.SH NAME
nssetchecksum \- set or reset the checksum for a file
.SH SYNOPSIS
.B nssetchecksum [OPTION]... PATH
.SH DESCRIPTION
.B nssetchecksum
set or resets the checksum for a file in the name server. Requires the user to have access to
the file.
.TP
.I PATH
specifies the CASTOR pathname.
If PATH does not start with
.BR / ,
it is prefixed by the content of the
.B CASTOR_HOME
environment variable.
.SH OPTIONS
.TP
.B -n,\ \-\-name=CKSUMNAME
Name of the checksum to be stored in the name server.
.TP
.B -k,\ \-\-checksum=CKSUM
Value of the checksum to be stored in the name server.
.TP
.B --clear
Resets the checksum to a NULL name, and a 0 value.
.TP
.B \-\-help
Display this help and exit
.SH EXAMPLES

.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Castor_limits(3) ,
.BR Cns_updatefile_checksum(3)
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
