.\" @(#)$RCSfile: nstouch.man,v $ $Revision: 1.1 $ $Date: 2007/08/09 06:32:56 $ CERN Castor Dev team
.\" Copyright (C) 2003  CERN
.\" All rights reserved
.\"
.TH NSTOUCH 1 "$Date: 2007/08/09 06:32:56 $" CASTOR "Cns User Commands"
.SH NAME
nstouch \- change file timestamps
.SH SYNOPSIS
.B nstouch
.RB [ -a ]
.RB [ -c ]
.RB [ -m ]
.RB [ -t " STAMP"]
.RB path ...
.SH DESCRIPTION
.B nstouch
updates the access and modification times of CASTOR directory/files(s) in the name server to the current time.
.TP
.I path
specifies the CASTOR pathname or directory.
If
.I path
does not start with
.BR / 
it is prefixed by the content of the
.B CASTOR_HOME
environment variable.
If
.I path
does not exist and the no create 
.I -c
argument is not specified it will be created.
.SH OPTIONS
The following options are supported:
.TP
.B -a
change only the access time
.TP
.B -c
do not create any files
.TP
.B -m
change only the modification time
.TP
.B -t " STAMP"
use [[CC]YY]MMDDhhmm instead of current time
.SH EXIT STATUS
This program returns 0 if the operation was successful or >0 if the operation
failed.
.SH SEE ALSO
.BR Castor_limits(4) ,
.SH AUTHOR
\fBCASTOR\fP Team <castor.support@cern.ch>
