{{- /*
SPDX-FileCopyrightText: 2026 CERN
SPDX-License-Identifier: GPL-3.0-or-later
*/ -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-mount-decision
data:
  reset_mount_decision.sh: |
    {{ .Files.Get "scripts/reset_mount_decision.sh" | nindent 4 }}
