# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
  name                    = "cta-restore-files"
  description             = "Command-line tool to restore deleted tape files in the CTA catalogue and the EOS namespace"
  version.workspace       = true
  edition.workspace       = true
  authors.workspace       = true
  license.workspace       = true
  repository.workspace    = true
  homepage.workspace      = true
  documentation.workspace = true
  keywords.workspace      = true
  categories.workspace    = true
  publish.workspace       = true
  readme                  = "README.md"

[lints]
  workspace = true

[dependencies]
  cta-lib      = { workspace = true }
  eos-protobuf = { workspace = true }
  cta-protobuf = { workspace = true }

  tonic        = { workspace = true, features = ["tls-native-roots", "tls-ring"] }
  tonic-prost  = { workspace = true }
  prost        = { workspace = true }
  tokio        = { workspace = true, features = ["macros", "rt-multi-thread"] }
  thiserror    = { workspace = true }
  anyhow       = { workspace = true }
  clap         = { workspace = true, features = ["env", "derive"] }
  url          = { workspace = true }
  log          = { workspace = true }
  env_logger   = { workspace = true }
  tokio-stream = { workspace = true }
  serde_json   = { workspace = true }
