# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

cancel-on-failure:
  stage: .post
  needs:
    - job: $[[ matrix.JOB_NAME ]]
      artifacts: false
      optional: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_failure
    - when: never
  image: $IMAGE_LINT # comes with curl installed
  variables:
    GIT_STRATEGY: "none" # Don't need anything from the repo for this job
  script:
    - 'curl -s -X POST --header "PRIVATE-TOKEN: ${CI_API_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines/${CI_PIPELINE_ID}/cancel"'
  parallel:
    matrix:
      - JOB_NAME: [validate-pipeline-variables, validate-project-json, unit-test-cta, build-cta-rpms-no-cache]

update-pipeline-image-version:
  stage: .post
  needs:
    - job: generate-pipeline-images-tag
      artifacts: true
    - job: build-pipeline-images
      artifacts: false
  rules:
    - if: $PIPELINE_TYPE == "UPDATE_PIPELINE_IMAGES" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $PIPELINE_TYPE == "UPDATE_PIPELINE_IMAGES" && $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
  image: $IMAGE_RELEASE
  variables:
    GIT_SUBMODULE_STRATEGY: "none"
    PIPELINE_IMAGE_UPDATE_BRANCH: "ci/update-pipeline-images-${CI_PIPELINE_ID}"
  script:
    - python3 ci/release/update_pipeline_image_version.py
        --api-url "$CI_SERVER_URL"
        --project-id "$CI_PROJECT_ID"
        --api-token "$CI_API_TOKEN"
        --target-branch "$CI_COMMIT_BRANCH"
        --source-branch "$PIPELINE_IMAGE_UPDATE_BRANCH"
        --version "$NEW_PIPELINE_IMAGE_VERSION"
