# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

modify-project-json:
  stage: .pre
  rules:
    - if: $PIPELINE_TYPE == "REGR_AGAINST_CTA_MAIN"
    - if: $PIPELINE_TYPE == "REGR_AGAINST_CTA_VERSION"
  script:
    - project_json_file="project.json"
    # Replace XRootD
    - trimmed_xrootd_version=$(echo "$CUSTOM_XROOTD_VERSION" | xargs)
    - |
      if [[ -n "$trimmed_xrootd_version" ]]; then
        echo "Updating XRootD version to: $trimmed_xrootd_version."
        tmp_file=$(mktemp)
        jq --arg new_xrd_version "$trimmed_xrootd_version" \
          --arg platform "$PLATFORM" \
          '.platforms[$platform].versionlock["group-xrootd"] = $new_xrd_version' \
          "$project_json_file" > "$tmp_file" && mv "$tmp_file" "$project_json_file"
      else
        echo "CUSTOM_XROOTD_VERSION is not provided. Skipping XRootD version replacement."
      fi
    # Replace EOS image tag
    - trimmed_eos_image_tag=$(echo "$CUSTOM_EOS_IMAGE_TAG" | xargs)
    # Grab the latest stable EOS release if not provided
    - |
      if [[ -z "$trimmed_eos_image_tag" ]]; then
        EOS_REPO_URL="https://storage-ci.web.cern.ch/storage-ci/eos/diopside/tag/testing/${PLATFORM}/x86_64/"
        echo "No CUSTOM_EOS_IMAGE_TAG provided. Getting latest release from: $EOS_REPO_URL"
        trimmed_eos_image_tag="$(dnf -q --repofrompath=temprepo,$EOS_REPO_URL --repo=temprepo repoquery --latest-limit=1 --qf "%{version}" eos-server).${PLATFORM}"
        echo "Using latest stable release: $trimmed_eos_image_tag"
      fi
    - echo "Updating EOS image tag to $trimmed_eos_image_tag."
    - tmp_file=$(mktemp)
    - jq --arg new_eos_image_tag "$trimmed_eos_image_tag"
          '.dev.eosImageTag = $new_eos_image_tag'
          "$project_json_file" > "$tmp_file" && mv "$tmp_file" "$project_json_file"
    # Populate the latest CTA version if necessary in a dotenv file so that we can use this later on
    - |
      if [[ "$PIPELINE_TYPE" == "REGR_AGAINST_CTA_VERSION" ]] && [[ -z "$CUSTOM_CTA_VERSION" ]]; then
        CTA_REPO_URL="https://cta-public-repo.web.cern.ch/stable/cta-5/${PLATFORM}/cta/x86_64/"
        echo "No CUSTOM_CTA_VERSION provided. Getting latest release from: $CTA_REPO_URL"
        CUSTOM_CTA_VERSION=$(dnf -q --repofrompath=temprepo,$CTA_REPO_URL --repo=temprepo repoquery --latest-limit=1 --qf "%{version}-%{release}" cta-taped)
        echo "Using latest stable release: $CUSTOM_CTA_VERSION"
        echo "CUSTOM_CTA_VERSION=$CUSTOM_CTA_VERSION" >> pipeline_vars.env
      fi
    # Done
    - echo "File content after replacement"
    - cat "${project_json_file}" | jq
  artifacts:
    paths:
      - project.json
    reports:
      dotenv:
        pipeline_vars.env
  when: on_success
