# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

modify-project-json:
  stage: .pre
  rules:
    - if: $PIPELINE_TYPE == "REGR_AGAINST_CTA_BRANCH"
    - if: $PIPELINE_TYPE == "REGR_AGAINST_CTA_VERSION"
  script:
    - project_json_file="project.json"
    - touch pipeline.env
    # Replace XRootD
    - trimmed_xrootd_version=$(echo "$CUSTOM_XROOTD_VERSION" | xargs)
    - |
      if [[ -n "$trimmed_xrootd_version" ]]; then
        echo "Updating XRootD version to: $trimmed_xrootd_version."
        tmp_file=$(mktemp)
        jq --arg new_xrd_version "$trimmed_xrootd_version" \
          --arg platform "$PLATFORM" \
          '.platforms[$platform].versionlock["group-xrootd"] = $new_xrd_version' \
          "$project_json_file" > "$tmp_file" && mv "$tmp_file" "$project_json_file"
      else
        echo "CUSTOM_XROOTD_VERSION is not provided. Skipping XRootD version replacement."
      fi
    # Replace EOS image tag
    - trimmed_eos_image_tag=$(echo "$CUSTOM_EOS_IMAGE_TAG" | xargs)
    # Grab the latest stable EOS release if not provided
    # Note that EOS uses "el-9" instead of "el9" for the repository >:(, so we just hardcode the platform instead of relying on $PLATFORM
    - |
      if [[ -z "$trimmed_eos_image_tag" ]]; then
        EOS_REPO_URL="https://storage-ci.web.cern.ch/storage-ci/eos/diopside/tag/testing/el-9/x86_64/"
        echo "No CUSTOM_EOS_IMAGE_TAG provided. Getting latest release from: $EOS_REPO_URL"
        trimmed_eos_image_tag="$(dnf -q --repofrompath=temprepo,$EOS_REPO_URL --repo=temprepo repoquery --latest-limit=1 --qf "%{version}" eos-server).el9"
        echo "Using latest stable release: $trimmed_eos_image_tag"
      fi
    - echo "Updating EOS image tag to $trimmed_eos_image_tag"
    - tmp_file=$(mktemp)
    - jq --arg new_eos_image_tag "$trimmed_eos_image_tag"
          '.dev.eosImageTag = $new_eos_image_tag'
          "$project_json_file" > "$tmp_file" && mv "$tmp_file" "$project_json_file"
    # Populate the latest CTA image tag if necessary in a dotenv file so that we can use this later on
    # The image tag should be identical to the version, so we simply grab the latest stable relase and assume that is our image tag
    - |
      if [[ "$PIPELINE_TYPE" == "REGR_AGAINST_CTA_VERSION" ]] && [[ -z "$CUSTOM_CTA_IMAGE_TAG" ]]; then
        CTA_REPO_URL="https://cta-public-repo.web.cern.ch/stable/cta-5/${PLATFORM}/cta/x86_64/"
        echo "No CUSTOM_CTA_IMAGE_TAG provided. Getting latest release from: $CTA_REPO_URL"
        CUSTOM_CTA_IMAGE_TAG="v$(dnf -q --repofrompath=temprepo,$CTA_REPO_URL --repo=temprepo repoquery --latest-limit=1 --qf "%{version}-%{release}" cta-taped)"
        # This stable version did not yet have Docker images available, so this is for backward compatibility. Can be removed as soon as we have a later stable release
        if [[ $CUSTOM_CTA_IMAGE_TAG == "v5.11.18.0-2.el9" ]]; then
          CUSTOM_CTA_IMAGE_TAG="v5.11.19.0-2.el9"
        fi
        echo "Using latest stable release: $CUSTOM_CTA_IMAGE_TAG"
        # Note the slightly different name. This is due to CI variable precedence
        echo "CUSTOM_CTA_IMAGE_TAG_ENV=$CUSTOM_CTA_IMAGE_TAG" >> pipeline.env
      fi
    # Done
    - echo "File content after replacement"
    - cat "${project_json_file}" | jq
  artifacts:
    paths:
      - project.json
    reports:
      dotenv: pipeline.env
