# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

.build-cta-image:
  stage: build:image
  needs:
    - job: build-cta-rpms
      optional: true # TODO in different pipelines we don't need it
    - job: modify-project-json
      optional: true
  rules:
    - if: $PIPELINE_TYPE == "SYSTEM_TEST_ONLY"
      when: never
    # For pivot CTA releases: vX.Y.0
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^.*\.0\.[0-9]+-[^-]*$/
      when: on_success
    # For non-pivot CTA releases
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^.*\.0\.[0-9]+-[^-]*$/
      when: manual
    - when: on_success
  image:
    name: $IMAGE_DOCKER_IMAGE_BUILDER
    entrypoint: [""]
  variables:
    TARGET_NAME: # Should be overwritten by one of the child jobs
    CTA_BUILD_ID: ${CI_PIPELINE_ID}git${CI_COMMIT_SHORT_SHA}
    GIT_SUBMODULE_STRATEGY: "none" # Don't need submodules for these jobs
    DOCKERFILE: ci/docker/${PLATFORM}/prod-minimal.Dockerfile
    IMAGE_NAME: ctageneric/${TARGET_NAME}
    EXTRA_BUILD_ARGS: ""
    CTA_REPO_URL: ""
  before_script:
    # TODO: createrepo and start http server in build_rpm/RPM/RPMS/x86_64
    # TODO: add version build arg for regression test
    - |
      if [[ "${PIPELINE_TYPE}" == "REGR_AGAINST_CTA_VERSION" || "${PIPELINE_TYPE}" == "IMAGE_FROM_CTA_VERSION" ]]; then
        CTA_REPO_URL="https://cta-public-repo.web.cern.ch/testing/cta-5/el9/cta/x86_64/"
      else
        CTA_REPO_URL="http://host.containers.internal:8000/"
      fi
    # For the Postgres scheduler, choose a different Dockerfile and add the "-pg" suffix to the image
    # TODO: add this minimal image
    - |
      if [[ "${SCHEDULER_TYPE}" == "pgsched" ]]; then
        DOCKERFILE="ci/docker/${PLATFORM}/prod-minimal-pg.Dockerfile"
        IMAGE_NAME="${IMAGE_NAME}-pg"
      fi
  script:
    # image comes with sh instead of bash, so no bash syntax allowed
    - |
      if [ $CI_PIPELINE_SOURCE = "merge_request_event" ]; then
        EXTRA_BUILD_ARGS="$EXTRA_BUILD_ARGS --no-push-cache"
      fi
    - echo "Authenticating against repo"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"${DOCKER_LOGIN_USERNAME}\",\"password\":\"${DOCKER_LOGIN_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - echo "Building ${DOCKERFILE} and pushing resulting image to ${CI_REGISTRY}/cta/${IMAGE_NAME}:${CTA_BUILD_ID}"
    - /kaniko/executor --context $CI_PROJECT_DIR
                       --cache=true
                       --cache-copy-layers
                       --cache-ttl=48h
                       --dockerfile $DOCKERFILE
                       --destination ${CI_REGISTRY}/cta/${IMAGE_NAME}:${CTA_BUILD_ID}
                       --target ${TARGET_NAME}
                       --build-arg CTA_REPO_URL="$CTA_REPO_URL"
                       ${EXTRA_BUILD_ARGS}
    - echo "Image pushed successfully to ${CI_REGISTRY}/cta/${IMAGE_NAME}:${CTA_BUILD_ID}"

###############################################
# Immutable images
###############################################

build-image-taped:
  extends:
    - build-cta-image
  variables:
    TARGET_NAME: "cta-taped"

build-image-rmcd:
  extends:
    - build-cta-image
  variables:
    TARGET_NAME: "cta-rmcd"

build-image-maintd:
  extends:
    - build-cta-image
  variables:
    TARGET_NAME: "cta-maintd"

# TODO: conditionally switch the variable to -grpc
build-image-frontend:
  extends:
    - build-cta-image
  variables:
    TARGET_NAME: "cta-frontend-xrd"

build-image-tools:
  extends:
    - build-cta-image
  variables:
    TARGET_NAME: "cta-tools-xrd"
