# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

spec:
  inputs:
    platform:
      type: string
---

lint-cpp:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/*.c"
        - "**/*.h"
        - "**/*.cpp"
        - "**/*.hpp"
        - ".gitlab-ci.yml"  # For changes in the image
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  image:
    name: $IMAGE_LINT
    entrypoint: ["/usr/bin/env"]
  variables:
    GIT_SUBMODULE_STRATEGY: "none"  # Don't need submodules for this job
  script:
    - cppcheck --xml
               --force
               --enable=warning,performance
               --inline-suppr
               --check-level=exhaustive
               --suppressions-list=.cppcheck-suppressions.txt
               . 2> cppcheck_out.xml
    - cppcheck-codequality --input-file=cppcheck_out.xml --output-file=cppcheck.json
    - |
      if cat cppcheck_out.xml | grep -q "<error\s"; then
        echo "cppcheck detected errors. cppcheck-codequality output:"
        cat cppcheck.json | jq -C
        exit 1
      fi
    - echo "Done. No errors detected by cppcheck"
  artifacts:
    expire_in: 7 days
    reports:
      codequality: cppcheck.json

lint-bash:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/*.sh"
        - ".gitlab-ci.yml"  # For changes in the image
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  image:
    name: $IMAGE_LINT
    entrypoint: ["/usr/bin/env"]
  variables:
    GIT_SUBMODULE_STRATEGY: "none"  # Don't need submodules for this job
  script:
    - all_shell_scripts=( **/*.sh )
    - if [ ${#all_shell_scripts[@]} -eq 0 ]; then echo "No shell scripts"; exit 0; fi
    - shellcheck "${all_shell_scripts[@]}" --format json --severity warning | tee shellcheck.json | jq -C
  artifacts:
    expire_in: 7 days
    reports:
      codequality: shellcheck.json

lint-python:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/*.py"
        - ".gitlab-ci.yml"  # For changes in the image
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  image:
    name: $IMAGE_LINT
    entrypoint: ["/usr/bin/env"]
  variables:
    GIT_SUBMODULE_STRATEGY: "none"  # Don't need submodules for this job
  script:
    - ruff check --output-format gitlab | tee ruff.json | jq -C
  artifacts:
    expire_in: 7 days
    reports:
      codequality: ruff.json

# general code quality (using clippy)
lint-rust:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/*.rs"
        - ".gitlab-ci.yml"  # For changes in the image
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  image:
    name: $IMAGE_LINT
    entrypoint: ["/usr/bin/env"]
  variables:
    GIT_SUBMODULE_STRATEGY: "recursive" # we need the proto defs
    RUST_CODE_PATH: "tools-rs"
  before_script:
    - !reference [.merge-train-guard, before_script]
    - set -o pipefail
  script:
    - |
      set +e
      cargo clippy --manifest-path ${RUST_CODE_PATH}/Cargo.toml --all-targets --all-features --message-format=json > clippy-output.json
      CARGO_EXIT_CODE=$?
      set -e

      # Fail if cargo itself failed (a genuine build error), or if any clippy diagnostic is present at warning/error level.
      # We deliberately don't pass -D warnings to cargo clippy here: doing so promotes every warning to an "error" diagnostic
      # before cargo-sonar ever sees it, which makes everything show up as "critical" in the GitLab code quality report.
      if [ "$CARGO_EXIT_CODE" -ne 0 ] || jq -e 'select(.reason == "compiler-message") | select(.message.level == "warning" or .message.level == "error")' clippy-output.json > /dev/null; then
        echo "Clippy detected errors:"
        cat clippy-output.json | jq -C
        echo "📎 Everyone makes mistakes - it's how we learn and grow."
        CLIPPY_EXIT_CODE=1
      else
        CLIPPY_EXIT_CODE=0
      fi

      # convert to code climate format (readable by GitLab)
      (cd $RUST_CODE_PATH && cargo codeclimate --clippy --clippy-path "$CI_PROJECT_DIR/clippy-output.json" --codeclimate-path "$CI_PROJECT_DIR/cargo-clippy-raw.json")

      # cargo-codeclimate must run from inside RUST_CODE_PATH, but this means the file paths it emits are relative to the former
      jq --arg prefix "$RUST_CODE_PATH/" 'map(.location.path |= $prefix + .)' "$CI_PROJECT_DIR/cargo-clippy-raw.json" > "$CI_PROJECT_DIR/cargo-clippy.json"

      exit $CLIPPY_EXIT_CODE
  artifacts:
    when: always
    expire_in: 7 days
    reports:
      codequality: cargo-clippy.json

# check for security advisories, bans, licenses and package sources
deny-rust:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/Cargo.toml"
        - "**/Cargo.lock"
        - "**/deny.toml"
        - ".gitlab-ci.yml"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  image:
    name: $IMAGE_LINT
    entrypoint: ["/usr/bin/env"]
  variables:
    GIT_SUBMODULE_STRATEGY: "none"
    RUST_CODE_PATH: "tools-rs"
  script:
    - cargo deny --manifest-path "$RUST_CODE_PATH/Cargo.toml" --config "$RUST_CODE_PATH/deny.toml" check

# check for unused dependencies
machete-rust:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/Cargo.toml"
        - "**/*.rs"
        - ".gitlab-ci.yml"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  image:
    name: $IMAGE_LINT
    entrypoint: ["/usr/bin/env"]
  variables:
    GIT_SUBMODULE_STRATEGY: "none"
    RUST_CODE_PATH: "tools-rs"
  before_script:
    - !reference [.merge-train-guard, before_script]
  script:
    - cargo machete $RUST_CODE_PATH/

lint-yaml:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/*.yaml"
        - "**/*.yml"
        - "ci/checks/check_gitlab_ci_before_script_guard.py"
        - "ci/checks/test_check_gitlab_ci_before_script_guard.py"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  image:
    name: $IMAGE_LINT
    entrypoint: ["/usr/bin/env"]
  variables:
    GIT_SUBMODULE_STRATEGY: "none"  # Don't need submodules for this job
  script:
    - python3 ci/checks/check_gitlab_ci_before_script_guard.py .gitlab-ci.yml .gitlab/ci/
    - python3 ci/checks/check_gitlab_ci_key_order.py .gitlab/
    - python3 ci/checks/check_gitlab_ci_single_stage.py .gitlab/ci/
    - yamllint .

lint-licenses:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: always
  image:
    name: $IMAGE_LICENSE_CHECK
    entrypoint: [""]
  variables:
    GIT_SUBMODULE_STRATEGY: "none"  # Don't need submodules for this job
  script:
    - reuse lint

lint-secrets:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: always
  image:
    name: $IMAGE_LINT
    entrypoint: [""]
  variables:
    GIT_SUBMODULE_STRATEGY: "none"  # Don't need submodules for this job
  script:
    - detect-secrets scan --baseline .secrets.baseline

lint-dockerfile:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "ci/docker/cta/$[[ inputs.platform ]]/prod.Dockerfile"
        - ".gitlab/ci/lint.gitlab-ci.yml"
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  image:
    name: $IMAGE_DOCKER_LINT
    entrypoint: [""]
  variables:
    GIT_SUBMODULE_STRATEGY: "none"  # Don't need submodules for this job
  script:
    - hadolint --failure-threshold warning ci/docker/cta/$[[ inputs.platform ]]/prod.Dockerfile

# Generic format check job template
# The idea is to extend this, fill in the FORMAT_DIFF variable
# And then add a before_script: section that populates this FORMAT_DIFF file
.format-report:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: always
  image: $IMAGE_LINT
  variables:
    GIT_SUBMODULE_STRATEGY: "none"  # Don't need submodules for these job
    FORMAT_DIFF:
  before_script:
    - !reference [.merge-train-guard, before_script]
    - exit 1  # The jobs that extend this job should override this
  script:
    - |
      if [[ ! -f "$FORMAT_DIFF" ]]; then
        echo "FORMAT_DIFF file not found: $FORMAT_DIFF"
        exit 1
      fi
    - |
      if [[ $(wc -l < $FORMAT_DIFF) -le 1 ]]; then
        echo "No formatting issues found"
        exit 0
      fi
    - |
      if [[ $(wc -l < $FORMAT_DIFF) -le 1000 ]]; then
        bat --style=plain --color=always $FORMAT_DIFF
      else
        echo "Format diff too large. Please check job artifacts"
      fi
    - exit 1  # format checks failed, so the job should fail
  artifacts:
    when: on_failure
    expire_in: 7 days
    paths:
      - $FORMAT_DIFF

format-cpp:
  extends:
    - .format-report
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/*.c"
        - "**/*.h"
        - "**/*.cpp"
        - "**/*.hpp"
        - "**/*.json"
        - ".gitlab-ci.yml"  # For changes in the image
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  variables:
    FORMAT_DIFF: artifacts/clang-format.diff
  before_script:
    - !reference [.merge-train-guard, before_script]
    - mkdir -p artifacts
    - TARGET_BRANCH=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-$CI_DEFAULT_BRANCH}
    - git fetch --no-tags origin $TARGET_BRANCH:$TARGET_BRANCH
    - echo "Running clang-format for changes compared to branch $TARGET_BRANCH"
    - git-clang-format $TARGET_BRANCH HEAD --diff > $FORMAT_DIFF || true

format-python:
  extends:
    - .format-report
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/*.py"
        - ".gitlab-ci.yml"  # For changes in the image
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  variables:
    FORMAT_DIFF: artifacts/ruff.diff
  before_script:
    - !reference [.merge-train-guard, before_script]
    - mkdir -p artifacts
    - echo "Running ruff on all Python files"
    - ruff format . --check --diff | sed "s|$CI_PROJECT_DIR|$CI_PROJECT_NAME|" > "$FORMAT_DIFF"

format-rust:
  extends:
    - .format-report
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/*.rs"
        - ".gitlab-ci.yml"  # For changes in the image
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  variables:
    FORMAT_DIFF: artifacts/cargo-fmt.diff
    RUST_CODE_PATH: "tools-rs"
  before_script:
    - !reference [.merge-train-guard, before_script]
    - mkdir -p artifacts
    - echo "Running cargo fmt on all Rust files"
    - cargo fmt --manifest-path ${RUST_CODE_PATH}/Cargo.toml --all -- --check > "$FORMAT_DIFF" 2>&1 || true

type-check-python:
  stage: lint
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - changes:
        - "**/*.py"
        - ".gitlab-ci.yml"  # For changes in the image
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: manual
      allow_failure: true
  image:
    name: $IMAGE_LINT
    entrypoint: ["/usr/bin/env"]
  variables:
    GIT_SUBMODULE_STRATEGY: "none"  # Don't need submodules for this job
    FORCE_COLOR: 3  # Force color output of pyright
  script:
    # Necessary dependencies, these are not in the lint image on purpose as they are project specific
    # It is a bit unfortunate we have to do this explicitly, but they are mostly independent scripts that need this,
    # so not one top-level "install all dependencies" is available
    - uv pip install --system -r ci/system_tests/requirements.txt
    - uv pip install --system pyjwt cryptography
    - pyright .
