# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

changelog-preview:
  stage: release
  needs: []  # Ensure this job can be triggered at the beginning if necessary
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $PIPELINE_TYPE != "DEFAULT"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - when: manual
      allow_failure: true
  image: $IMAGE_RELEASE
  variables:
    GIT_DEPTH: 0  # Ensure we don't do a shallow clone here as we might need to find the latest tag
    TO_COMMIT: "HEAD"
    FROM_REF: ""
    RELEASE_VERSION: ""
  before_script:
    - |
      if [[ -z "${RELEASE_VERSION}" ]]; then
        echo "Release version cannot be empty. Please set the RELEASE_VERSION variable manually in the CI."
        exit 1
      fi
  script:
    # If no from reference (commit hash or tag) is provided, grab the latest tag before the current commit
    - |
      if [[ -z "${FROM_REF}" ]]; then
        FROM_REF=$(git describe --tags --abbrev=0 ${TO_COMMIT})
      fi
    - python3 ci/release/preview_changelog.py --api-url ${CI_SERVER_URL}
                                              --project-id ${CI_PROJECT_ID}
                                              --api-token ${CI_API_TOKEN}
                                              --from ${FROM_REF}
                                              --to ${TO_COMMIT}
                                              --release-version ${RELEASE_VERSION}
                                              --markdown-output changelog_report.md
                                              --verbose
                                              --preview
    # Pass on variables so that the update_changelog job does not have to re-initialise them
    - echo -e "ENV_TO_COMMIT=${TO_COMMIT}\nENV_FROM_REF=${FROM_REF}\nENV_RELEASE_VERSION=${RELEASE_VERSION}" > vars.env
  artifacts:
    expire_in: 2 days
    paths:
      - changelog_report.md
    reports:
      dotenv: vars.env

changelog-update:
  stage: release
  needs:
    - changelog-preview
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $PIPELINE_TYPE != "DEFAULT"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - when: manual
      allow_failure: true
  image: $IMAGE_RELEASE
  variables:
    SOURCE_BRANCH: ""
  script:
    - TO_COMMIT=${ENV_TO_COMMIT}
    - FROM_REF=${ENV_FROM_REF}
    - RELEASE_VERSION=${ENV_RELEASE_VERSION}
    - |
      if [[ -z "${SOURCE_BRANCH}" ]]; then
        echo "No source branch provided. Using default branch: ${CI_DEFAULT_BRANCH}"
        SOURCE_BRANCH=${CI_DEFAULT_BRANCH}
      fi
    - python3 ci/release/update_changelog.py --api-url ${CI_SERVER_URL}
                                             --project-id ${CI_PROJECT_ID}
                                             --api-token ${CI_API_TOKEN}
                                             --from ${FROM_REF}
                                             --to ${TO_COMMIT}
                                             --release-version ${RELEASE_VERSION}
                                             --reviewer ${GITLAB_USER_ID}
                                             --source-branch ${SOURCE_BRANCH}
                                             --description-file changelog_report.md
                                             --verbose

###############################################
# Publish RPMs
###############################################

internal-release-cta:
  stage: release
  needs:
    - build-cta-rpms
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true
  image: $IMAGE_RELEASE
  script:
    - echo "Publishing to internal CTA repository"
    - ./ci/release/upload_to_eos.sh --eos-username ${DOCKER_LOGIN_USERNAME}
                                    --eos-password ${DOCKER_LOGIN_PASSWORD}
                                    --local-source-dir build_rpm/RPM/RPMS
                                    --eos-target-dir /eos/user/c/ctareg/www/cta-repo
                                    --hook /eos/user/c/ctareg/www/cta-repo/update_repos.sh

public-release-cta-unstable:
  stage: release
  needs:
    - internal-release-cta
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true
  image: $IMAGE_RELEASE
  script:
    - export CTA_VERSION=$(echo ${CI_COMMIT_TAG} | sed 's/^v//')
    - echo "Publishing CTA version ${CTA_VERSION} to unstable CTA repository"
    - ./ci/release/upload_to_eos.sh --eos-username ${DOCKER_LOGIN_USERNAME}
                                    --eos-password ${DOCKER_LOGIN_PASSWORD}
                                    --eos-source-dir /eos/user/c/ctareg/www/cta-repo/RPMS
                                    --eos-target-dir /eos/user/c/ctareg/www/public/cta-public-repo/unstable/cta-5/${PLATFORM}/cta
                                    --hook /eos/user/c/ctareg/www/public/update_repos.sh
                                    --cta-version ${CTA_VERSION}
    - REPO_URL="https://cta-public-repo.web.cern.ch/unstable/cta-5/el9/cta/x86_64"
    - ./ci/release/check_rpm_available.sh --repository-url "$REPO_URL" --package "cta-taped" --version "$CTA_VERSION"

public-release-cta-testing:
  stage: release
  needs:
    - internal-release-cta
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true
  image: $IMAGE_RELEASE
  script:
    - export CTA_VERSION=$(echo ${CI_COMMIT_TAG} | sed 's/^v//')
    - echo "Publishing CTA version ${CTA_VERSION} to testing CTA repository"
    - ./ci/release/upload_to_eos.sh --eos-username ${DOCKER_LOGIN_USERNAME}
                                    --eos-password ${DOCKER_LOGIN_PASSWORD}
                                    --eos-source-dir /eos/user/c/ctareg/www/cta-repo/RPMS
                                    --eos-target-dir /eos/user/c/ctareg/www/public/cta-public-repo/testing/cta-5/${PLATFORM}/cta
                                    --hook /eos/user/c/ctareg/www/public/update_repos.sh
                                    --cta-version ${CTA_VERSION}
    - REPO_URL="https://cta-public-repo.web.cern.ch/testing/cta-5/el9/cta/x86_64"
    - ./ci/release/check_rpm_available.sh --repository-url "$REPO_URL" --package "cta-taped" --version "$CTA_VERSION"

public-release-cta-stable:
  stage: release
  needs:
    - internal-release-cta
    # Anything in stable must also be in unstable and testing
    - public-release-cta-unstable
    - public-release-cta-testing
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true
  image: $IMAGE_RELEASE
  script:
    - export CTA_VERSION=$(echo ${CI_COMMIT_TAG} | sed 's/^v//')
    - echo "Publishing CTA version ${CTA_VERSION} to public CTA repository"
    - ./ci/release/upload_to_eos.sh --eos-username ${DOCKER_LOGIN_USERNAME}
                                    --eos-password ${DOCKER_LOGIN_PASSWORD}
                                    --eos-source-dir /eos/user/c/ctareg/www/cta-repo/RPMS
                                    --eos-target-dir /eos/user/c/ctareg/www/public/cta-public-repo/stable/cta-5/${PLATFORM}/cta
                                    --hook /eos/user/c/ctareg/www/public/update_repos.sh
                                    --cta-version ${CTA_VERSION}
    - REPO_URL="https://cta-public-repo.web.cern.ch/stable/cta-5/el9/cta/x86_64"
    - ./ci/release/check_rpm_available.sh --repository-url "$REPO_URL" --package "cta-taped" --version "$CTA_VERSION"


###############################################
# Publish Images
###############################################

.image-targets: &image-targets
  - cta-taped
  - cta-rmcd
  - cta-maintd
  - cta-frontend
  - cta-tools

.publish-image:
  stage: release
  needs:
    - job: build-cta-images
      parallel:
        matrix:
          - TARGET_NAME: ['$[[ matrix.TARGET_NAME ]]']
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
      allow_failure: true
  image:
    name: $IMAGE_DOCKER_IMAGE_BUILDER
    entrypoint: [""]
  variables:
    CTA_BUILD_ID: ${CI_PIPELINE_ID}git${CI_COMMIT_SHORT_SHA}
    SRC_IMAGE: ${DOCKER_IMAGE_REGISTRY}/${DOCKER_PRIVATE_REGISTRY_PREFIX}/${TARGET_NAME}:${CTA_BUILD_ID}
    GIT_SUBMODULE_STRATEGY: none
  before_script:
    - echo "$SOURCE_REGISTRY_PASSWORD" | buildah login
        -u "$SOURCE_REGISTRY_USERNAME"
        --password-stdin
        "$CI_REGISTRY"
    - echo "$DEST_REGISTRY_PASSWORD" | buildah login
        -u "$DEST_REGISTRY_USERNAME"
        --password-stdin
        "$DEST_REGISTRY"
  script:
    - DST_IMAGE="${DEST_REGISTRY}/${DEST_IMAGE_PREFIX}/${TARGET_NAME}:${CI_COMMIT_TAG}.${PLATFORM}"
    - echo "Publishing ${SRC_IMAGE} -> ${DST_IMAGE}"
    - buildah pull "$SRC_IMAGE"
    - buildah tag "$SRC_IMAGE" "$DST_IMAGE"
    - buildah push "$DST_IMAGE"

publish-images-private:
  extends: .publish-image
  variables:
    DEST_REGISTRY: $DOCKER_IMAGE_REGISTRY
    DEST_IMAGE_PREFIX: $DOCKER_PRIVATE_REGISTRY_PREFIX

    SOURCE_REGISTRY_USERNAME: $DOCKER_LOGIN_USERNAME
    SOURCE_REGISTRY_PASSWORD: $DOCKER_LOGIN_PASSWORD

    DEST_REGISTRY_USERNAME: $DOCKER_LOGIN_USERNAME
    DEST_REGISTRY_PASSWORD: $DOCKER_LOGIN_PASSWORD
  parallel:
    matrix:
      - TARGET_NAME: *image-targets

publish-images-public:
  extends: .publish-image
  rules:
    - if: $ENABLE_ORACLE_SUPPORT == "TRUE"
      when: never
    - !reference [.publish-image, rules]
  variables:
    DEST_REGISTRY: $DOCKER_IMAGE_REGISTRY
    DEST_IMAGE_PREFIX: $DOCKER_PUBLIC_REGISTRY_PREFIX

    SOURCE_REGISTRY_USERNAME: $DOCKER_LOGIN_USERNAME
    SOURCE_REGISTRY_PASSWORD: $DOCKER_LOGIN_PASSWORD

    # If this does not work, we may need different credentials for the public registry
    DEST_REGISTRY_USERNAME: $DOCKER_LOGIN_USERNAME
    DEST_REGISTRY_PASSWORD: $DOCKER_LOGIN_PASSWORD
  before_script:
    - |
      if [[ "$ENABLE_ORACLE_SUPPORT" == "TRUE" ]]; then
        echo "Oracle-enabled images cannot be published publicly."
        exit 1
      fi
    - !reference [.publish-image, before_script]
  parallel:
    matrix:
      - TARGET_NAME: *image-targets
