# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

validate-catalogue-schema-version:
  stage: validate
  needs:
    - job: check-merge-train-duplicate
      optional: true
  rules:
    - if: '$PIPELINE_TYPE != "DEFAULT"'
      when: never
    # Tags and the default branch require the catalogue schema submodule commit to be tagged.
    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
      variables:
        CATALOGUE_SCHEMA_CHECK_PARAMS: "-t"
    # Other pipelines validate the schema versions without requiring a submodule tag.
    - when: on_success
      variables:
        CATALOGUE_SCHEMA_CHECK_PARAMS: ""
  script:
    - ./ci/checks/check_catalogue_schema_version.sh ${CATALOGUE_SCHEMA_CHECK_PARAMS}

validate-project-json:
  stage: validate
  needs:
    - job: check-merge-train-duplicate
      optional: true
    - job: modify-project-json
      optional: true
  rules:
    - when: on_success
  script:
    - python3 ./ci/project-json/validate_project_json.py
